      BLOCK DATA HSTBKD
C
      COMMON /HSTGC1/ HORZNT, PERCNT, MIDVAL, SHADE, MEDIAN, PERIM,
     -       HFRAME, LISTOP, WINDOW, COLORS, HSTFOR, TITLE, LABEL,
     -       FREQNC, HWIND(4), COLSHA, COLREC, COLAXI, COLMED, COLTEX,
     -       COLTIT, COLPER, DRAWL, SPACE, LABMAX, CHARL, HEIGHT,
     -       ORIENT, COLSH2, SETSPA, SETSP2, MVALU, SETMVA, SETEPS,
     -       NMVAL, PMVAL
      LOGICAL HORZNT, PERCNT, MIDVAL, SHADE, MEDIAN, PERIM, HFRAME,
     -        LISTOP, WINDOW, COLORS, HSTFOR, TITLE, LABEL, FREQNC,
     -        DRAWL, SPACE, CHARL, MVALU, NMVAL, PMVAL
      COMMON /HSTGC2/ STRFOR, STRTIT, STRLAB, STRFRE, LABTEX
      CHARACTER*96  STRTIT
      CHARACTER*55  STRFOR, STRLAB, STRFRE
      CHARACTER*15 LABTEX(30)
      INTEGER  COLSHA, COLREC, COLAXI, COLMED, COLTEX
      INTEGER  COLTIT, COLPER, COLSH2, HEIGHT, ORIENT
C
      DATA HORZNT /.FALSE./
      DATA PERCNT /.TRUE./
      DATA MIDVAL /.TRUE./
      DATA SPACE  /.TRUE./
      DATA SHADE  /.TRUE./
      DATA DRAWL  /.FALSE./
      DATA MEDIAN /.FALSE./
      DATA PERIM  /.FALSE./
      DATA HFRAME /.TRUE./
      DATA LISTOP /.FALSE./
      DATA WINDOW /.FALSE./
      DATA COLORS /.FALSE./
      DATA HSTFOR /.FALSE./
      DATA TITLE  /.FALSE./
      DATA LABEL  /.FALSE./
      DATA FREQNC /.FALSE./
      DATA CHARL  /.FALSE./
      DATA MVALU  /.FALSE./
      DATA NMVAL  /.TRUE./
      DATA PMVAL  /.TRUE./
      DATA HWIND  /0.,1.,0.,1./
      DATA COLSHA /1/
      DATA COLSH2 /1/
      DATA COLREC /1/
      DATA COLAXI /1/
      DATA COLMED /1/
      DATA COLTEX /1/
      DATA COLTIT /1/
      DATA COLPER /1/
      DATA HEIGHT /2/
      DATA ORIENT /0/
      DATA SETSPA /2./
      DATA SETSP2 /0./
      DATA SETMVA /-9999./
      DATA SETEPS /1.E-10/
      DATA STRFOR / '(G10.3)' /
      END
