/*
 * Deutscher Wetterdienst (DWD): Offenbach
 * Center: 78
 * Subcenter: 0
 * Parameter table version: 201
 */

TBLE2 dwd_201_params[] = {
{1,   "downward shortwave radiant flux density",     "W/m**2", "DW_SW_FLUX"},
{2,   "upward shortwave radiant flux density",   "W/m**2", "UW_SW_FLUX"},
{3,   "downward longwave radiant flux density",  "W/m**2", "DW_LW_FLUX"},
{4,   "upward longwave radiant flux density",    "W/m**2", "UW_LW_FLUX"},
{5,   "surface photosynthetic active radiation",   "W m-2", "PABS_RAD"},
{6,   "net shortwave flux",  "W/m**2", "NET_S_FLUX"},
{7,   "net longwave flux",   "W/m**2", "NET_L_FLUX"},
{8,   "total net radiative flux density",    "W/m**2", "NET_FLUX"},
{9,   "downw shortw radiant flux density, cloudfree part",   "W/m**2", "DW_SW_CLFR"},
{10,  "upw shortw radiant flux density, cloudy part",    "W/m**2", "UW_SW_CLDY"},
{11,  "downw longw radiant flux density, cloudfree part",    "W/m**2", "DW_LW_CLFR"},
{12,  "upw longw radiant flux density, cloudy part",     "W/m**2", "UW_LW_CLDY"},
{13,  "solar radiation heating rate in the atmosphere",    "K s-1", "SOHR_RAD"},
{14,  "thermal radiation heating rate in the atmosphere",     "K s-1", "THHR_RAD"},
{15,  "total radiative heating rate",    "K/s", "RAD_HEAT"},
{16,  "soil heat flux, surface",     "W/m**2", "SOILHEAT_S"},
{17,  "soil heat flux, bottom of layer",     "W/m**2", "SOILHEAT_L"},
{20,  "sunshine hours",  "h", "SUNSHHRS"},
{29,  "cloud area fraction",    "index", "CLC"},
{30,  "grid scale cloud area fraction",     "index", "CLC_SGS"},
{31,  "specific cloud liquid water content",    "kg kg-1", "QC"},
{32,  "cloud water content, grid scale, vert integrated",    "kg/m**2", "CLW_GS_VI"},
{33,  "specific cloud ice content",  "kg kg-1", "QI"},
{34,  "cloud ice content, grid scale, vert integrated",  "kg/m**2", "CLI_GS_VI"},
{35,  "specific rainwater content",  "kg kg-1", "QR"},
{36,  "specific snow content, grid scale",   "kg/kg", "SSC_GR_SC"},
{37,  "total rain water content vertically integrated",    "kg m-2", "TQR"},
{38,  "total snow content vertically integrated",     "kg m-2", "TQS"},
{39,  "specific graupel content",    "kg kg-1", "QG"},
{40,  "total graupel content vertically integrated",  "kg m-2", "TQG"},
{41,  "cloud conensed water content",   "kg m-2", "T_WATER"},
{42,  "atmosphere water divergence",  "kg m-2", "TDIV_HUM"},
{43,  "sub scale specific cloud water content",    "kg kg-1", "QC_RAD"},
{44,  "subscale specific cloud ice content",  "kg kg-1", "QI_RAD"},
{50,  "cloud covers CH_CM_CL (000...888)",   "index", "CH_CM_CL"},
{51,  "cloud cover CH (0..8)",   "index", "CL_COV_CH"},
{52,  "cloud cover CM (0..8)",   "index", "CL_COV_CM"},
{53,  "cloud cover CL (0..8)",   "index", "CL_COV_CL"},
{54,  "total cloud cover (0..8)",    "index", "CLOUD_COV"},
{55,  "fog (0..8)",  "index", "FOG"},
{56,  "fog",  "%", "FOG"},
{58,  "height of shallow convective cloud base",  "m", "HBAS_SC"},
{59,  "height of shallow convective cloud top",   "m", "HTOP_SC"},
{60,  "cloud cover, convective cirrus (0...1)",  "index", "CLC_CON_CI"},
{61,  "convective cloud liquid water",     "kg kg-1", "CLW_CON"},
{62,  "cloud water content, conv clouds, vert integrated",   "kg/m**2", "CLW_CON_VI"},
{63,  "specific cloud ice content, convective clouds",   "kg/kg", "CLI_CON"},
{64,  "cloud ice content, conv clouds, vert integrated",     "kg/m**2", "CLI_CON_VI"},
{65,  "convective mass flux",    "kg/(s*m**2)", "MASS_FL_CO"},
{66,  "updraft velocity, convection",    "m/s", "UPD_VEL_CO"},
{67,  "entrainment parameter, convection",   "m**(-1)", "ENTR_P_CO"},
{68,  "height of convective cloud base",   "m", "HBAS_CON"},
{69,  "height of convective cloud top",    "m", "HTOP_CON"},
{70,  "convective layers (00...77) (BKE)",   "index", "CON_LAYERS"},
{71,  "KO-index",    "index", "KO_INDEX"},
{72,  "index of convective cloud base",   "index", "BAS_CON"},
{73,  "index of convective cloud top",    "index", "TOP_CON"},
{74,  "convective tendency of temperature",     "K s-1", "DT_CON"},
{75,  "convective tendency of specific humidity",    "s-1", "DQV_CON"},
{76,  "convective tendency of total heat",   "J/(kg*s)", "H_TEN_CO"},
{77,  "convective tendency of total water",  "s**(-1)", "QDW_TEN_CO"},
{78,  "convective tendency of u-wind component",  "m s-2", "DU_CON"},
{79,  "convective tendency of v-wind component",  "m s-", "DV_CON"},
{80,  "convective vorticity tendency",   "s**(-2)", "VOR_TEN_CO"},
{81,  "convective divergence tendency",  "s**(-2)", "DIV_TEN_CO"},
{82,  "height of dry convection top",   "m", "HTOP_DC"},
{83,  "dry convection top index",  "index", "TOP_IND_DC"},
{84,  "height of 0 degree Celsius isotherm above msl",   "m", "0_C_AB_MSL"},
{85,  "height of snow fall limit in m above sea level",  "m", "SNOWLMT"},
{91,  "shape factor of temperature profile in lake thermocline",  "index", "C_T_LK"},
{92,  "attenuation coefficient for solar radiation in lake water",     "m-1", "GAMSO_LK"},
{93,  "thickness of thermally active layer of bottom sediment",  "m", "DP_BS_LK"},
{94,  "thickness of the upper layer of bottom sediments",    "m", "H_B1_LK"},
{95,  "thickness of the mixed layer",    "m", "H_ML_LK"},
{96,  "lake depth",  "m", "DEPTH_LK"},
{97,  "wind fetch over lake",  "m", "FETCH_LK"},
{99,  "precipitation water (water loading)",   "index", "QRS"},
{100, "mass flux density of large scale rainfall",    "kg m-2 s-1", "PRR_GSP"},
{101, "mass flux density of large scale snowfall",    "kg m-2 s-1", "PRS_GSP"},
{102, "large scale rainfall",  "kg m-2", "RAIN_GSP"},
{103, "condensation rate, grid scale",   "kg/(kg*s)", "CONDENS_GS"},
{104, "autoconversion rate, grid scale (C+C -->; R)",  "kg/(kg*s)", "AUTOCON_GS"},
{105, "accretion rate, grid scale (R+C -->; R)",   "kg/(kg*s)", "ACCRET_GS"},
{106, "nucleation rate, grid scale (C+C -->; S)",  "kg/(kg*s)", "NUCLEAT_GS"},
{107, "riming rate, grid scale (S+C -->; S)",  "kg/(kg*s)", "RIMING_GS"},
{108, "deposition rate, grid scale (S+V <;-->; S)",  "kg/(kg*s)", "DEPOSIT_GS"},
{109, "melting rate, grid scale (S -->; R)",   "kg/(kg*s)", "MELTING_GS"},
{110, "evaporation rate, grid scale (R+V <;-- R)",     "kg/(kg*s)", "EVAPOR_GS"},
{111, "mass flux density of convective rainfall",    "kg m-2 s-1", "PRR_CON"},
{112, "mass flux density of convective snowfall",    "kg m-2 s-1", "PRS_CON"},
{113, "convective rainfall",  "kg m-2", "RAIN_CON"},
{114, "condensation rate, convective",   "kg/(kg*s)", "CONDENS_CO"},
{115, "autoconversion rate, convective",     "kg/(kg*s)", "AUTOCON_CO"},
{116, "accretion rate, convective",  "kg/(kg*s)", "ACCRET_CO"},
{117, "nucleation rate, convective",     "kg/(kg*s)", "NUCLEAT_CO"},
{118, "riming rate, convective",     "kg/(kg*s)", "RIMING_CO"},
{119, "sublimation rate, convective",    "kg/(kg*s)", "SUBLIM_CO"},
{120, "melting rate, convective",    "kg/(kg*s)", "MELTING_CO"},
{121, "evaporation rate, convective",    "kg/(kg*s)", "EVAPOR_CO"},
{122, "rain amount, grid-scale plus convective",     "kg/m**2", "RAIN_AM"},
{123, "snow amount, grid-scale plus convective",     "kg/m**2", "SNOW_AM"},
{124, "temperature tendency, grid-scale condensation",   "K/s", "TEM_TEN_GS"},
{125, "tendency of specific humidity, grid-scale condens",   "s**(-1)", "MOI_TEN_GS"},
{126, "tendency of total heat, grid-scale condensation",     "J/(kg*s)", "H_TEN_GS"},
{127, "tendency of total water, grid-scale condensation",    "s**(-1)", "QDW_TEN_GS"},
{128, "snowfall (dimension: m of water equivalence)",    "m", "SNOWFALL"},
{129, "freshness of snow",   "index", "FRESHSNW"},
{130, "tend of the sp cl ice cont due to gs precipitation",  "kg/(kg*s)", "TSCIC_GSPR"},
{131, "mass flux density of large scale graupel",     "kg m-2 s-1", "PRG_GSP"},
{132, "surface precipitation amount, graupel, grid scale",   "kg/(m**2)", "GRA_AM_GS"},
{133, "density of snow",    "kg m-3", "RHO_SNOW"},
{139, "deviation from reference pressure",  "Pa", "PP"},
{140, "standard deviation of saturation deficit",    "non-dim", "RCLD"},
{143, "capeof most unstable parcel",    "J kg-1", "CAPE_MU"},
{144, "convective inhibition of most unstable parcel",    "J kg-1", "CIN_MU"},
{145, "cape of mean surf layer parcel",    "J kg-1", "CAPE_ML"},
{146, "convective inhibition of mean surface layer parcel",   "J kg-1", "CIN_ML"},
{147, "convective turbulent kinetic energy",     "J/kg", "TKE_CON"},
{148, "tendency of turbulent kinetic energy",    "m/s", "TKETENS"},
{149, "kinetic energy ((u**2 + v**2) / 2)", "J/kg", "KE"},
{150, "coefficient of horizontal diffusion",     "m**2/s", "HDI_COEFF"},
{151, "dissipation rate",    "W/(Pa*m**2)", "DISSP_RATE"},
{152, "turbulent kinetic energy",    "J/kg", "TKE"},
{153, "coefficient of vertical diffusion, momentum",     "m**2/s", "VDI_COE_MO"},
{154, "coefficient of vertical diffusion, heat",     "m**2/s", "VDI_COE_HE"},
{155, "coefficient of vertical diffusion, cloud water",  "m**2/s", "VDI_COE_CW"},
{156, "coefficient of vertical diffusion, cloud ice",    "m**2/s", "VDI_COE_CI"},
{157, "coefficient of vertical diffusion, water vapour",     "m**2/s", "VDI_COE_VP"},
{158, "turbulent dissipation length for momentum",   "m", "DIS_LEN_M"},
{159, "turbulent dissipation length for heat",   "m", "DIS_LEN_H"},
{160, "variance of u-component of momentum",     "(m/s)**2", "VAR_U_MOM"},
{161, "variance of v-component of momentum",     "(m/s)**2", "VAR_V_MOM"},
{162, "variance of w-component of momentum",     "(m/s)**2", "VAR_W_MOM"},
{163, "variance of temperature",     "K**2", "VAR_TEMP"},
{164, "variance of specific cloud water content",    "(kg/kg)**2", "VAR_CL_WAT"},
{165, "variance of specific cloud ice content",  "(kg/kg)**2", "VAR_CL_ICE"},
{166, "variance of water vapour mixing ratio",   "(kg/kg)**2", "VAR_VAP_MR"},
{167, "turbulent vertical flux of spec cloud water",     "m/s", "C_WAT_FLUX"},
{168, "turbulent vertical flux of spec cloud ice",   "m/s", "C_ICE_FLUX"},
{169, "turbulent vertical flux of water vapour mix ratio",   "m/s", "W_VAP_FLUX"},
{170, "drag coefficient CD",     "index", "DR_COEF_CD"},
{171, "transfer coefficient CH (sensible heat)",     "index", "TR_COEF_CH"},
{172, "transfer coefficient CQ (latent heat)",   "index", "TR_COEF_CQ"},
{173, "PBL-top h",   "m", "PBL_TOP_H"},
{174, "temperature jump at PBL-top",     "K", "T_JUMP_H"},
{175, "specific humidity jump at PBL-top",   "kg/kg", "Q_JUMP_H"},
{176, "entrainment at PBL-top",  "kg/(s*m**2)", "ENTR_AT_H"},
{177, "upward mass flux at PBL-top",     "kg/(s*m**2)", "MASS_FL_H"},
{178, "cloud cover of PBL-clouds (0...1)",   "index", "CL_COV_PBL"},
{179, "specific cloud water content of PBL-clouds",  "kg/kg", "CL_WAT_PBL"},
{180, "cloud top of PBL-clouds",     "m", "CL_TOP_PBL"},
{181, "cloud base of PBL-clouds",    "m", "CL_BAS_PBL"},
{182, "vertical mountain wave momentum flux (X component)",  "kg/(m*s**2)", "MOUN_WAV_X"},
{183, "vertical mountain wave momentum flux (Y component)",  "kg/(m*s**2)", "MOUN_WAV_Y"},
{184, "wave Richardson number",  "index", "WAVE_RI"},
{185, "mountain wave momentum flux divergence (X comp)",     "m/s**2", "WAV_DIV_X"},
{186, "mountain wave momentum flux divergence (Y comp)",     "m/s**2", "WAV_DIV_Y"},
{187, "maximum 10m wind speed",   "m s-1", "VMAX_10M"},
{188, "mountain wave dissipation, vert integrated",  "W/m**2", "WAV_DIS_VI"},
{189, "vertical wave energy flux",   "kg*m/s**4", "WV_EN_FLUX"},
{190, "climatological temperature at bottom of thermally active layer of sediments", "K", "T_BS_LK"},
{191, "temperature at the water bottom sediment interface",  "K", "T_BOT_LK"},
{192, "temperature at bottom of upper layer of sedients",  "K", "T_B1_LK"},
{193, "mixed layer temperature",     "K", "T_WML_LK"},
{194, "mean temperature of water column",    "K", "T_MNW_LK"},
{195, "lake surface temperature",    "K", "T_SFC_LK"},
{197, "soil temperature",  "K", "T_SO"},
{198, "soil water content",  "kg m-2", "W_SO"},
{199, "soil frozen water content",  "kg m-2", "W_SO_ICE"},
{200, "canopy water amount",     "kg m-2", "W_I"},
{201, "icebit for interception store",   "index", "INTERC_ICE"},
{202, "snow fraction",   "index", "SNOW_FRACT"},
{203, "snow surface temperature",    "K", "T_SNOW"},
{204, "foliage temperature",     "K", "FOLIAG_TEM"},
{205, "infiltration",    "m/s", "INFILTRAT"},
{206, "runoff",  "m/s", "RUNOFF"},
{207, "bare soil evaporation",   "m/s", "SOIL_EVAP"},
{208, "plant transpiration",     "m/s", "PLANT_TRAN"},
{209, "interception store evaporation",  "m/s", "INTER_EVAP"},
{210, "evaporation from water surfaces",     "m/s", "WATER_EVAP"},
{211, "aerodynamic resistance",  "s/m", "AERO_RESIS"},
{212, "plant resistance",    "s/m", "PLANT_RES"},
{213, "soil resistance",     "s/m", "SOIL_RES"},
{214, "total evaporation (water, soil, plants)",     "m/s", "TOTAL_EVAP"},
{215, "temperature of ice upper surface",  "K", "T_ICE"},
{217, "maximum wind velocity (modified)",    "m/s", "MAX_WIND_M"},
{230, "reflectivity",    "dBz", "REFLECTIV"},
{231, "FE1",     "index", "FE1"},
{232, "FE1",     "index", "FE1"},
{233, "FE1",     "index", "FE1"},
{234, "FE1",     "index", "FE1"},
{235, "FE1",     "index", "FE1"},
{236, "sum of all contributions to evapotranspiration",  "kg m-2", "EVATRA_SUM"},
{237, "total transpiration from all soil layers",    "kg m-2", "TRA_SUM"},
{238, "total forcing at soil surface",   "W m-2", "TOTFORCE_S"},
{239, "residuum of soil moisture",   "kg m-2", "RESID_WSO"},
{240, "convective mass flux density",   "kg m-2 s-1", "MFLX_CON"},
{241, "specific convectively available potential energy",   "J kg-1", "CAPE_CON"},
{242, "moisture convergence below convective cloud base",    "1/s", "MC_CONVCLB"},
{243, "moisture convergence in the air for Kuotype closure",   "s-1", "QCVG_CON"},
{244, "MOS Gewitter-Wahrscheinlichkeit (frequent)",  "%", "MOS_PTS_FQ"},
{245, "MOS Gewitteranteil (occasional - frequent (1 - 2))",  "index", "MOS_TS_COV"},
{246, "S17",     "index", "S17"},
{247, "S18",     "index", "S18"},
{248, "S19",     "index", "S19"},
{249, "S20",     "index", "S20"},
{250, "Wahrscheinlichkeit mindestens ein Blitz",     "%", "MOS_TSISO1"},
{251, "Wahrscheinlichkeit mindestens zehn Blitze",   "%", "MOS_TSISO2"},
{252, "Wahrscheinlichkeit mindestens hundert Blitze",    "%", "MOS_TSISO3"},
{253, "Vorhersage der Blitzanzahl",  "index", "MOS_TS_DEN"},
{254, "Gewitter-Wahrscheinlichkeit (occasional)",    "%", "MOS_TS_OCC"},
{255, "Gewitter-Wahrscheinlichkeit (frequent)",  "%", "MOS_TS_FRQ"}
};
