/*
 * Deutscher Wetterdienst (DWD): Offenbach
 * Center: 78
 * Subcenter: 0
 * Parameter table version: 2
 */

TBLE2 dwd_002_params[] = {
{1,   "pressure",    "Pa", "P"},
{2,   "pressure reduced to MSL",     "Pa", "PMSL"},
{3,   "surface pressure change",   "Pa s-1", "DPSDT"},
{4,   "potential voreticity",    "K*(m**2)/(kg*s)", "POT_VORTIC"},
{5,   "ICAO standard atmosphere reference height",   "m", "ICAO_SA_RH"},
{6,   "geopotential",    "m2 s-2", "FI"},
{7,   "geopotential height",     "gpm", "GEOPOT_H"},
{8,   "height",  "m", "HHL"},
{9,   "standard deviation of height",    "m", "DEV_OF_H"},
{10,  "vertical integrated ozone content", "Dobson", "TO3"},
{11,  "temperature", "K", "T"},
{12,  "virtual temperature",     "K", "VIRT_TEMP"},
{13,  "potential temperature",   "K", "POT_TEMP"},
{14,  "pseudo-adiabatic potential temperature",  "K", "PSEUDO_POT"},
{15,  "2m maximum temperature",     "K", "TMAX_2M"},
{16,  "2m minimum temperature",     "K", "TMIN_2M"},
{17,  "2m dew point temperature",   "K", "TD_2M"},
{18,  "dew-point depression (or deficit)",   "K", "DEW_PNT_DE"},
{19,  "laps rate",   "K/m", "LAPSE_RATE"},
{20,  "visibility",  "m", "VISIBILITY"},
{21,  "radar spectra (1),"   "non-dim", "RADAR_SP_1"},
{22,  "radar spectra (2),"   "non-dim", "RADAR_SP_2"},
{23,  "radar spectra (3),"   "non-dim", "RADAR_SP_3"},
{24,  "parcel lifted index (to 500 hPa)",    "K", "PLI_TO_500"},
{25,  "temperature anomaly",     "K", "TEMP_ANOM"},
{26,  "pressure anomaly",    "Pa", "PRES_ANOM"},
{27,  "geopotential height anomaly",     "gpm", "GEOP_ANOM"},
{28,  "wave spectra(1)",     "non-dim", "WAVE_SP_1"},
{29,  "wave spectra(2)",     "non-dim", "WAVE_SP_2"},
{30,  "wave spectra(3)",     "non-dim", "WAVE_SP_3"},
{31,  "wind direction",  "degree true", "WIND_DIR"},
{32,  "wind speed",  "m/s", "WIND_SPEED"},
{33,  "u-component of wind",     "m s-1", "U"},
{34,  "v-component of wind",     "m s-1", "V"},
{35,  "stream function",     "(m**2)/s", "STREAM_FUN"},
{36,  "velocity potential",  "(m**2)/s", "VEL_POTENT"},
{37,  "Montgomery stream function",  "(m**2)/(s**2)", "M_STREAM_F"},
{38,  "sigma co-ordinate vertical velocity",     "1/s", "SIGMA_VERT"},
{39,  "omega",   "Pa s-1", "OMEGA"},
{40,  "vertical velocity",   "m s-1", "W"},
{41,  "absolute vorticity",  "1/s", "ABS_VORTIC"},
{42,  "absolute divergence",     "1/s", "ABS_DIVERG"},
{43,  "relative vorticity",  "1/s", "REL_VORTIC"},
{44,  "relative divergence",     "1/s", "REL_DIVERG"},
{45,  "vertical u-component shear",  "1/s", "VERT_U_SHR"},
{46,  "vertical v-component shear",  "1/s", "VERT_V_SHR"},
{47,  "direction of current",    "degree true", "DIR_OF_CUR"},
{48,  "speed of current",    "m/s", "SPD_OF_CUR"},
{49,  "u-component of current",  "m/s", "CURRCOMP_U"},
{50,  "v-component of current",  "m/s", "CURRCOMP_V"},
{51,  "specific humidity",   "kg kg-1", "QV"},
{52,  "relative humidity",   "%", "RELHUM"},
{53,  "humidity mixing ratio",   "kg/kg", "HUM_MIXRAT"},
{54,  "precipitable water",  "kg m-2", "TQV"},
{55,  "vapor pressure",  "Pa", "VAPOR_PRES"},
{56,  "saturation deficit",  "Pa", "SAT_DEFIC"},
{57,  "surface evaporation",     "kg m-2", "AEVAP_S"},
{58,  "cloud ice",   "kg m-2", "TQI"},
{59,  "precipitation rate",  "kg/(m**2)*s)", "PREC_RATE"},
{60,  "thunderstorm probability",    "%", "THUNDERST"},
{61,  "total precipitation amount",     "kg m-2", "TOT_PREC"},
{62,  "large scale precipitation",   "kg/(m**2)", "LS_PRECIP"},
{63,  "convective precipitation",    "kg/(m**2)", "CONV_PREC"},
{64,  "snowfall rate water equivalent",  "kg/((m**2)*s)", "SNOWF_RATE"},
{65,  "surface snow amount",  "m", "W_SNOW"},
{66,  "snow depth",  "m", "SNOW_DEPTH"},
{67,  "mixed layer depth",   "m", "MIX_LAY_DE"},
{68,  "transient thermocline depth",     "m", "TR_THERM_D"},
{69,  "main thermocline depth",  "m", "MA_THERM_D"},
{70,  "main thermocline depth anomaly",  "m", "M_THERM_DA"},
{71,  "total cloud cover",   "index", "CLOUD_COV"},
{72,  "convective cloud area fraction",  "index", "CLC_CON"},
{73,  "low cloud cover",     "index", "CLCL"},
{74,  "medium cloud cover",  "index", "CLCM"},
{75,  "high cloud cover",    "index", "CLCH"},
{76,  "vertical integrated cloud water",     "kg m-2", "TQC"},
{77,  "best lifted index (to 500 hPa)",  "K", "BLI_TO_500"},
{78,  "convective snowfall",     "kg m-2", "SNOW_CON"},
{79,  "large scale snowfall",    "kg m-2", "SNOW_GSP"},
{80,  "water temperature",   "K", "WATER_TEMP"},
{81,  "land-sea fraction",  "index", "FR_LAND"},
{82,  "deviation of sea-level from mean",    "m", "DEV_SEA_LE"},
{83,  "surface roughness length",   "m", "Z0"},
{84,  "surface albedo",  "index", "ALB_RAD"},
{85,  "soil surface temperature",    "K", "T_S"},
{86,  "water content of 1. soil layer",   "m", "W_G1"},
{87,  "vegetation area fraction",  "index", "PLCOV"},
{88,  "salinity",    "kg/kg", "SALINITY"},
{89,  "density",     "kg/(m**3)", "DENSITY"},
{90,  "surface runoff",   "kg m-2", "RUNOFF_S"},
{91,  "sea ice area fraction",     "index", "FR_ICE"},
{92,  "sea ice thickness",   "m", "H_ICE"},
{93,  "direction of ice drift",  "degree true", "DIR_ICE_DR"},
{94,  "speed of ice drift",  "m/s", "SP_ICE_DR"},
{95,  "u-component of ice drift",    "m/s", "ICE_DR_U"},
{96,  "v-component of ice drift",    "m/s", "ICE_DR_V"},
{97,  "ice growth rate",     "m/s", "ICE_GROWTH"},
{98,  "ice divergence",  "1/s", "ICE_DIVERG"},
{99,  "snow melt",   "kg/(m**2)", "SNOW_MELT"},
{100, "significant height of comb. wind waves and swell",    "m", "WINWAV_SWE"},
{101, "direction of wind waves",     "degree true", "DIR_OF_WAV"},
{102, "significant height of wind waves",    "m", "HEI_OF_WAV"},
{103, "mean period of wind waves",   "s", "MP_OF_WIWA"},
{104, "direction of swell",  "degree true", "DIR_OF_SWE"},
{105, "significant height of swell",     "m", "HEI_OF_SWE"},
{106, "mean period of swell",    "s", "MP_OF_SWEL"},
{107, "primary wave mean direction",     "degree true", "PR_WAVE_DI"},
{108, "primary wave mean period",    "s", "PR_WAVE_PE"},
{109, "secondary wave mean direction",   "degree true", "SE_WAVE_DI"},
{110, "secondary wave mean period",  "s", "SE_WAVE_PE"},
{111, "surface net downward shortwave radiation",     "W m-2", "SOBS_RAD"},
{112, "surface net downward longwave radiation",  "W m-2", "THBS_RAD"},
{113, "TOA net downward shortwave radiation",   "W m-2", "SOBT_RAD"},
{114, "TOA outgoing longwave radiation",    "W m-2", "THBT_RAD"},
{115, "long-wave radiation flux",    "W/(m**2)", "L_W_RAD"},
{116, "short-wave radiation flux",   "W/(m**2)", "S_W_RAD"},
{117, "global radiation flux",   "W/(m**2)", "GLOBAL_RAD"},
{118, "brightness temperature",  "K", "BRIGHTN_T"},
{119, "radiance (with respect to wave number)",  "(W/m)*(s/r)", "RADIANCE_N"},
{120, "radiance (with respect to wave length)",  "(W/(m**3))*(s/r)", "RADIANCE_L"},
{121, "averaged surface latent heat flux",    "W m-2", "ALHFL_S"},
{122, "averaged surface sensible heat flux",  "W m-2", "ASHFL_S"},
{123, "boundary layer dissipation",  "W/(m**2)", "BOUND_L_DI"},
{124, "averaged eastward stress",  "Pa", "AUMFL_S"},
{125, "averaged northward stress",  "Pa", "AVMFL_S"},
{126, "wind mixing energy",  "J", "WIND_MIX_E"},
{127, "image data",  "non-dim", "IMAGE_DATA"},
{129, "geopotential height (ECMF)",  "gpm", "GEOPOT_H"},
{130, "temperature (ECMF)",  "K", "TEMPERATUR"},
{131, "u-component of wind (ECMF)",  "m/s", "WIND_COMPU"},
{132, "v-component of wind (ECMF)",  "m/s", "WIND_COMPV"},
{139, "soil temperature (ECMF)",     "K", "SOIL_TEMP"},
{142, "large scale precipitation (ECMF)",    "kg/(m**2)", "LS_PRECIP"},
{143, "convective precipitation (ECMF)",     "kg/(m**2)", "CONV_PREC"},
{144, "snowfall (dimension: m of water equivalence)(ECMF)",  "m", "SNOWFALL"},
{151, "pressure reduced to MSL (ECMF)",  "Pa", "PRESSURE"},
{156, "geopotential height (ECMF)",  "gpm", "GEOPOT_H"},
{157, "relative humidity (ECMF)",    "%", "REL_HUMID"},
{164, "total cloud cover (ECMF)",    "1", "CLOUD_COV"},
{165, "u-component of 10m-wind (ECMF)",  "m/s", "10M_WIND_U"},
{166, "v-component of 10m-wind (ECMF)",  "m/s", "10M_WIND_V"},
{167, "2m temperature (ECMF)",   "K", "2M_TEMPER"},
{168, "2m due-point temperature (ECMF)",     "K", "2M_DUE_P"},
{228, "total precipitation (ECMF)",  "m", "TOTAL_PREC"},
{229, "seaway 01 (ECMF)",    "non-dim", "SEAWAY_01"},
{230, "seaway 02 (ECMF)",    "non-dim", "SEAWAY_02"},
{231, "seaway 03 (ECMF)",    "non-dim", "SEAWAY_03"},
{232, "seaway 04 (ECMF)",    "non-dim", "SEAWAY_04"},
{233, "seaway 05 (ECMF)",    "non-dim", "SEAWAY_05"},
{234, "seaway 06 (ECMF)",    "non-dim", "SEAWAY_06"},
{235, "seaway 07 (ECMF)",    "non-dim", "SEAWAY_07"},
{236, "seaway 08 (ECMF)",    "non-dim", "SEAWAY_08"},
{237, "seaway 09 (ECMF)",    "non-dim", "SEAWAY_09"},
{238, "seaway 10 (ECMF)",    "non-dim", "SEAWAY_10"},
{239, "seaway 11 (ECMF)",    "non-dim", "SEAWAY_11"},
};