/*
 * Center: 98
 * Subcenter: 
 * Parameter table version: 230
 */

TBLE2 ecmwf_230_params[] = {
{8, "Surface runoff", "m", "SROVAR"},
{9, "Sub-surface runoff", "m", "SSROVAR"},
{20, "Clear sky surface photosynthetically active radiation", "J m**-2", "PARCSVAR"},
{21, "Total sky direct solar radiation at surface", "J m**-2", "FDIRVAR"},
{22, "Clear-sky direct solar radiation at surface", "J m**-2", "CDIRVAR"},
{44, "Snow evaporation", "kg m**-2", "ESVAR"},
{45, "Snowmelt", "kg m**-2", "SMLTVAR"},
{46, "Solar duration", "s", "SDURVAR"},
{50, "Large-scale precipitation fraction", "s", "LSPFVAR"},
{57, "Downward UV radiation at the surface", "J m**-2", "UVBVAR"},
{58, "Photosynthetically active radiation at the surface", "J m**-2", "PARVAR"},
{80, "Accumulated Carbon Dioxide Net Ecosystem Exchange", "kg m**-2", "ACO2NEEVAR"},
{81, "Accumulated Carbon Dioxide Gross Primary Production", "kg m**-2", "ACO2GPPVAR"},
{82, "Accumulated Carbon Dioxide Ecosystem Respiration", "kg m**-2", "ACO2RECVAR"},
{129, "Surface solar radiation downward clear-sky", "J m**-2", "SSRDCVAR"},
{130, "Surface thermal radiation downward clear-sky", "J m**-2", "STRDCVAR"},
{142, "Stratiform precipitation", "m", "LSPVAR"},
{143, "Convective precipitation", "m", "CPVAR"},
{144, "Snowfall", "m of water equivalent", "SFVAR"},
{145, "Boundary layer dissipation", "J m**-2", "BLDVAR"},
{146, "Surface sensible heat flux", "J m**-2", "SSHFVAR"},
{147, "Surface latent heat flux", "J m**-2", "SLHFVAR"},
{169, "Surface solar radiation downwards", "J m**-2", "SSRDVAR"},
{174, "Albedo", "(0 - 1)", "ALVAR"},
{175, "Surface thermal radiation downwards", "J m**-2", "STRDVAR"},
{176, "Surface net solar radiation", "J m**-2", "SSRVAR"},
{177, "Surface net thermal radiation", "J m**-2", "STRVAR"},
{178, "Top net solar radiation", "J m**-2", "TSRVAR"},
{179, "Top net thermal radiation", "J m**-2", "TTRVAR"},
{180, "East-West surface stress", "N m**-2 s", "EWSSVAR"},
{181, "North-South surface stress", "N m**-2 s", "NSSSVAR"},
{182, "Evaporation", "kg m**-2", "EVAR"},
{189, "Sunshine duration", "s", "SUNDVAR"},
{195, "Longitudinal component of gravity wave stress", "N m**-2 s", "LGWSVAR"},
{196, "Meridional component of gravity wave stress", "N m**-2 s", "MGWSVAR"},
{197, "Gravity wave dissipation", "J m**-2", "GWDVAR"},
{198, "Skin reservoir content", "kg m**-2", "SRCVAR"},
{205, "Runoff", "m", "ROVAR"},
{208, "Top net solar radiation", "J m**-2", "TSRCVAR"},
{209, "Top net thermal radiation", "J m**-2", "TTRCVAR"},
{210, "Surface net solar radiation", "J m**-2", "SSRCVAR"},
{211, "Surface net thermal radiation", "J m**-2", "STRCVAR"},
{212, "TOA incident solar radiation", "J m**-2", "TISRVAR"},
{213, "Vertically integrated moisture divergence", "kg m**-2", "VIMDVAR"},
{228, "Total precipitation", "m", "TPVAR"},
{239, "Convective snowfall", "m of water equivalent", "CSFVAR"},
{240, "Large-scale snowfall", "m of water equivalent", "LSFVAR"},
{251, "Potential evaporation", "m", "PEVVAR"}
};
