TBLE2 ecmwf_170_params[] = {
{129, "Geopotential", "m**2 s**-2", "Z"},
{130, "Temperature", "K", "T"},
{131, "U-velocity", "m s**-1", "U"},
{132, "V-velocity", "m s**-1", "V"},
{138, "Vorticity (relative)", "s**-1", "VO"},
{140, "Soil wetness level 1", "m", "SWL1"},
{141, "Snow depth", "m (of water equivalent)", "SD"},
{149, "Total soil moisture", "m", "TSW"},
{151, "Mean sea level pressure", "Pa", "MSL"},
{155, "Divergence", "s**-1", "D"},
{171, "Soil wetness level", "2 m", "SWL2"},
{179, "Top thermal radiation", "W m-2", "TTR"},
{184, "Soil wetness level 3", "m", "SWL3"},
{201, "Max temp at 2m since previous postprocess", "K", "MX2T"},
{202, "Min temp at 2m since previous postprocess", "K", "MN2T"},
{228, "Total precipitation", "m", "TP"},
};
