/*
 * Center: 98
 * Subcenter: 
 * Parameter table version: 215
 */

TBLE2 ecmwf_215_params[] = {
{1, "Source/gain of sea salt aerosol (0.03 - 0.5 um)", "kg m**-2 s**-1", "AERSRCSSS"},
{2, "Source/gain of sea salt aerosol (0.5 - 5 um)", "kg m**-2 s**-1", "AERSRCSSM"},
{3, "Source/gain of sea salt aerosol (5 - 20 um)", "kg m**-2 s**-1", "AERSRCSSL"},
{4, "Dry deposition of sea salt aerosol (0.03 - 0.5 um)", "kg m**-2 s**-1", "AERDDPSSS"},
{5, "Dry deposition of sea salt aerosol (0.5 - 5 um)", "kg m**-2 s**-1", "AERDDPSSM"},
{6, "Dry deposition of sea salt aerosol (5 - 20 um)", "kg m**-2 s**-1", "AERDDPSSL"},
{7, "Sedimentation of sea salt aerosol (0.03 - 0.5 um)", "kg m**-2 s**-1", "AERSDMSSS"},
{8, "Sedimentation of sea salt aerosol (0.5 - 5 um)", "kg m**-2 s**-1", "AERSDMSSM"},
{9, "Sedimentation of sea salt aerosol (5 - 20 um)", "kg m**-2 s**-1", "AERSDMSSL"},
{10, "Wet deposition of sea salt aerosol (0.03 - 0.5 um) by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSSSS"},
{11, "Wet deposition of sea salt aerosol (0.5 - 5 um) by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSSSM"},
{12, "Wet deposition of sea salt aerosol (5 - 20 um) by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSSSL"},
{13, "Wet deposition of sea salt aerosol (0.03 - 0.5 um) by convective precipitation", "kg m**-2 s**-1", "AERWDCCSSS"},
{14, "Wet deposition of sea salt aerosol (0.5 - 5 um) by convective precipitation", "kg m**-2 s**-1", "AERWDCCSSM"},
{15, "Wet deposition of sea salt aerosol (5 - 20 um) by convective precipitation", "kg m**-2 s**-1", "AERWDCCSSL"},
{16, "Negative fixer of sea salt aerosol (0.03 - 0.5 um)", "kg m**-2 s**-1", "AERNGTSSS"},
{17, "Negative fixer of sea salt aerosol (0.5 - 5 um)", "kg m**-2 s**-1", "AERNGTSSM"},
{18, "Negative fixer of sea salt aerosol (5 - 20 um)", "kg m**-2 s**-1", "AERNGTSSL"},
{19, "Vertically integrated mass of sea salt aerosol (0.03 - 0.5 um)", "kg m**-2", "AERMSSSSS"},
{20, "Vertically integrated mass of sea salt aerosol (0.5 - 5 um)", "kg m**-2", "AERMSSSSM"},
{21, "Vertically integrated mass of sea salt aerosol (5 - 20 um)", "kg m**-2", "AERMSSSSL"},
{22, "Sea salt aerosol (0.03 - 0.5 um) optical depth", "-", "AERODSSS"},
{23, "Sea salt aerosol (0.5 - 5 um) optical depth", "-", "AERODSSM"},
{24, "Sea salt aerosol (5 - 20 um) optical depth", "-", "AERODSSL"},
{25, "Source/gain of dust aerosol (0.03 - 0.55 um)", "kg m**-2 s**-1", "AERSRCDUS"},
{26, "Source/gain of dust aerosol (0.55 - 9 um)", "kg m**-2 s**-1", "AERSRCDUM"},
{27, "Source/gain of dust aerosol (9 - 20 um)", "kg m**-2 s**-1", "AERSRCDUL"},
{28, "Dry deposition of dust aerosol (0.03 - 0.55 um)", "kg m**-2 s**-1", "AERDDPDUS"},
{29, "Dry deposition of dust aerosol (0.55 - 9 um)", "kg m**-2 s**-1", "AERDDPDUM"},
{30, "Dry deposition of dust aerosol (9 - 20 um)", "kg m**-2 s**-1", "AERDDPDUL"},
{31, "Sedimentation of dust aerosol (0.03 - 0.55 um)", "kg m**-2 s**-1", "AERSDMDUS"},
{32, "Sedimentation of dust aerosol (0.55 - 9 um)", "kg m**-2 s**-1", "AERSDMDUM"},
{33, "Sedimentation of dust aerosol (9 - 20 um)", "kg m**-2 s**-1", "AERSDMDUL"},
{34, "Wet deposition of dust aerosol (0.03 - 0.55 um) by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSDUS"},
{35, "Wet deposition of dust aerosol (0.55 - 9 um) by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSDUM"},
{36, "Wet deposition of dust aerosol (9 - 20 um) by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSDUL"},
{37, "Wet deposition of dust aerosol (0.03 - 0.55 um) by convective precipitation", "kg m**-2 s**-1", "AERWDCCDUS"},
{38, "Wet deposition of dust aerosol (0.55 - 9 um) by convective precipitation", "kg m**-2 s**-1", "AERWDCCDUM"},
{39, "Wet deposition of dust aerosol (9 - 20 um) by convective precipitation", "kg m**-2 s**-1", "AERWDCCDUL"},
{40, "Negative fixer of dust aerosol (0.03 - 0.55 um)", "kg m**-2 s**-1", "AERNGTDUS"},
{41, "Negative fixer of dust aerosol (0.55 - 9 um)", "kg m**-2 s**-1", "AERNGTDUM"},
{42, "Negative fixer of dust aerosol (9 - 20 um)", "kg m**-2 s**-1", "AERNGTDUL"},
{43, "Vertically integrated mass of dust aerosol (0.03 - 0.55 um)", "kg m**-2", "AERMSSDUS"},
{44, "Vertically integrated mass of dust aerosol (0.55 - 9 um)", "kg m**-2", "AERMSSDUM"},
{45, "Vertically integrated mass of dust aerosol (9 - 20 um)", "kg m**-2", "AERMSSDUL"},
{46, "Dust aerosol (0.03 - 0.55 um) optical depth", "-", "AERODDUS"},
{47, "Dust aerosol (0.55 - 9 um) optical depth", "-", "AERODDUM"},
{48, "Dust aerosol (9 - 20 um) optical depth", "-", "AERODDUL"},
{49, "Source/gain of hydrophobic organic matter aerosol", "kg m**-2 s**-1", "AERSRCOMHPHOB"},
{50, "Source/gain of hydrophilic organic matter aerosol", "kg m**-2 s**-1", "AERSRCOMHPHIL"},
{51, "Dry deposition of hydrophobic organic matter aerosol", "kg m**-2 s**-1", "AERDDPOMHPHOB"},
{52, "Dry deposition of hydrophilic organic matter aerosol", "kg m**-2 s**-1", "AERDDPOMHPHIL"},
{53, "Sedimentation of hydrophobic organic matter aerosol", "kg m**-2 s**-1", "AERSDMOMHPHOB"},
{54, "Sedimentation of hydrophilic organic matter aerosol", "kg m**-2 s**-1", "AERSDMOMHPHIL"},
{55, "Wet deposition of hydrophobic organic matter aerosol by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSOMHPHOB"},
{56, "Wet deposition of hydrophilic organic matter aerosol by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSOMHPHIL"},
{57, "Wet deposition of hydrophobic organic matter aerosol by convective precipitation", "kg m**-2 s**-1", "AERWDCCOMHPHOB"},
{58, "Wet deposition of hydrophilic organic matter aerosol by convective precipitation", "kg m**-2 s**-1", "AERWDCCOMHPHIL"},
{59, "Negative fixer of hydrophobic organic matter aerosol", "kg m**-2 s**-1", "AERNGTOMHPHOB"},
{60, "Negative fixer of hydrophilic organic matter aerosol", "kg m**-2 s**-1", "AERNGTOMHPHIL"},
{61, "Vertically integrated mass of hydrophobic organic matter aerosol", "kg m**-2", "AERMSSOMHPHOB"},
{62, "Vertically integrated mass of hydrophilic organic matter aerosol", "kg m**-2", "AERMSSOMHPHIL"},
{63, "Hydrophobic organic matter aerosol optical depth", "-", "AERODOMHPHOB"},
{64, "Hydrophilic organic matter aerosol optical depth", "-", "AERODOMHPHIL"},
{65, "Source/gain of hydrophobic black carbon aerosol", "kg m**-2 s**-1", "AERSRCBCHPHOB"},
{66, "Source/gain of hydrophilic black carbon aerosol", "kg m**-2 s**-1", "AERSRCBCHPHIL"},
{67, "Dry deposition of hydrophobic black carbon aerosol", "kg m**-2 s**-1", "AERDDPBCHPHOB"},
{68, "Dry deposition of hydrophilic black carbon aerosol", "kg m**-2 s**-1", "AERDDPBCHPHIL"},
{69, "Sedimentation of hydrophobic black carbon aerosol", "kg m**-2 s**-1", "AERSDMBCHPHOB"},
{70, "Sedimentation of hydrophilic black carbon aerosol", "kg m**-2 s**-1", "AERSDMBCHPHIL"},
{71, "Wet deposition of hydrophobic black carbon aerosol by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSBCHPHOB"},
{72, "Wet deposition of hydrophilic black carbon aerosol by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSBCHPHIL"},
{73, "Wet deposition of hydrophobic black carbon aerosol by convective precipitation", "kg m**-2 s**-1", "AERWDCCBCHPHOB"},
{74, "Wet deposition of hydrophilic black carbon aerosol by convective precipitation", "kg m**-2 s**-1", "AERWDCCBCHPHIL"},
{75, "Negative fixer of hydrophobic black carbon aerosol", "kg m**-2 s**-1", "AERNGTBCHPHOB"},
{76, "Negative fixer of hydrophilic black carbon aerosol", "kg m**-2 s**-1", "AERNGTBCHPHIL"},
{77, "Vertically integrated mass of hydrophobic black carbon aerosol", "kg m**-2", "AERMSSBCHPHOB"},
{78, "Vertically integrated mass of hydrophilic black carbon aerosol", "kg m**-2", "AERMSSBCHPHIL"},
{79, "Hydrophobic black carbon aerosol optical depth", "-", "AERODBCHPHOB"},
{80, "Hydrophilic black carbon aerosol optical depth", "-", "AERODBCHPHIL"},
{81, "Source/gain of sulphate aerosol", "kg m**-2 s**-1", "AERSRCSU"},
{82, "Dry deposition of sulphate aerosol", "kg m**-2 s**-1", "AERDDPSU"},
{83, "Sedimentation of sulphate aerosol", "kg m**-2 s**-1", "AERSDMSU"},
{84, "Wet deposition of sulphate aerosol by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSSU"},
{85, "Wet deposition of sulphate aerosol by convective precipitation", "kg m**-2 s**-1", "AERWDCCSU"},
{86, "Negative fixer of sulphate aerosol", "kg m**-2 s**-1", "AERNGTSU"},
{87, "Vertically integrated mass of sulphate aerosol", "kg m**-2", "AERMSSSU"},
{88, "Sulphate aerosol optical depth", "-", "AERODSU"},
{89, "Accumulated total aerosol optical depth at 550 nm", "s", "ACCAOD550"},
{90, "Effective (snow effect included) UV visible albedo for direct radiation", "(0 - 1)", "ALUVPSN"},
{91, "10 metre wind speed dust emission potential", "kg s**2 m**-5", "AERDEP10SI"},
{92, "10 metre wind gustiness dust emission potential", "kg s**2 m**-5", "AERDEP10FG"},
{93, "Profile of total aerosol optical depth at 532 nm", "-", "PAOD532"},
{94, "Profile of natural (sea-salt and dust) aerosol optical depth at 532 nm", "-", "PNAOD532"},
{95, "Profile of antropogenic (black carbon, organic matter, sulphate) aerosol optical depth at 532 nm", "-", "PAAOD532"},
{96, "Total absorption aerosol optical depth at 340 nm", "-", "AODABS340"},
{97, "Total absorption aerosol optical depth at 355 nm", "-", "AODABS355"},
{98, "Total absorption aerosol optical depth at 380 nm", "-", "AODABS380"},
{99, "Total absorption aerosol optical depth at 400 nm", "-", "AODABS400"},
{100, "Total absorption aerosol optical depth at 440 nm", "-", "AODABS440"},
{101, "Total absorption aerosol optical depth at 469 nm", "-", "AODABS469"},
{102, "Total absorption aerosol optical depth at 500 nm", "-", "AODABS500"},
{103, "Total absorption aerosol optical depth at 532 nm", "-", "AODABS532"},
{104, "Total absorption aerosol optical depth at 550 nm", "-", "AODABS550"},
{105, "Total absorption aerosol optical depth at 645 nm", "-", "AODABS645"},
{106, "Total absorption aerosol optical depth at 670 nm", "-", "AODABS670"},
{107, "Total absorption aerosol optical depth at 800 nm", "-", "AODABS800"},
{108, "Total absorption aerosol optical depth at 858 nm", "-", "AODABS858"},
{109, "Total absorption aerosol optical depth at 865 nm", "-", "AODABS865"},
{110, "Total absorption aerosol optical depth at 1020 nm", "-", "AODABS1020"},
{111, "Total absorption aerosol optical depth at 1064 nm", "-", "AODABS1064"},
{112, "Total absorption aerosol optical depth at 1240 nm", "-", "AODABS1240"},
{113, "Total absorption aerosol optical depth at 1640 nm", "-", "AODABS1640"},
{114, "Total fine mode (r < 0.5 um) aerosol optical depth at 340 nm", "-", "AODFM340"},
{115, "Total fine mode (r < 0.5 um) aerosol optical depth at 355 nm", "-", "AODFM355"},
{116, "Total fine mode (r < 0.5 um) aerosol optical depth at 380 nm", "-", "AODFM380"},
{117, "Total fine mode (r < 0.5 um) aerosol optical depth at 400 nm", "-", "AODFM400"},
{118, "Total fine mode (r < 0.5 um) aerosol optical depth at 440 nm", "-", "AODFM440"},
{119, "Total fine mode (r < 0.5 um) aerosol optical depth at 469 nm", "-", "AODFM469"},
{120, "Total fine mode (r < 0.5 um) aerosol optical depth at 500 nm", "-", "AODFM500"},
{121, "Total fine mode (r < 0.5 um) aerosol optical depth at 532 nm", "-", "AODFM532"},
{122, "Total fine mode (r < 0.5 um) aerosol optical depth at 550 nm", "-", "AODFM550"},
{123, "Total fine mode (r < 0.5 um) aerosol optical depth at 645 nm", "-", "AODFM645"},
{124, "Total fine mode (r < 0.5 um) aerosol optical depth at 670 nm", "-", "AODFM670"},
{125, "Total fine mode (r < 0.5 um) aerosol optical depth at 800 nm", "-", "AODFM800"},
{126, "Total fine mode (r < 0.5 um) aerosol optical depth at 858 nm", "-", "AODFM858"},
{127, "Total fine mode (r < 0.5 um) aerosol optical depth at 865 nm", "-", "AODFM865"},
{128, "Total fine mode (r < 0.5 um) aerosol optical depth at 1020 nm", "-", "AODFM1020"},
{129, "Total fine mode (r < 0.5 um) aerosol optical depth at 1064 nm", "-", "AODFM1064"},
{130, "Total fine mode (r < 0.5 um) aerosol optical depth at 1240 nm", "-", "AODFM1240"},
{131, "Total fine mode (r < 0.5 um) aerosol optical depth at 1640 nm", "-", "AODFM1640"},
{132, "Single scattering albedo at 340 nm", "(0 - 1)", "SSA340"},
{133, "Single scattering albedo at 355 nm", "(0 - 1)", "SSA355"},
{134, "Single scattering albedo at 380 nm", "(0 - 1)", "SSA380"},
{135, "Single scattering albedo at 400 nm", "(0 - 1)", "SSA400"},
{136, "Single scattering albedo at 440 nm", "(0 - 1)", "SSA440"},
{137, "Single scattering albedo at 469 nm", "(0 - 1)", "SSA469"},
{138, "Single scattering albedo at 500 nm", "(0 - 1)", "SSA500"},
{139, "Single scattering albedo at 532 nm", "(0 - 1)", "SSA532"},
{140, "Single scattering albedo at 550 nm", "(0 - 1)", "SSA550"},
{141, "Single scattering albedo at 645 nm", "(0 - 1)", "SSA645"},
{142, "Single scattering albedo at 670 nm", "(0 - 1)", "SSA670"},
{143, "Single scattering albedo at 800 nm", "(0 - 1)", "SSA800"},
{144, "Single scattering albedo at 858 nm", "(0 - 1)", "SSA858"},
{145, "Single scattering albedo at 865 nm", "(0 - 1)", "SSA865"},
{146, "Single scattering albedo at 1020 nm", "(0 - 1)", "SSA1020"},
{147, "Single scattering albedo at 1064 nm", "(0 - 1)", "SSA1064"},
{148, "Single scattering albedo at 1240 nm", "(0 - 1)", "SSA1240"},
{149, "Single scattering albedo at 1640 nm", "(0 - 1)", "SSA1640"},
{150, "Assimetry factor at 340 nm", "-", "ASSIMETRY340"},
{151, "Assimetry factor at 355 nm", "-", "ASSIMETRY355"},
{152, "Assimetry factor at 380 nm", "-", "ASSIMETRY380"},
{153, "Assimetry factor at 400 nm", "-", "ASSIMETRY400"},
{154, "Assimetry factor at 440 nm", "-", "ASSIMETRY440"},
{155, "Assimetry factor at 469 nm", "-", "ASSIMETRY469"},
{156, "Assimetry factor at 500 nm", "-", "ASSIMETRY500"},
{157, "Assimetry factor at 532 nm", "-", "ASSIMETRY532"},
{158, "Assimetry factor at 550 nm", "-", "ASSIMETRY550"},
{159, "Assimetry factor at 645 nm", "-", "ASSIMETRY645"},
{160, "Assimetry factor at 670 nm", "-", "ASSIMETRY670"},
{161, "Assimetry factor at 800 nm", "-", "ASSIMETRY800"},
{162, "Assimetry factor at 858 nm", "-", "ASSIMETRY858"},
{163, "Assimetry factor at 865 nm", "-", "ASSIMETRY865"},
{164, "Assimetry factor at 1020 nm", "-", "ASSIMETRY1020"},
{165, "Assimetry factor at 1064 nm", "-", "ASSIMETRY1064"},
{166, "Assimetry factor at 1240 nm", "-", "ASSIMETRY1240"},
{167, "Assimetry factor at 1640 nm", "-", "ASSIMETRY1640"},
{168, "Source/gain of sulphur dioxide", "kg m**-2 s**-1", "AERSRCSO2"},
{169, "Dry deposition of sulphur dioxide", "kg m**-2 s**-1", "AERDDPSO2"},
{170, "Sedimentation of sulphur dioxide", "kg m**-2 s**-1", "AERSDMSO2"},
{171, "Wet deposition of sulphur dioxide by large-scale precipitation", "kg m**-2 s**-1", "AERWDLSSO2"},
{172, "Wet deposition of sulphur dioxide by convective precipitation", "kg m**-2 s**-1", "AERWDCCSO2"},
{173, "Negative fixer of sulphur dioxide", "kg m**-2 s**-1", "AERNGTSO2"},
{174, "Vertically integrated mass of sulphur dioxide", "kg m**-2", "AERMSSSO2"},
{175, "Sulphur dioxide optical depth", "-", "AERODSO2"},
{176, "Total absorption aerosol optical depth at 2130 nm", "-", "AODABS2130"},
{177, "Total fine mode (r < 0.5 um) aerosol optical depth at 2130 nm", "-", "AODFM2130"},
{178, "Single scattering albedo at 2130 nm", "(0 - 1)", "SSA2130"},
{179, "Assimetry factor at 2130 nm", "-", "ASSIMETRY2130"}
};
