/*
 * Center: 98
 * Subcenter: 
 * Parameter table version: 218
 */

TBLE2 ecmwf_218_params[] = {
{3, "Total column hydrogen peroxide", "kg m**-2", "TC_H2O2"},
{4, "Total column methane", "kg m**-2", "TC_CH4"},
{6, "Total column nitric acid", "kg m**-2", "TC_HNO3"},
{7, "Total column methyl peroxide", "kg m**-2", "TC_CH3OOH"},
{9, "Total column paraffins", "kg m**-2", "TC_PAR"},
{10, "Total column ethene", "kg m**-2", "TC_C2H4"},
{11, "Total column olefins", "kg m**-2", "TC_OLE"},
{12, "Total column aldehydes", "kg m**-2", "TC_ALD2"},
{13, "Total column  peroxyacetyl nitrate", "kg m**-2", "TC_PAN"},
{14, "Total column peroxides", "kg m**-2", "TC_ROOH"},
{15, "Total column organic nitrates", "kg m**-2", "TC_ONIT"},
{16, "Total column  isoprene", "kg m**-2", "TC_C5H8"},
{18, "Total column dimethyl sulfide", "kg m**-2", "TC_DMS"},
{19, "Total column ammonia", "kg m**-2", "TC_NH3"},
{20, "Total column  sulfate", "kg m**-2", "TC_SO4"},
{21, "Total column ammonium", "kg m**-2", "TC_NH4"},
{22, "Total column  methane sulfonic acid", "kg m**-2", "TC_MSA"},
{23, "Total column methyl glyoxal", "kg m**-2", "TC_CH3COCHO"},
{24, "Total column stratospheric ozone", "kg m**-2", "TC_O3S"},
{26, "Total column  lead", "kg m**-2", "TC_PB"},
{27, "Total column nitrogen monoxide", "kg m**-2", "TC_NO"},
{28, "Total column hydroperoxy radical", "kg m**-2", "TC_HO2"},
{29, "Total column methylperoxy radical", "kg m**-2", "TC_CH3O2"},
{30, "Total column hydroxyl radical", "kg m**-2", "TC_OH"},
{32, "Total column nitrate radical", "kg m**-2", "TC_NO3"},
{33, "Total column dinitrogen pentoxide", "kg m**-2", "TC_N2O5"},
{34, "Total column pernitric acid", "kg m**-2", "TC_HO2NO2"},
{35, "Total column peroxy acetyl radical", "kg m**-2", "TC_C2O3"},
{36, "Total column  organic ethers", "kg m**-2", "TC_ROR"},
{37, "Total column PAR budget corrector", "kg m**-2", "TC_RXPAR"},
{38, "Total column NO to NO2 operator", "kg m**-2", "TC_XO2"},
{39, "Total column NO to alkyl nitrate operator", "kg m**-2", "TC_XO2N"},
{40, "Total column amine", "kg m**-2", "TC_NH2"},
{41, "Total column  polar stratospheric cloud", "kg m**-2", "TC_PSC"},
{42, "Total column methanol", "kg m**-2", "TC_CH3OH"},
{43, "Total column formic acid", "kg m**-2", "TC_HCOOH"},
{44, "Total column  methacrylic acid", "kg m**-2", "TC_MCOOH"},
{45, "Total column  ethane", "kg m**-2", "TC_C2H6"},
{46, "Total column ethanol", "kg m**-2", "TC_C2H5OH"},
{47, "Total column propane", "kg m**-2", "TC_C3H8"},
{48, "Total column propene", "kg m**-2", "TC_C3H6"},
{49, "Total column terpenes", "kg m**-2", "TC_C10H16"},
{50, "Total column methacrolein MVK", "kg m**-2", "TC_ISPD"},
{51, "Total column nitrate", "kg m**-2", "TC_NO3_A"},
{52, "Total column acetone", "kg m**-2", "TC_CH3COCH3"},
{53, "Total column acetone product", "kg m**-2", "TC_ACO2"},
{54, "Total column IC3H7O2", "kg m**-2", "TC_IC3H7O2"},
{55, "Total column HYPROPO2", "kg m**-2", "TC_HYPROPO2"},
{56, "Total column nitrogen oxides Transp", "kg m**-2", "TC_NOXA"}
};
