/*
 * Center: 98
 * Subcenter: 
 * Parameter table version: 219
 */

TBLE2 ecmwf_219_params[] = {
{1, "Ozone emissions", "kg m**-2", "E_GO3"},
{2, "Nitrogen oxides emissions", "kg m**-2", "E_NOX"},
{3, "Hydrogen peroxide emissions", "kg m**-2", "E_H2O2"},
{4, "Methane emissions", "kg m**-2", "E_CH4"},
{5, "Carbon monoxide emissions", "kg m**-2", "E_CO"},
{6, "Nitric acid emissions", "kg m**-2", "E_HNO3"},
{7, "Methyl peroxide emissions", "kg m**-2", "E_CH3OOH"},
{8, "Formaldehyde emissions", "kg m**-2", "E_HCHO"},
{9, "Paraffins emissions", "kg m**-2", "E_PAR"},
{10, "Ethene emissions", "kg m**-2", "E_C2H4"},
{11, "Olefins emissions", "kg m**-2", "E_OLE"},
{12, "Aldehydes emissions", "kg m**-2", "E_ALD2"},
{13, "Peroxyacetyl nitrate emissions", "kg m**-2", "E_PAN"},
{14, "Peroxides emissions", "kg m**-2", "E_ROOH"},
{15, "Organic nitrates emissions", "kg m**-2", "E_ONIT"},
{16, "Isoprene emissions", "kg m**-2", "E_C5H8"},
{17, "Sulfur dioxide emissions", "kg m**-2", "E_SO2"},
{18, "Dimethyl sulfide emissions", "kg m**-2", "E_DMS"},
{19, "Ammonia emissions", "kg m**-2", "E_NH3"},
{20, "Sulfate emissions", "kg m**-2", "E_SO4"},
{21, "Ammonium emissions", "kg m**-2", "E_NH4"},
{22, "Methane sulfonic acid emissions", "kg m**-2", "E_MSA"},
{23, "Methyl glyoxal emissions", "kg m**-2", "E_CH3COCHO"},
{24, "Stratospheric ozone emissions", "kg m**-2", "E_O3S"},
{25, "Radon emissions", "kg m**-2", "E_RA"},
{26, "Lead emissions", "kg m**-2", "E_PB"},
{27, "Nitrogen monoxide emissions", "kg m**-2", "E_NO"},
{28, "Hydroperoxy radical emissions", "kg m**-2", "E_HO2"},
{29, "Methylperoxy radical emissions", "kg m**-2", "E_CH3O2"},
{30, "Hydroxyl radical emissions", "kg m**-2", "E_OH"},
{31, "Nitrogen dioxide emissions", "kg m**-2", "E_NO2"},
{32, "Nitrate radical emissions", "kg m**-2", "E_NO3"},
{33, "Dinitrogen pentoxide emissions", "kg m**-2", "E_N2O5"},
{34, "Pernitric acid emissions", "kg m**-2", "E_HO2NO2"},
{35, "Peroxy acetyl radical emissions", "kg m**-2", "E_C2O3"},
{36, "Organic ethers emissions", "kg m**-2", "E_ROR"},
{37, "PAR budget corrector emissions", "kg m**-2", "E_RXPAR"},
{38, "NO to NO2 operator emissions", "kg m**-2", "E_XO2"},
{39, "NO to alkyl nitrate operator emissions", "kg m**-2", "E_XO2N"},
{40, "Amine emissions", "kg m**-2", "E_NH2"},
{41, "Polar stratospheric cloud emissions", "kg m**-2", "E_PSC"},
{42, "Methanol emissions", "kg m**-2", "E_CH3OH"},
{43, "Formic acid emissions", "kg m**-2", "E_HCOOH"},
{44, "Methacrylic acid emissions", "kg m**-2", "E_MCOOH"},
{45, "Ethane emissions", "kg m**-2", "E_C2H6"},
{46, "Ethanol emissions", "kg m**-2", "E_C2H5OH"},
{47, "Propane emissions", "kg m**-2", "E_C3H8"},
{48, "Propene emissions", "kg m**-2", "E_C3H6"},
{49, "Terpenes emissions", "kg m**-2", "E_C10H16"},
{50, "Methacrolein MVK  emissions", "kg m**-2", "E_ISPD"},
{51, "Nitrate emissions", "kg m**-2", "E_NO3_A"},
{52, "Acetone emissions", "kg m**-2", "E_CH3COCH3"},
{53, "Acetone product emissions", "kg m**-2", "E_ACO2"},
{54, "IC3H7O2 emissions", "kg m**-2", "E_IC3H7O2"},
{55, "HYPROPO2 emissions", "kg m**-2", "E_HYPROPO2"},
{56, "Nitrogen oxides Transp emissions", "kg m**-2", "E_NOXA"}
};
