/*
 * Center: 
 * Subcenter: 
 * Parameter table version: 
 */

TBLE2 ecmwf_217_params[] = {
{3, "Hydrogen peroxide", "kg kg**-1", "H2O2"},
{4, "Methane", "kg kg**-1", "CH4"},
{6, "Nitric acid", "kg kg**-1", "HNO3"},
{7, "Methyl peroxide", "kg kg**-1", "CH3OOH"},
{9, "Paraffins", "kg kg**-1", "PAR"},
{10, "Ethene", "kg kg**-1", "C2H4"},
{11, "Olefins", "kg kg**-1", "OLE"},
{12, "Aldehydes", "kg kg**-1", "ALD2"},
{13, "Peroxyacetyl nitrate", "kg kg**-1", "PAN"},
{14, "Peroxides", "kg kg**-1", "ROOH"},
{15, "Organic nitrates", "kg kg**-1", "ONIT"},
{16, "Isoprene", "kg kg**-1", "C5H8"},
{18, "Dimethyl sulfide", "kg kg**-1", "DMS"},
{19, "Ammonia", "kg kg**-1", "NH3"},
{20, "Sulfate", "kg kg**-1", "SO4"},
{21, "Ammonium", "kg kg**-1", "NH4"},
{22, "Methane sulfonic acid", "kg kg**-1", "MSA"},
{23, "Methyl glyoxal", "kg kg**-1", "CH3COCHO"},
{24, "Stratospheric ozone", "kg kg**-1", "O3S"},
{26, "Lead", "kg kg**-1", "PB"},
{27, "Nitrogen monoxide", "kg kg**-1", "NO"},
{28, "Hydroperoxy radical", "kg kg**-1", "HO2"},
{29, "Methylperoxy radical", "kg kg**-1", "CH3O2"},
{30, "Hydroxyl radical", "kg kg**-1", "OH"},
{32, "Nitrate radical", "kg kg**-1", "NO3"},
{33, "Dinitrogen pentoxide", "kg kg**-1", "N2O5"},
{34, "Pernitric acid", "kg kg**-1", "HO2NO2"},
{35, "Peroxy acetyl radical", "kg kg**-1", "C2O3"},
{36, "Organic ethers", "kg kg**-1", "ROR"},
{37, "PAR budget corrector", "kg kg**-1", "RXPAR"},
{38, "NO to NO2 operator", "kg kg**-1", "XO2"},
{39, "NO to alkyl nitrate operator", "kg kg**-1", "XO2N"},
{40, "Amine", "kg kg**-1", "NH2"},
{41, "Polar stratospheric cloud", "kg kg**-1", "PSC"},
{42, "Methanol", "kg kg**-1", "CH3OH"},
{43, "Formic acid", "kg kg**-1", "HCOOH"},
{44, "Methacrylic acid", "kg kg**-1", "MCOOH"},
{45, "Ethane", "kg kg**-1", "C2H6"},
{46, "Ethanol", "kg kg**-1", "C2H5OH"},
{47, "Propane", "kg kg**-1", "C3H8"},
{48, "Propene", "kg kg**-1", "C3H6"},
{49, "Terpenes", "kg kg**-1", "C10H16"},
{50, "Methacrolein MVK", "kg kg**-1", "ISPD"},
{51, "Nitrate", "kg kg**-1", "NO3_A"},
{52, "Acetone", "kg kg**-1", "CH3COCH3"},
{53, "Acetone product", "kg kg**-1", "ACO2"},
{54, "IC3H7O2", "kg kg**-1", "IC3H7O2"},
{55, "HYPROPO2", "kg kg**-1", "HYPROPO2"},
{56, "Nitrogen oxides Transp", "kg kg**-1", "NOXA"}
};
