/*
 * Center: 98 
 * Subcenter: 
 * Parameter table version: 211
 */

TBLE2 ecmwf_211_params[] = {
{1, "Sea Salt Aerosol (0.03 - 0.5 um) Mixing Ratio", "kg kg**-1", "AERMR01DIFF"},
{2, "Sea Salt Aerosol (0.5 - 5 um) Mixing Ratio", "kg kg**-1", "AERMR02DIFF"},
{3, "Sea Salt Aerosol (5 - 20 um) Mixing Ratio", "kg kg**-1", "AERMR03DIFF"},
{4, "Dust Aerosol (0.03 - 0.55 um) Mixing Ratio", "kg kg**-1", "AERMR04DIFF"},
{5, "Dust Aerosol (0.55 - 0.9 um) Mixing Ratio", "kg kg**-1", "AERMR05DIFF"},
{6, "Dust Aerosol (0.9 - 20 um) Mixing Ratio", "kg kg**-1", "AERMR06DIFF"},
{7, "Hydrophobic Organic Matter Aerosol Mixing Ratio", "kg kg**-1", "AERMR07DIFF"},
{8, "Hydrophilic Organic Matter Aerosol Mixing Ratio", "kg kg**-1", "AERMR08DIFF"},
{9, "Hydrophobic Black Carbon Aerosol Mixing Ratio", "kg kg**-1", "AERMR09DIFF"},
{10, "Hydrophilic Black Carbon Aerosol Mixing Ratio", "kg kg**-1", "AERMR10DIFF"},
{11, "Sulphate Aerosol Mixing Ratio", "kg kg**-1", "AERMR11DIFF"},
{12, "Aerosol type 12 mixing ratio", "kg kg**-1", "AERMR12DIFF"},
{13, "Aerosol type 13 mass mixing ratio", "kg kg**-1", "AERMR13DIFF"},
{14, "Aerosol type 14 mass mixing ratio", "kg kg**-1", "AERMR14DIFF"},
{15, "Aerosol type 15 mass mixing ratio", "kg kg**-1", "AERMR15DIFF"},
{16, "Aerosol type 1 source", "kg m**-2", "AERGN01DIFF"},
{17, "Aerosol type 2 source", "kg m**-2", "AERGN02DIFF"},
{18, "Aerosol type 3 source", "kg m**-2", "AERGN03DIFF"},
{19, "Aerosol type 4 source", "kg m**-2", "AERGN04DIFF"},
{20, "Aerosol type 5 source", "kg m**-2", "AERGN05DIFF"},
{21, "Aerosol type 6 source", "kg m**-2", "AERGN06DIFF"},
{22, "Aerosol type 7 source", "kg m**-2", "AERGN07DIFF"},
{23, "Aerosol type 8 source", "kg m**-2", "AERGN08DIFF"},
{24, "Aerosol type 9 source", "kg m**-2", "AERGN09DIFF"},
{25, "Aerosol type 10 source", "kg m**-2", "AERGN10DIFF"},
{26, "Aerosol type 11 source", "kg m**-2", "AERGN11DIFF"},
{27, "Aerosol type 12 source", "kg m**-2", "AERGN12DIFF"},
{28, "SO4 aerosol precursor mass mixing ratio", "kg kg**-1", "AERPR03DIFF"},
{29, "Water vapour mixing ratio for hydrophilic aerosols in mode 1", "kg kg**-1", "AERWV01DIFF"},
{30, "Water vapour mixing ratio for hydrophilic aerosols in mode 2", "kg kg**-1", "AERWV02DIFF"},
{31, "Aerosol type 1 sink", "kg m**-2", "AERLS01DIFF"},
{32, "Aerosol type 2 sink", "kg m**-2", "AERLS02DIFF"},
{33, "Aerosol type 3 sink", "kg m**-2", "AERLS03DIFF"},
{34, "Aerosol type 4 sink", "kg m**-2", "AERLS04DIFF"},
{35, "Aerosol type 5 sink", "kg m**-2", "AERLS05DIFF"},
{36, "Aerosol type 6 sink", "kg m**-2", "AERLS06DIFF"},
{37, "Aerosol type 7 sink", "kg m**-2", "AERLS07DIFF"},
{38, "Aerosol type 8 sink", "kg m**-2", "AERLS08DIFF"},
{39, "Aerosol type 9 sink", "kg m**-2", "AERLS09DIFF"},
{40, "Aerosol type 10 sink", "kg m**-2", "AERLS10DIFF"},
{41, "Aerosol type 11 sink", "kg m**-2", "AERLS11DIFF"},
{42, "Aerosol type 12 sink", "kg m**-2", "AERLS12DIFF"},
{43, "DMS surface emission", "kg m**-2 s**-1", "EMDMSDIFF"},
{44, "Water vapour mixing ratio for hydrophilic aerosols in mode 3", "kg kg**-1", "AERWV03DIFF"},
{45, "Water vapour mixing ratio for hydrophilic aerosols in mode 4", "kg kg**-1", "AERWV04DIFF"},
{46, "Aerosol precursor mixing ratio", "kg kg**-1", "AERPRDIFF"},
{47, "Aerosol small mode mixing ratio", "kg kg**-1", "AERSMDIFF"},
{48, "Aerosol large mode mixing ratio", "kg kg**-1", "AERLGDIFF"},
{49, "Aerosol precursor optical depth", "dimensionless", "AODPRDIFF"},
{50, "Aerosol small mode optical depth", "dimensionless", "AODSMDIFF"},
{51, "Aerosol large mode optical depth", "dimensionless", "AODLGDIFF"},
{52, "Dust emission potential", "kg s**2 m**-5", "AERDEPDIFF"},
{53, "Lifting threshold speed", "m s**-1", "AERLTSDIFF"},
{54, "Soil clay content", "%", "AERSCCDIFF"},
{61, "Carbon Dioxide", "kg kg**-1", "CO2DIFF"},
{62, "Methane", "kg kg**-1", "CH4DIFF"},
{63, "Nitrous oxide", "kg kg**-1", "N2ODIFF"},
{64, "Total column Carbon Dioxide", "kg m**-2", "TCCO2DIFF"},
{65, "Total column Methane", "kg m**-2", "TCCH4DIFF"},
{66, "Total column Nitrous oxide", "kg m**-2", "TCN2ODIFF"},
{67, "Ocean flux of Carbon Dioxide", "kg m**-2 s**-1", "CO2OFDIFF"},
{68, "Natural biosphere flux of Carbon Dioxide", "kg m**-2 s**-1", "CO2NBFDIFF"},
{69, "Anthropogenic emissions of Carbon Dioxide", "kg m**-2 s**-1", "CO2APFDIFF"},
{70, "Methane Surface Fluxes", "kg m**-2 s**-1", "CH4FDIFF"},
{71, "Methane loss rate due to radical hydroxyl (OH)", "s**-1", "KCH4DIFF"},
{80, "Wildfire flux of Carbon Dioxide", "kg m**-2 s**-1", "CO2FIREDIFF"},
{81, "Wildfire flux of Carbon Monoxide", "kg m**-2 s**-1", "COFIREDIFF"},
{82, "Wildfire flux of Methane", "kg m**-2 s**-1", "CH4FIREDIFF"},
{83, "Wildfire flux of Non-Methane Hydro-Carbons", "kg m**-2 s**-1", "NMHCFIREDIFF"},
{84, "Wildfire flux of Hydrogen", "kg m**-2 s**-1", "H2FIREDIFF"},
{85, "Wildfire flux of Nitrogen Oxides NOx", "kg m**-2 s**-1", "NOXFIREDIFF"},
{86, "Wildfire flux of Nitrous Oxide", "kg m**-2 s**-1", "N2OFIREDIFF"},
{87, "Wildfire flux of Particulate Matter PM2.5", "kg m**-2 s**-1", "PM2P5FIREDIFF"},
{88, "Wildfire flux of Total Particulate Matter", "kg m**-2 s**-1", "TPMFIREDIFF"},
{89, "Wildfire flux of Total Carbon in Aerosols", "kg m**-2 s**-1", "TCFIREDIFF"},
{90, "Wildfire flux of Organic Carbon", "kg m**-2 s**-1", "OCFIREDIFF"},
{91, "Wildfire flux of Black Carbon", "kg m**-2 s**-1", "BCFIREDIFF"},
{92, "Wildfire overall flux of burnt Carbon", "kg m**-2 s**-1", "CFIREDIFF"},
{93, "Wildfire fraction of C4 plants", "dimensionless", "C4FFIREDIFF"},
{94, "Wildfire vegetation map index", "dimensionless", "VEGFIREDIFF"},
{95, "Wildfire Combustion Completeness", "dimensionless", "CCFIREDIFF"},
{96, "Wildfire Fuel Load", "kg m**-2", "FLFIREDIFF"},
{97, "Wildfire fraction of area observed", "dimensionless", "OFFIREDIFF"},
{98, "Wildfire observed area", "m**2", "OAFIREDIFF"},
{99, "Wildfire radiative power", "W m**-2", "FRPFIREDIFF"},
{100, "Wildfire combustion rate", "kg m**-2 s**-1", "CRFIREDIFF"},
{101, "Wildfire radiative power maximum", "W", "MAXFRPFIREDIFF"},
{102, "Wildfire flux of Sulfur Dioxide", "kg m**-2 s**-1", "SO2FIREDIFF"},
{103, "Wildfire Flux of Methanol (CH3OH)", "kg m**-2 s**-1", "CH3OHFIREDIFF"},
{104, "Wildfire Flux of Ethanol (C2H5OH)", "kg m**-2 s**-1", "C2H5OHFIREDIFF"},
{105, "Wildfire Flux of Propane (C3H8)", "kg m**-2 s**-1", "C3H8FIREDIFF"},
{106, "Wildfire Flux of Ethene (C2H4)", "kg m**-2 s**-1", "C2H4FIREDIFF"},
{107, "Wildfire Flux of Propene (C3H6)", "kg m**-2 s**-1", "C3H6FIREDIFF"},
{108, "Wildfire Flux of Isoprene (C5H8)", "kg m**-2 s**-1", "C5H8FIREDIFF"},
{109, "Wildfire Flux of Terpenes (C5H8)n", "kg m**-2 s**-1", "TERPENESFIREDIFF"},
{110, "Wildfire Flux of Toluene_lump (C7H8+ C6H6 + C8H10)", "kg m**-2 s**-1", "TOLUENEFIREDIFF"},
{111, "Wildfire Flux of Higher Alkenes (CnH2n, C", "kg m**-2 s**-1", "HIALKENESFIREDIFF"},
{112, "Wildfire Flux of Higher Alkanes (CnH2n+2, C", "kg m**-2 s**-1", "HIALKANESFIREDIFF"},
{113, "Wildfire Flux of Formaldehyde (CH2O)", "kg m**-2 s**-1", "CH2OFIREDIFF"},
{114, "Wildfire Flux of Acetaldehyde (C2H4O)", "kg m**-2 s**-1", "C2H4OFIREDIFF"},
{115, "Wildfire Flux of Acetone (C3H6O)", "kg m**-2 s**-1", "C3H6OFIREDIFF"},
{116, "Wildfire Flux of Ammonia (NH3)", "kg m**-2 s**-1", "NH3FIREDIFF"},
{117, "Wildfire Flux of Dimethyl Sulfide (DMS) (C2H6S)", "kg m**-2 s**-1", "C2H6SFIREDIFF"},
{118, "Wildfire Flux of Ethane (C2H6)", "kg m**-2 s**-1", "C2H6FIREDIFF"},
{119, "Altitude of emitter", "m above sea level", "ALEDIFF"},
{120, "Altitude of plume top", "m above sea level", "APTDIFF"},
{121, "Nitrogen dioxide", "kg kg**-1", "NO2DIFF"},
{122, "Sulphur dioxide", "kg kg**-1", "SO2DIFF"},
{123, "Carbon monoxide", "kg kg**-1", "CODIFF"},
{124, "Formaldehyde", "kg kg**-1", "HCHODIFF"},
{125, "Total column Nitrogen dioxide", "kg m**-2", "TCNO2DIFF"},
{126, "Total column Sulphur dioxide", "kg m**-2", "TCSO2DIFF"},
{127, "Total column Carbon monoxide", "kg m**-2", "TCCODIFF"},
{128, "Total column Formaldehyde", "kg m**-2", "TCHCHODIFF"},
{129, "Nitrogen Oxides", "kg kg**-1", "NOXDIFF"},
{130, "Total Column Nitrogen Oxides", "kg m**-2", "TCNOXDIFF"},
{131, "Reactive tracer 1 mass mixing ratio", "kg kg**-1", "GRG1DIFF"},
{132, "Total column GRG tracer 1", "kg m**-2", "TCGRG1DIFF"},
{133, "Reactive tracer 2 mass mixing ratio", "kg kg**-1", "GRG2DIFF"},
{134, "Total column GRG tracer 2", "kg m**-2", "TCGRG2DIFF"},
{135, "Reactive tracer 3 mass mixing ratio", "kg kg**-1", "GRG3DIFF"},
{136, "Total column GRG tracer 3", "kg m**-2", "TCGRG3DIFF"},
{137, "Reactive tracer 4 mass mixing ratio", "kg kg**-1", "GRG4DIFF"},
{138, "Total column GRG tracer 4", "kg m**-2", "TCGRG4DIFF"},
{139, "Reactive tracer 5 mass mixing ratio", "kg kg**-1", "GRG5DIFF"},
{140, "Total column GRG tracer 5", "kg m**-2", "TCGRG5DIFF"},
{141, "Reactive tracer 6 mass mixing ratio", "kg kg**-1", "GRG6DIFF"},
{142, "Total column GRG tracer 6", "kg m**-2", "TCGRG6DIFF"},
{143, "Reactive tracer 7 mass mixing ratio", "kg kg**-1", "GRG7DIFF"},
{144, "Total column GRG tracer 7", "kg m**-2", "TCGRG7DIFF"},
{145, "Reactive tracer 8 mass mixing ratio", "kg kg**-1", "GRG8DIFF"},
{146, "Total column GRG tracer 8", "kg m**-2", "TCGRG8DIFF"},
{147, "Reactive tracer 9 mass mixing ratio", "kg kg**-1", "GRG9DIFF"},
{148, "Total column GRG tracer 9", "kg m**-2", "TCGRG9DIFF"},
{149, "Reactive tracer 10 mass mixing ratio", "kg kg**-1", "GRG10DIFF"},
{150, "Total column GRG tracer 10", "kg m**-2", "TCGRG10DIFF"},
{151, "Surface flux Nitrogen oxides", "kg m**-2 s**-1", "SFNOXDIFF"},
{152, "Surface flux Nitrogen dioxide", "kg m**-2 s**-1", "SFNO2DIFF"},
{153, "Surface flux Sulphur dioxide", "kg m**-2 s**-1", "SFSO2DIFF"},
{154, "Surface flux Carbon monoxide", "kg m**-2 s**-1", "SFCO2DIFF"},
{155, "Surface flux Formaldehyde", "kg m**-2 s**-1", "SFHCHODIFF"},
{156, "Surface flux GEMS Ozone", "kg m**-2 s**-1", "SFGO3DIFF"},
{157, "Surface flux reactive tracer 1", "kg m**-2 s**-1", "SFGR1DIFF"},
{158, "Surface flux reactive tracer 2", "kg m**-2 s**-1", "SFGR2DIFF"},
{159, "Surface flux reactive tracer 3", "kg m**-2 s**-1", "SFGR3DIFF"},
{160, "Surface flux reactive tracer 4", "kg m**-2 s**-1", "SFGR4DIFF"},
{161, "Surface flux reactive tracer 5", "kg m**-2 s**-1", "SFGR5DIFF"},
{162, "Surface flux reactive tracer 6", "kg m**-2 s**-1", "SFGR6DIFF"},
{163, "Surface flux reactive tracer 7", "kg m**-2 s**-1", "SFGR7DIFF"},
{164, "Surface flux reactive tracer 8", "kg m**-2 s**-1", "SFGR8DIFF"},
{165, "Surface flux reactive tracer 9", "kg m**-2 s**-1", "SFGR9DIFF"},
{166, "Surface flux reactive tracer 10", "kg m**-2 s**-1", "SFGR10DIFF"},
{181, "Radon", "kg kg**-1", "RADIFF"},
{182, "Sulphur Hexafluoride", "kg kg**-1", "SF6DIFF"},
{183, "Total column Radon", "kg m**-2", "TCRADIFF"},
{184, "Total column Sulphur Hexafluoride", "kg m**-2", "TCSF6DIFF"},
{185, "Anthropogenic Emissions of Sulphur Hexafluoride", "kg m**-2 s**-1", "SF6APFDIFF"},
{203, "GEMS Ozone", "kg kg**-1", "GO3DIFF"},
{206, "GEMS Total column ozone", "kg m**-2", "GTCO3DIFF"},
{207, "Total Aerosol Optical Depth at 550nm", "-", "AOD550DIFF"},
{208, "Sea Salt Aerosol Optical Depth at 550nm", "-", "SSAOD550DIFF"},
{209, "Dust Aerosol Optical Depth at 550nm", "-", "DUAOD550DIFF"},
{210, "Organic Matter Aerosol Optical Depth at 550nm", "-", "OMAOD550DIFF"},
{211, "Black Carbon Aerosol Optical Depth at 550nm", "-", "BCAOD550DIFF"},
{212, "Sulphate Aerosol Optical Depth at 550nm", "-", "SUAOD550DIFF"},
{213, "Total Aerosol Optical Depth at 469nm", "-", "AOD469DIFF"},
{214, "Total Aerosol Optical Depth at 670nm", "-", "AOD670DIFF"},
{215, "Total Aerosol Optical Depth at 865nm", "-", "AOD865DIFF"},
{216, "Total Aerosol Optical Depth at 1240nm", "-", "AOD1240DIFF"}
};
