/*
 * Center: 98
 * Subcenter: 
 * Parameter table version: 221
 */

TBLE2 ecmwf_221_params[] = {
{1, "Ozone deposition velocity", "m s**-1", "DV_GO3"},
{2, "Nitrogen oxides deposition velocity", "m s**-1", "DV_NOX"},
{3, "Hydrogen peroxide deposition velocity", "m s**-1", "DV_H2O2"},
{4, "Methane deposition velocity", "m s**-1", "DV_CH4"},
{5, "Carbon monoxide deposition velocity", "m s**-1", "DV_CO"},
{6, "Nitric acid deposition velocity", "m s**-1", "DV_HNO3"},
{7, "Methyl peroxide deposition velocity", "m s**-1", "DV_CH3OOH"},
{8, "Formaldehyde deposition velocity", "m s**-1", "DV_HCHO"},
{9, "Paraffins deposition velocity", "m s**-1", "DV_PAR"},
{10, "Ethene deposition velocity", "m s**-1", "DV_C2H4"},
{11, "Olefins deposition velocity", "m s**-1", "DV_OLE"},
{12, "Aldehydes deposition velocity", "m s**-1", "DV_ALD2"},
{13, "Peroxyacetyl nitrate deposition velocity", "m s**-1", "DV_PAN"},
{14, "Peroxides deposition velocity", "m s**-1", "DV_ROOH"},
{15, "Organic nitrates deposition velocity", "m s**-1", "DV_ONIT"},
{16, "Isoprene deposition velocity", "m s**-1", "DV_C5H8"},
{17, "Sulfur dioxide deposition velocity", "m s**-1", "DV_SO2"},
{18, "Dimethyl sulfide deposition velocity", "m s**-1", "DV_DMS"},
{19, "Ammonia deposition velocity", "m s**-1", "DV_NH3"},
{20, "Sulfate deposition velocity", "m s**-1", "DV_SO4"},
{21, "Ammonium deposition velocity", "m s**-1", "DV_NH4"},
{22, "Methane sulfonic acid deposition velocity", "m s**-1", "DV_MSA"},
{23, "Methyl glyoxal deposition velocity", "m s**-1", "DV_CH3COCHO"},
{24, "Stratospheric ozone deposition velocity", "m s**-1", "DV_O3S"},
{25, "Radon deposition velocity", "m s**-1", "DV_RA"},
{26, "Lead deposition velocity", "m s**-1", "DV_PB"},
{27, "Nitrogen monoxide deposition velocity", "m s**-1", "DV_NO"},
{28, "Hydroperoxy radical deposition velocity", "m s**-1", "DV_HO2"},
{29, "Methylperoxy radical deposition velocity", "m s**-1", "DV_CH3O2"},
{30, "Hydroxyl radical deposition velocity", "m s**-1", "DV_OH"},
{31, "Nitrogen dioxide deposition velocity", "m s**-1", "DV_NO2"},
{32, "Nitrate radical deposition velocity", "m s**-1", "DV_NO3"},
{33, "Dinitrogen pentoxide deposition velocity", "m s**-1", "DV_N2O5"},
{34, "Pernitric acid deposition velocity", "m s**-1", "DV_HO2NO2"},
{35, "Peroxy acetyl radical deposition velocity", "m s**-1", "DV_C2O3"},
{36, "Organic ethers deposition velocity", "m s**-1", "DV_ROR"},
{37, "PAR budget corrector deposition velocity", "m s**-1", "DV_RXPAR"},
{38, "NO to NO2 operator deposition velocity", "m s**-1", "DV_XO2"},
{39, "NO to alkyl nitrate operator deposition velocity", "m s**-1", "DV_XO2N"},
{40, "Amine deposition velocity", "m s**-1", "DV_NH2"},
{41, "Polar stratospheric cloud deposition velocity", "m s**-1", "DV_PSC"},
{42, "Methanol deposition velocity", "m s**-1", "DV_CH3OH"},
{43, "Formic acid deposition velocity", "m s**-1", "DV_HCOOH"},
{44, "Methacrylic acid deposition velocity", "m s**-1", "DV_MCOOH"},
{45, "Ethane deposition velocity", "m s**-1", "DV_C2H6"},
{46, "Ethanol deposition velocity", "m s**-1", "DV_C2H5OH"},
{47, "Propane deposition velocity", "m s**-1", "DV_C3H8"},
{48, "Propene deposition velocity", "m s**-1", "DV_C3H6"},
{49, "Terpenes deposition velocity", "m s**-1", "DV_C10H16"},
{50, "Methacrolein MVK  deposition velocity", "m s**-1", "DV_ISPD"},
{51, "Nitrate deposition velocity", "m s**-1", "DV_NO3_A"},
{52, "Acetone deposition velocity", "m s**-1", "DV_CH3COCH3"},
{53, "Acetone product deposition velocity", "m s**-1", "DV_ACO2"},
{54, "IC3H7O2 deposition velocity", "m s**-1", "DV_IC3H7O2"},
{55, "HYPROPO2 deposition velocity", "m s**-1", "DV_HYPROPO2"},
{56, "Nitrogen oxides Transp deposition velocity", "m s**-1", "DV_NOXA"}
};
