#define NOOP			1
#define STOPSEQ			2
#define ENDSTMNT_OP			3
#define RETURN_OP			4
#define FPDEF 			5
#define NEW_FRAME_OP			6
#define BPROC_CALL_OP			7
#define FUNC_CALL_OP			8
#define PROC_CALL_OP			9
#define JMP			10
#define JMPFALSE 			11
#define DUP_TOFS 			12
#define DO_FROM_TO_OP			13
#define DO_FROM_TO_STRIDE_OP			14
#define DO_WHILE_OP			15
#define BREAK_OP			16
#define CONTINUE_OP			17
#define CREATE_OBJ_OP			18
#define SET_OBJ_OP			19
#define GET_OBJ_OP			20
#define CONVERT_TO_LOCAL 			21
#define PUSH_STRING_LIT_OP			22
#define PUSH_REAL_LIT_OP			23
#define PUSH_INT_LIT_OP			24
#define ARRAY_LIT_OP			25
#define NAMED_INT_SUBSCRIPT_OP			26
#define INT_SUBSCRIPT_OP			27
#define NAMED_COORD_SUBSCRIPT_OP			28
#define COORD_SUBSCRIPT_OP			29
#define SINGLE_INDEX_OP				30
#define DEFAULT_RANGE_OP			31
#define BFUNC_CALL_OP			32
#define RANGE_INDEX_OP			33
#define NEG_OP			34
#define NOT_OP			35
#define MOD_OP			36
#define OR_OP			37
#define AND_OP			38
#define XOR_OP			39
#define LTSEL_OP			40
#define GTSEL_OP			41
#define PLUS_OP			42
#define MINUS_OP			43
#define MUL_OP			44
#define MAT_OP			45
#define DIV_OP			46
#define EXP_OP			47
#define LE_OP			48
#define GE_OP			49
#define GT_OP			50
#define LT_OP			51
#define EQ_OP			52
#define NE_OP			53
#define FILE_VAR_OP			54
#define ASSIGN_FILE_VAR_OP			55
#define PARAM_FILE_VAR_OP			56
#define FILEVAR_DIM_OP			57
#define ASSIGN_FILEVAR_DIM_OP			58
#define PARAM_FILEVAR_DIM_OP			59
#define VAR_DIM_OP			60
#define ASSIGN_VAR_DIM_OP			61
#define PARAM_VAR_DIM_OP			62
#define FILEVAR_COORD_OP			63
#define ASSIGN_FILEVAR_COORD_OP			64
#define PARAM_FILEVAR_COORD_OP			65
#define FILEVARATT_OP			66
#define ASSIGN_FILEVARATT_OP			67
#define PARAM_FILEVARATT_OP			68
#define CREATE_OBJ_WP_OP 			69 
#define ASSIGN_VAR_OP			70
#define PARAM_VAR_OP			71
#define VARATT_OP			72
#define ASSIGN_VARATT_OP			73
#define PARAM_VARATT_OP				74
#define VAR_COORD_OP			75
#define ASSIGN_VAR_COORD_OP			76
#define PARAM_VAR_COORD_OP			77
#define VAR_READ_OP				78
#define VAR_READ_COORD_OP			79
#define INTRINSIC_FUNC_CALL			80
#define INTRINSIC_PROC_CALL			81
#define ASSIGN_VAR_VAR_OP			82
#define NEW_OP 					83
#define NEW_WM_OP				84
#define NUM_OPERATORS				85
