#define NOOP					1
#define STOPSEQ					2
#define ENDSTMNT_OP				3
#define RETURN_OP				4
#define FPDEF 					5
#define NEW_FRAME_OP				6
#define PUSHNULL				7 
#define FUNC_CALL_OP				8
#define PROC_CALL_OP				9
#define JMP					10
#define JMPFALSE 				11
#define DUP_TOFS 				12
#define LOOP_VALIDATE_OP			13
#define LOOP_INC_OP				14
#define DO_WHILE_OP				15
#define ASSIGN_VAR_COORD_ATT_OP			16
#define PARAM_VAR_COORD_ATT_OP			17
#define CREATE_OBJ_OP				18
#define SET_OBJ_OP				19
#define GET_OBJ_OP				20
#define CONVERT_TO_LOCAL 			21
#define PUSH_STRING_LIT_OP			22
#define PUSH_REAL_LIT_OP			23
#define PUSH_INT_LIT_OP				24
#define ARRAY_LIT_OP				25
#define NAMED_INT_SUBSCRIPT_OP			26
#define INT_SUBSCRIPT_OP			27
#define NAMED_COORD_SUBSCRIPT_OP		28
#define COORD_SUBSCRIPT_OP			29
#define SINGLE_INDEX_OP				30
#define DEFAULT_RANGE_OP			31
/*#define BFUNC_CALL_OP				32*/
#define RANGE_INDEX_OP				33
#define NEG_OP					34
#define NOT_OP					35
#define MOD_OP					36
#define OR_OP					37
#define AND_OP					38
#define XOR_OP					39
#define LTSEL_OP				40
#define GTSEL_OP				41
#define PLUS_OP					42
#define MINUS_OP				43
#define MUL_OP					44
#define MAT_OP					45
#define DIV_OP					46
#define EXP_OP					47
#define LE_OP					48
#define GE_OP					49
#define GT_OP					50
#define LT_OP					51
#define EQ_OP					52
#define NE_OP					53
#define FILE_VAR_OP				54
#define ASSIGN_FILE_VAR_OP			55
#define PARAM_FILE_VAR_OP			56
#define FILEVAR_DIM_OP				57
#define ASSIGN_FILEVAR_DIM_OP			58
#define PARAM_FILEVAR_DIM_OP			59
#define VAR_DIM_OP				60
#define ASSIGN_VAR_DIM_OP			61
#define PARAM_VAR_DIM_OP			62
#define FILEVAR_COORD_OP			63
#define ASSIGN_FILEVAR_COORD_OP			64
#define PARAM_FILEVAR_COORD_OP			65
#define FILEVARATT_OP				66
#define ASSIGN_FILEVARATT_OP			67
#define PARAM_FILEVARATT_OP			68
#define CREATE_OBJ_WP_OP 			69 
#define ASSIGN_VAR_OP				70
#define PARAM_VAR_OP				71
#define VARATT_OP				72
#define ASSIGN_VARATT_OP			73
#define PARAM_VARATT_OP				74
#define VAR_COORD_OP				75
#define ASSIGN_VAR_COORD_OP			76
#define PARAM_VAR_COORD_OP			77
#define VAR_READ_OP				78
#define CRETURN_OP				79
#define INTRINSIC_FUNC_CALL			80
#define INTRINSIC_PROC_CALL			81
#define ASSIGN_VAR_VAR_OP			82
#define NEW_OP 					83
#define NEW_WM_OP				84
#define VAR_COORD_ATT_OP			85
#define JMP_SCALAR_TRUE_OP			86
#define JMP_SCALAR_FALSE_OP			87
#define ISDEFINED_OP				88
#define PUSH_LOGICAL_LIT_OP 			89
#define FILEVAR_COORD_ATT_OP			90
#define PARAM_FILEVAR_COORD_ATT_OP		91
#define ASSIGN_FILEVAR_COORD_ATT_OP		92
#define VARVAL_READ_OP				93
#define FILEVARVAL_COORD_OP			94
#define VARVAL_COORD_OP				95
#define FILE_VARVAL_OP				96
#define LIST_READ_OP				97
#define SET_NEXT_OP				98
#define TERM_LIST_OP				99
#define LIST_CLEAR_TMP_OP			100
#define LIST_ASSIGN_VERIFY_SUB 			101
#define LIST_READ_FILEVAR_OP                    102
#define FILE_GROUP_OP				103
#define FILE_GROUPVAL_OP			104
#define ASSIGN_FILE_GROUP_OP			105
#define PARAM_FILE_GROUP_OP			106
#define LISTVAR_LIT_OP				107
#define REASSIGN_VAR_OP				108
#define REASSIGN_VAR_VAR_OP			109
#define REASSIGN_VARATT_OP			110
#define NUM_OPERATORS				111

