#define NOOP 				0
#define JMP 				1
#define JMPFALSE 			2
#define IF_OP 				3
#define CREATE_OBJ_OP			4
#define SET_OBJ_OP			5
#define GET_OBJ_OP			6
#define PUSH_STRING_LIT_OP		7
#define PUSH_VAR_OP			8
#define DO_FROM_TO_OP			9
#define DO_FROM_TO_STRIDE_OP		10
#define ASSIGN_OP			11
#define NAMED_INT_SUBSCRIPT_OP		12
#define INT_SUBSCRIPT_OP		13
#define NAMED_COORD_SUBSCRIPT_OP	14
#define COORD_SUBSCRIPT_OP		15
#define SINGLE_INDEX_OP			16
#define DEFAULT_RANGE_OP		17
#define RETURN_OP			18
#define IF_THEN_OP			19
#define RANGE_INDEX_OP			20
#define NEG_OP				21
#define NOT_OP				22
#define MOD_OP				23
#define OR_OP				24
#define AND_OP				25
#define XOR_OP				26
#define LTSEL_OP			27
#define GTSEL_OP			28
#define PLUS_OP				29
#define MINUS_OP			30
#define MUL_OP				31
#define MAT_OP				32
#define DIV_OP				33
#define EXP_OP				34
#define LE_OP				35
#define GE_OP				36
#define GT_OP				37
#define LT_OP				38
#define EQ_OP				39
#define NE_OP				40
#define PUSH_REAL_LIT_OP		41
#define PUSH_INT_LIT_OP			42
#define ARRAY_LIT_OP			43
#define DO_WHILE_OP			44
#define SUBSCRIPTED_VAR_OP		45
#define PUSH_FILE_OP			46
#define SUBSCRIPTED_FILE_VAR_OP		47
#define PUSH_FILE_VAR_OP		48
#define FILE_DIMNUM_OP			49
#define FILE_DIMNAME_OP			50
#define FILE_ATT_OP			51
#define SUBSCRIPTED_FILE_ATT_OP		52
#define STOPSEQ				53
#define VAR_DIMNUM_OP			54
#define SUBSCRIPTED_VARATT_OP 		55
#define VARATT_OP			56
#define VAR_DIMNAME_OP			57
#define VAR_COORD_OP			58
#define SUBSCRIPTED_VAR_COORD_OP	59
#define LINE				60
#define FPDEF 				61
#define BREAK_OP			62
#define CONTINUE_OP			63
#define NEW_FRAME_OP			64
#define ENDSTMNT_OP			65
#define FUNC_CALL_OP			66
#define PROC_CALL_OP			67
#define BPROC_CALL_OP			68
#define BFUNC_CALL_OP			69

#define NUM_OPERATORS			70


