      PROGRAM FAGEZMY
      PARAMETER (NPTS=200)
      PARAMETER (NCURVE=4)
      REAL YDRA(NPTS,NCURVE)

      DO 10 I=1,NPTS
	 DO 10 J=1,NCURVE
            YDRA(I,J)=SIN(I*0.1+0.2*J)*EXP(-0.01*I*0.1*J**2)
  10  CONTINUE

      CALL OPNGKS
      CALL EZMY (YDRA,NPTS,NCURVE,NPTS,'EZMY$')
      CALL CLSGKS

      STOP
      END
