#!/bin/csh -f
#
#      $Id: INSTALL,v 1.10 1996-04-19 16:53:58 haley Exp $
#
#########################################################################
#                                                                       #
#              Copyright (C)  1992                                      #
#        University Corporation for Atmospheric Research                #
#              All Rights Reserved                                      #
#                                                                       #
#########################################################################
#
#   File:       INSTALL
#
#   Author:     John Clyne
#           National Center for Atmospheric Research
#           PO 3000, Boulder, Colorado
#
#   Date:       Tue Sep 29 08:31:24 MDT 1992
#
#   Description:    Present the NCAR Graphics installation menu
#
#   Usage:      INSTALL
#
#   Environment:    
#           LOCALDIR (exported)     path to install scripts. 
#           VERSION (exported)  NCAR Graphics version number
#
#   Files:      $LOCALDIR/var/version   contains version number
#
#
#   Options:
#
#

#
# get the dir name where INSTALL lives
#
set dir = `expr \( x"$0" : x'\(/\)$' \) \| \( x"$0" : x'\(.*\)/[^/]*$' \) \| .`
if ($status != 0) then
    echo "$0 : Can't find working directory, <expr> failed" > /dev/tty
    exit 1
endif

setenv LOCALDIR "$dir"

setenv SYSTEM `$LOCALDIR/sys_type`
if ($status != 0) then
        exit 1
endif

setenv VERSION `cat $LOCALDIR/var/version.$SYSTEM`

while (1) 
    clear
cat <<EOF


                 NCAR Graphics Unix Version $VERSION
                     Copyright (C) 1987-1996
          University Corporation for Atmospheric Research
     The use of this Software is governed by a License Agreement.



        1.  Ordering information
        2.  Install software
        3.  Remove installed software
        4.  Help

        0.  Exit

EOF

    echo -n "    Select: "
    set answer =  $<
    switch ("$answer")
    case "1":
        clear
        cat <<EOF



    To order NCAR Graphics or request further information please call
    or write NCAR Graphics Information:

        University Corporation for Atmospheric Research
        SCD/NCAR Graphics Orders
        P.O. Box 3000
        Boulder, CO 80307-3000 (USA)

        Telephone:  (303) 497-1201
        Telex:      989764
        FAX:        (303) 497-1814
        email:      scdinfo@ncar.ucar.edu
EOF
        $LOCALDIR/pause
        
    
        breaksw

    case "2":
        $LOCALDIR/install_soft
        if ($status != 0) then
            $LOCALDIR/pause
        endif
        breaksw

    case "3":
        $LOCALDIR/remove_soft
        if ($status != 0) then
            $LOCALDIR/pause
        endif
        breaksw

    case "4":

        clear
        cat <<EOF


    This is the main menu for the NCAR Graphics software installation
    program. From this menu you may choose to: 

        1. Get information on ordering NCAR Graphics.

        2. Install NCAR Graphics software.

        3. Remove previously installed versions of NCAR Graphics.

        4. Print this help message.

        0. Exit the INSTALL program.
EOF
        $LOCALDIR/pause
        breaksw

    case "99":
        $PAGER bambi1.ani
        breaksw
    case "0":
        exit 0
        breaksw

    case ""
        breaksw

    default
        echo "Invalid option <$answer>"
        $LOCALDIR/pause
    endsw
end
