C
C	$Id: reset.f,v 1.1.1.1 1992-04-17 22:32:41 ncargd Exp $
C
      SUBROUTINE RESET
C
C  USER ENTRY POINT
C  USED IN DASHCHAR AND DASHSMTH FOR COMPATIBILITY WITH CONREC AND
C  AUTOGRAPH WHICH ALSO USE DASHSUPR.  THUS SUBROUTINE PERFORMS NO
C  FUNCTION.
C
C-----------------------------------------------------------------------
C
C REVISION HISTORY--
C
C MAY 1984         CONVERTED TO FORTRAN 77 AND GKS.  CHANGED ENTRY
C                  DASHD TO DASHDB AND DASHDC.  DISALLOWED REAL
C                  ISIZE ARGUMENTS.
C
C DECEMBER 1979    ADDED A LIBRARY STATISTICS CALL AND A REVISION
C                  HISTORY
C
C JUNE 1988        CHANGED THE NAME OF A COMMON BLOCK TO GET RID OF A
C                  WARNING FROM SEGLDR.  (DJK)
C
C-----------------------------------------------------------------------
      END
