C
C $Id: halfax.f,v 1.4 1994-03-17 17:27:52 kennison Exp $
C
      SUBROUTINE HALFAX (MJRX,MNRX,MJRY,MNRY,XINT,YINT,IXLB,IYLB)
        IF (ICFELL('HALFAX - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
        CALL GRIDAL (MJRX,MNRX,MJRY,MNRY,IXLB,IYLB,10,XINT,YINT)
        IF (ICFELL('HALFAX',2).NE.0) RETURN
        RETURN
      END
