C
C	$Id: halfax.f,v 1.3 1992-09-04 20:40:55 ncargd Exp $
C

      SUBROUTINE HALFAX (MJRX,MNRX,MJRY,MNRY,XINT,YINT,IXLB,IYLB)
        CALL GRIDAL (MJRX,MNRX,MJRY,MNRY,IXLB,IYLB,10,XINT,YINT)
        RETURN
      END
