C
C $Id: ctinlb.f,v 1.2 2004-03-19 22:51:55 kennison Exp $
C
C                Copyright (C)  2000
C        University Corporation for Atmospheric Research
C                All Rights Reserved
C
C This file is free software; you can redistribute it and/or modify
C it under the terms of the GNU General Public License as published
C by the Free Software Foundation; either version 2 of the License, or
C (at your option) any later version.
C
C This software is distributed in the hope that it will be useful, but
C WITHOUT ANY WARRANTY; without even the implied warranty of
C MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
C General Public License for more details.
C
C You should have received a copy of the GNU General Public License
C along with this software; if not, write to the Free Software
C Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
C USA.
C
      SUBROUTINE CTINLB (RPNT,IEDG,ITRI,RWRK,IWRK)
C
      DIMENSION RPNT(*),IEDG(*),ITRI(*),RWRK(*),IWRK(*)
C
C CTINLB generates the informational label; the quantities defining the
C label are added to the lists in real workspaces 3 and 4.
C
C
C Declare all of the CONPACKT common blocks.
C
C
C CTCOM1 contains integer and real variables.
C
      COMMON /CTCOM1/ ANCF,ANHL,ANIL,ANLL,CDMX,CHWM,CINS,CINT(10)
      COMMON /CTCOM1/ CINU,CLDB(256),CLDL(256),CLDR(256)
      COMMON /CTCOM1/ CLDT(256),CLEV(256),CLWA(258),CXCF
      COMMON /CTCOM1/ CXIL,CYCF,CYIL,DBLF,DBLM,DBLN,DBLV,DFLD,DMAX
      COMMON /CTCOM1/ DMIN,DOPT,DVAL,EPSI,FNCM,GRAV,GRSD,GSDM,HCHL
      COMMON /CTCOM1/ HCHS,HLSR,IAIA(258),IAIB(256),IBCF,IBHL
      COMMON /CTCOM1/ IBIL,IBLL,ICAF,ICCF,ICCL(258),ICFF,ICHI
      COMMON /CTCOM1/ ICHL,ICIL,ICLL(256),ICLO,ICLP(256),ICLS
      COMMON /CTCOM1/ ICLU(258),ICLV,ICLW,IDUF,IGCL,IGLB,IGRM
      COMMON /CTCOM1/ IGRN,IGVS,IHCF,IHLE,IIWS(2),IIWU,ILBC
      COMMON /CTCOM1/ IMPF,INCX(8),INCY(8),INHL,INIL,INIT,INLL
      COMMON /CTCOM1/ IOCF,IOHL,IOLL,IPAI,IPCF,IPIC,IPIE,IPIL,IPLL
      COMMON /CTCOM1/ IRWS(4),IRWU,ISET,ITBM,IWSO,JODP,JOMA
      COMMON /CTCOM1/ JOTZ,LCTM,LEA1,LEA2,LEA3,LEE1,LEE2,LEE3,LINS
      COMMON /CTCOM1/ LINT(10),LINU,LIWB,LIWK,LIWM,LIWS(2),LNLG
      COMMON /CTCOM1/ LOEN,LOPN,LOTN,LRWC,LRWG,LRWK,LRWM,LRWS(4)
      COMMON /CTCOM1/ LSDD,LSDL,LSDM,LTCF,LTHI,LTIL,LTLO,MIRO
      COMMON /CTCOM1/ NCLB(256),NCLV,NDGL,NEDG,NEXL,NEXT,NEXU
      COMMON /CTCOM1/ NLBS,NLSD,NLZF,NOMF,NOVS,NPNT,NR04,NSDL
      COMMON /CTCOM1/ NSDR,NTRI,OORV,PITH,SCFS,SCFU,SEGL,T2DS
      COMMON /CTCOM1/ UCMN,UCMX,UVPB,UVPL,UVPR,UVPS,UVPT,UWDB,UWDL
      COMMON /CTCOM1/ UWDR,UWDT,WCCF,WCHL,WCIL,WCLL,WLCF,WLHL,WLIL
      COMMON /CTCOM1/ WLLL,WOCH,WODA,WTCD,WTGR,WTNC,WTOD,WWCF,WWHL
      COMMON /CTCOM1/ WWIL,WWLL,XLBC,XMAX,XMIN,XVPL,XVPR,XWDL,XWDR
      COMMON /CTCOM1/ YLBC,YMAX,YMIN,YVPB,YVPT,YWDB,YWDT,ZMAX,ZMIN
C
      EQUIVALENCE (IIWS(1),II01),(LIWS(1),LI01)
      EQUIVALENCE (IIWS(2),II02),(LIWS(2),LI02)
      EQUIVALENCE (IRWS(1),IR01),(LRWS(1),LR01)
      EQUIVALENCE (IRWS(2),IR02),(LRWS(2),LR02)
      EQUIVALENCE (IRWS(3),IR03),(LRWS(3),LR03)
      EQUIVALENCE (IRWS(4),IR04),(LRWS(4),LR04)
      SAVE   /CTCOM1/
C
C CTCOM2 holds character parameters.
C
      COMMON /CTCOM2/ CHEX,CLBL(256),CLDP(258),CTMA,CTMB,FRMT
      COMMON /CTCOM2/ TXCF,TXHI,TXIL,TXLO
      CHARACTER*13 CHEX
      CHARACTER*64 CLBL
      CHARACTER*128 CLDP
      CHARACTER*500 CTMA,CTMB
      CHARACTER*8 FRMT
      CHARACTER*64 TXCF
      CHARACTER*32 TXHI
      CHARACTER*128 TXIL
      CHARACTER*32 TXLO
      SAVE   /CTCOM2/
C
C If the text string for the informational label is blank, do nothing.
C
      IF (TXIL(1:LTIL).EQ.' ') RETURN
C
C Otherwise, form the informational label ...
C
      CALL CTSBST (TXIL(1:LTIL),CTMA,LCTM)
C
C ... get sizing information for the label ...
C
      XPFS=XVPL+CXIL*(XVPR-XVPL)
      YPFS=YVPB+CYIL*(YVPT-YVPB)
      XLBC=CFUX(XPFS)
      IF (ICFELL('CTINLB',1).NE.0) RETURN
      YLBC=CFUY(YPFS)
      IF (ICFELL('CTINLB',2).NE.0) RETURN
      WCFS=CHWM*WCIL*(XVPR-XVPL)
      WWFS=CHWM*WWIL*(XVPR-XVPL)
C
      CALL PCGETI ('TE',ITMP)
      IF (ICFELL('CTINLB',3).NE.0) RETURN
      CALL PCSETI ('TE',1)
      IF (ICFELL('CTINLB',4).NE.0) RETURN
      CALL HLUCTCHIL (+1)
      IF (ICFELL('CTINLB',5).NE.0) RETURN
      IF (CTMA(1:LCTM).EQ.' ') GO TO 101
      CALL PLCHHQ (XLBC,YLBC,CTMA(1:LCTM),WCFS,360.,0.)
      IF (ICFELL('CTINLB',6).NE.0) RETURN
      CALL HLUCTCHIL (-1)
      IF (ICFELL('CTINLB',7).NE.0) RETURN
      CALL PCGETR ('DL',DSTL)
      IF (ICFELL('CTINLB',8).NE.0) RETURN
      CALL PCGETR ('DR',DSTR)
      IF (ICFELL('CTINLB',9).NE.0) RETURN
      CALL PCGETR ('DB',DSTB)
      IF (ICFELL('CTINLB',10).NE.0) RETURN
      CALL PCGETR ('DT',DSTT)
      IF (ICFELL('CTINLB',11).NE.0) RETURN
      CALL PCSETI ('TE',ITMP)
      IF (ICFELL('CTINLB',12).NE.0) RETURN
      DSTL=DSTL+WWFS
      DSTR=DSTR+WWFS
      DSTB=DSTB+WWFS
      DSTT=DSTT+WWFS
C
C ... and then put information about the label into the lists.
C
      SINA=SIN(.017453292519943*ANIL)
      COSA=COS(.017453292519943*ANIL)
C
      IXPO=MOD(IPIL+4,3)-1
C
      IF (IXPO.LT.0) THEN
        XPFS=XPFS+DSTL*COSA
        YPFS=YPFS+DSTL*SINA
      ELSE IF (IXPO.GT.0) THEN
        XPFS=XPFS-DSTR*COSA
        YPFS=YPFS-DSTR*SINA
      END IF
C
      IYPO=(IPIL+4)/3-1
C
      IF (IYPO.LT.0) THEN
        XPFS=XPFS-DSTB*SINA
        YPFS=YPFS+DSTB*COSA
      ELSE IF (IYPO.GT.0) THEN
        XPFS=XPFS+DSTT*SINA
        YPFS=YPFS-DSTT*COSA
      END IF
C
      XLBC=CFUX(XPFS)
      IF (ICFELL('CTINLB',13).NE.0) RETURN
      YLBC=CFUY(YPFS)
      IF (ICFELL('CTINLB',14).NE.0) RETURN
C
      NLBS=NLBS+1
      IF (4*NLBS.GT.LR03) THEN
        CALL CTGRWS (RWRK,3,MAX(4*NLBS,LR03+100),IWSE)
        IF (IWSE.NE.0.OR.ICFELL('CTINLB',15).NE.0) THEN
          NLBS=NLBS-1
          RETURN
        END IF
      END IF
      RWRK(IR03+4*(NLBS-1)+1)=XPFS
      RWRK(IR03+4*(NLBS-1)+2)=YPFS
      RWRK(IR03+4*(NLBS-1)+3)=.017453292519943*ANIL
      RWRK(IR03+4*(NLBS-1)+4)=-NR04
      NR04=NR04+6
      IF (NR04.GT.LR04) THEN
        CALL CTGRWS (RWRK,4,MAX(NR04,LR04+100),IWSE)
        IF (IWSE.NE.0.OR.ICFELL('CTINLB',16).NE.0) THEN
          NLBS=NLBS-1
          RETURN
        END IF
      END IF
      RWRK(IR04+NR04-5)=0.
      RWRK(IR04+NR04-4)=0.
      RWRK(IR04+NR04-3)=DSTL
      RWRK(IR04+NR04-2)=DSTR
      RWRK(IR04+NR04-1)=DSTB
      RWRK(IR04+NR04  )=DSTT
C
C Done.
C
  101 RETURN
C
      END
