.\" The first line of this file must contain the '\"[e][r][t][v] line
.\" to tell man to run the appropriate filter "t" for table.
.\"
.\"	$Id: nhlex.man,v 1.2 1994-12-05 23:08:18 haley Exp $
.\"
.\"######################################################################
.\"#									#
.\"#			   Copyright (C)  1993				#
.\"#		University Corporation for Atmospheric Research		#
.\"#			   All Rights Reserved				#
.\"#                                                                    #
.\"######################################################################
.\"
.\"     File:		nhlex.man.sed
.\"
.\"     Author:		Jeff W. Boote
.\"			National Center for Atmospheric Research
.\"			PO 3000, Boulder, Colorado
.\"
.\"     Date:		Wed Apr 7 10:29:48 MDT 1993
.\"
.\"     Description:	Describes the nhlex script and the example programs.
.\"
.TH nhlex 1Nhl "Prototype Release" "Nhl Prototype" "NCARG Nhl EXAMPLES"
.SH NAME
.nh
nhlex \- NCAR Graphics High Level Utilties Example Programs
.ny
.SH STATUS
These examples are part of the Nhl \fBprototype\fP library.  They are provided
so NCAR Graphics users can see the direction that future versions of the
package will take.  The Nhl/HLU library is provided on Suns and SGIs only.
.SH SYNOPSIS
\fBnhlex\fP 
[\fI\-A\fP]
[\fI\-clean\fP]
[\fI\-n\fP]
\fIname ...\fP
.SH OPTIONS
.IP "\-A\fP" 1i
Copy and execute all available examples.
.IP \-\fIclean\fP 1i
Remove everything but the ".ncgm" file.
.IP \-\fIn\fP 1i
Specifies that the example should not copy the executable or run.
.IP \fIname\fP 1i
List of example programs to retrieve.
.SH DESCRIPTION
.B nhlex
provides the user with access to example source code for the NCAR
Graphics High Level Utilities (The HLU Library). \fBnhlex\fP copies
the source code and an executable for the specified example(s) into
the current directory and then executes the example. If the requested
example creates an NCGM file, it will have the same name as the
example, suffixed with ".ncgm". An option allows you to request that
only the source code be copied to your directory, without copying the
executable or executing the example.  Another option allows you to
request that only the NCGM file be left in your directory and that all
other files created by \fBnhlex\fP be deleted.  The argument
\fIname\fP may be selected from the lists that appear below.
.SH "EXAMPLES AVAILABLE"
.IP nhl01 1i
This example demonstrates how to display an XyPlot to an X Window, and then
copy it to a meta file.
.IP nhl02 1i
This example demonstrates how to incorporate the HLU library with a GUI.
It uses an X/Motif interface, and also allows the user to copy frames from
the X Window to a meta file.
.IP nhl05 1i
This example shows how to use the TextItem object of the HLU library.
.IP nhl06 1i
This example demonstates how to use HLU objects with low level NCAR Graphics
library calls. 
.IP nhl07 1i
.IP nhl08 1i
.IP nhl09 1i
.IP nhl10 1i
.IP nhl11 1i
.IP nhl12 1i
.IP nhl13 1i
.IP nhlf01 1i
Fortran example.
.SH SEE ALSO
ncargcex(1NCARG)
.SH COPYRIGHT
Copyright 1987, 1988, 1989, 1991, 1993, 1994 University Corporation
for Atmospheric Research
.br
All Rights Reserved
