C
C	$Id: wmlgfa.f,v 1.3 2000-08-22 15:07:46 haley Exp $
C                                                                      
C                Copyright (C)  2000
C        University Corporation for Atmospheric Research
C                All Rights Reserved
C
C This file is free software; you can redistribute it and/or modify
C it under the terms of the GNU General Public License as published
C by the Free Software Foundation; either version 2 of the License, or
C (at your option) any later version.
C
C This software is distributed in the hope that it will be useful, but
C WITHOUT ANY WARRANTY; without even the implied warranty of
C MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
C General Public License for more details.
C
C You should have received a copy of the GNU General Public License
C along with this software; if not, write to the Free Software
C Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
C USA.
C
      SUBROUTINE WMLGFA(XXC,YYC,NNC)
C
C  Subroutine for processing polygons generated by calls to PPINPO.
C
      DIMENSION XXC(NNC),YYC(NNC)
C
C  IDRFLG = -1  means draw a polyline only.
C         =  0  means draw a filled area only.
C         =  1  draws a filled area and a representative line for
C               showers.
C         =  2  draws a filled area and a representative line for
C               t-storms.
C         =  3  draws a filled area for showers.
C
      COMMON /WMLGCM/IDRFLG
C
      IF (IDRFLG .EQ. -1) THEN
        CALL GPL(NNC,XXC,YYC)
      ELSE IF (IDRFLG .EQ. 0) THEN
        CALL GFA(NNC,XXC,YYC)
      ELSE IF (IDRFLG .EQ. 1) THEN
        CALL GFA(NNC,XXC,YYC)
        CALL GQLWSC(IER,SCLO)
        CALL GSLWSC(.5)
        CALL GPL(2,XXC(2),YYC(2))
        CALL GSLWSC(SCLO)
      ELSE IF (IDRFLG .EQ. 2) THEN
        CALL GFA(NNC,XXC,YYC)
        CALL GQLWSC(IER,SCLO)
        CALL GSLWSC(.5)
        CALL GPL(4,XXC,YYC)
        CALL GSLWSC(SCLO)
      ELSE IF (IDRFLG .EQ. 3) THEN
        CALL GFA(NNC,XXC,YYC)
      ELSE IF (IDRFLG .EQ. 4) THEN
        CALL GFA(NNC,XXC,YYC)
        CALL GQLWSC(IER,SCLO)
        CALL GSLWSC(.5)
        CALL GPL(2,XXC,YYC)
        CALL GSLWSC(SCLO)
      ENDIF
C
      RETURN
      END
