*wkColorMap : default
*wkBackgroundColor : (/0.,0.,0./)
*wkForegroundColor : (/1.,1.,1./)

*trXMinF : 10
*trXMaxF : 100
*trYMinF : 10
*trYMaxF : 100
!*trXLog : true
!*trYLog : true
*trXReverse : true
*trYReverse : true

*pmTickMarkDisplayMode : always
!*tmXBLabelsOn : false
*tmXTLabelsOn : false
!*tmYLLabelsOn : false
*tmYRLabelsOn : false
*tmXMajorGrid : true
*tmXMinorGrid : true
*tmYMajorGrid : true
*tmYMinorGrid : true
*tmXMajorGridLineColor : 30
*tmXMinorGridLineColor : 30
*tmYMajorGridLineColor : 30
*tmYMinorGridLineColor : 30

*DashPattern : 4
*EdgeColor : 2
*gsLineLabelString : ????
*gsLineLabelFontHeightF : 0.02
*gsLineLabelFont : helvetica-bold
*gsMarkerIndex : 12
*gsMarkerColor : 3
*gsMarkerSizeF : 0.035
*gsFillColor : 4
*gsFillIndex : 3
*gsEdgeDashPattern : 3
*gsEdgeThicknessF : 2.5
*gsEdgesOn : true
*gsLineColor : 6
