C
C	$Id: g01ctb.f,v 1.1.1.1 1992-04-17 22:33:56 ncargd Exp $
C
        SUBROUTINE G01CTB
C
C     SET COLOR REPRESENTATION (DEFINE COLOR TABLE ENTRY).
C
      COMMON /GKSIN1/FCODE,CONT,IL1,IL2,ID(128),RL1,RL2,RX(128),
     - RY(128),STRL1,STRL2,RERR
      COMMON /GKSIN2/STR
      INTEGER FCODE, CONT, IL1, IL2, ID, RL1, RL2
      INTEGER STRL1, STRL2, RERR
      REAL  RX, RY
      CHARACTER*80 STR
      COMMON  /G01WSL/  MWKID   ,MCONID ,MWTYPE ,MSTATE ,MOPEN  ,
     +                  MDEFMO  ,MREGMO ,MDEMPT ,MNFRAM ,MTUS   ,
     +                  RWINDO(4)       ,CWINDO(4)      ,
     +                  RWKVP (4)       ,CWKVP (4)      ,
     +                  MOLMAX  ,MOL    ,MCOVFL ,MCSORT ,MCOLI(256),
     +                  SRED(256)       ,SGREEN(256)    ,SBLUE(256),
     +                  MRCREC(4)       ,MRCLIP
        INTEGER         MWKID   ,MCONID ,MWTYPE ,MSTATE ,MOPEN
        INTEGER         MDEFMO  ,MREGMO ,MDEMPT ,MNFRAM ,MTUS
        INTEGER         MOLMAX  ,MOL    ,MCOVFL ,MCSORT ,MCOLI
        REAL            RWINDO          ,CWINDO
        REAL            RWKVP           ,CWKVP
        REAL            SRED            ,SGREEN         ,SBLUE
        INTEGER         MRCREC  ,MRCLIP
      COMMON  /G01INS/  MCODES  ,MCONTS ,
     +                  MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW ,
     +                  MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL ,
     +                  MINXVD  ,MAXXVD ,MINYVD ,MAXYVD ,
     +                  MCFRM   ,MCOPCL ,MCOPID ,MCNBYT ,
     +                  MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG ,
     +                  MBCCHG
        INTEGER         MCODES  ,MCONTS
        INTEGER         MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW
        INTEGER         MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL
        INTEGER         MINXVD  ,MAXXVD ,MINYVD ,MAXYVD
        INTEGER         MCFRM   ,MCOPCL ,MCOPID ,MCNBYT
        INTEGER         MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG
        INTEGER         MBCCHG
C
C  Id code parameters for every element, and class codes for each class.
C
      COMMON /G01OPC/ IDNOOP, IDBEGM, IDENDM, IDBEGP, IDBGPB, IDENDP
      COMMON /G01OPC/ IDMVER, IDMELT, IDDREP, IDCSEL, IDVEXT, IDVINT
      COMMON /G01OPC/ IDCREC, IDCLIN, IDPLIN, IDPMRK, IDTEXT, IDPGON
      COMMON /G01OPC/ IDCARY, IDGDP,  IDLBIX, IDLTYP, IDLWID, IDLCLR
      COMMON /G01OPC/ IDMBIX, IDMTYP, IDMSIZ, IDMCLR, IDTBIX, IDTFON
      COMMON /G01OPC/ IDTPRE, IDCHEX, IDCHSP, IDTCLR, IDCHHT, IDCHOR
      COMMON /G01OPC/ IDTXPA, IDTXAL, IDFBIX, IDINTS, IDFCLR, IDHAIX
      COMMON /G01OPC/ IDPTIX, IDFRPT, IDPTBL, IDPTSZ, IDCTBL, IDASFS
      COMMON /G01OPC/ IDESC,  IDMESS, IDAPLD, IDBKGC, IDDSCR, IDFLST
      COMMON /G01OPC/ CLDELM, CLMDES, CLPDES, CLCNTL, CLPRIM, CLPRAT
      COMMON /G01OPC/ CLESCE, CLEXTE
C
C  Parameter data types.
C
      INTEGER         IDNOOP, IDBEGM, IDENDM, IDBEGP, IDBGPB, IDENDP
      INTEGER         IDMVER, IDMELT, IDDREP, IDCSEL, IDVEXT, IDVINT
      INTEGER         IDCREC, IDCLIN, IDPLIN, IDPMRK, IDTEXT, IDPGON
      INTEGER         IDCARY, IDGDP,  IDLBIX, IDLTYP, IDLWID, IDLCLR
      INTEGER         IDMBIX, IDMTYP, IDMSIZ, IDMCLR, IDTBIX, IDTFON
      INTEGER         IDTPRE, IDCHEX, IDCHSP, IDTCLR, IDCHHT, IDCHOR
      INTEGER         IDTXPA, IDTXAL, IDFBIX, IDINTS, IDFCLR, IDHAIX
      INTEGER         IDPTIX, IDFRPT, IDPTBL, IDPTSZ, IDCTBL, IDASFS
      INTEGER         IDESC,  IDMESS, IDAPLD, IDBKGC, IDDSCR, IDFLST
      INTEGER         CLDELM, CLMDES, CLPDES, CLCNTL, CLPRIM, CLPRAT
      INTEGER         CLESCE, CLEXTE
C
C Class code parameters for every element.
C
      INTEGER         CLNOOP, CLBEGM, CLENDM, CLBEGP, CLBGPB, CLENDP
      INTEGER         CLMVER, CLMELT, CLDREP, CLCSEL, CLVEXT, CLVINT
      INTEGER         CLCREC, CLCLIN, CLPLIN, CLPMRK, CLTEXT, CLPGON
      INTEGER         CLCARY, CLGDP,  CLLBIX, CLLTYP, CLLWID, CLLCLR
      INTEGER         CLMBIX, CLMTYP, CLMSIZ, CLMCLR, CLTBIX, CLTFON
      INTEGER         CLTPRE, CLCHEX, CLCHSP, CLTCLR, CLCHHT, CLCHOR
      INTEGER         CLTXPA, CLTXAL, CLFBIX, CLINTS, CLFCLR, CLHAIX
      INTEGER         CLPTIX, CLFRPT, CLPTBL, CLPTSZ, CLCTBL, CLASFS
      INTEGER         CLESC,  CLMESS, CLAPLD, CLBKGC, CLDSCR, CLFLST
C
C  Equivalence all individual class code parameters to the single
C  code for the class in which the element(s) belong.
C
      EQUIVALENCE (CLDELM, CLNOOP,CLBEGM,CLENDM,CLBEGP,CLBGPB,CLENDP)
      EQUIVALENCE (CLMDES, CLMVER,CLMELT,CLDREP,CLDSCR,CLFLST)
      EQUIVALENCE (CLPDES, CLCSEL,CLVEXT,CLBKGC)
      EQUIVALENCE (CLCNTL, CLVINT,CLCREC,CLCLIN)
      EQUIVALENCE (CLPRIM, CLPLIN,CLPMRK,CLTEXT,CLPGON,CLCARY,CLGDP)
      EQUIVALENCE (CLPRAT, CLLBIX,CLLTYP,CLLWID,CLLCLR,CLMBIX,CLMTYP)
      EQUIVALENCE (CLPRAT, CLMSIZ,CLMCLR,CLTBIX,CLTFON,CLTPRE,CLCHEX)
      EQUIVALENCE (CLPRAT, CLCHSP,CLTCLR,CLCHHT,CLCHOR,CLTXPA,CLTXAL)
      EQUIVALENCE (CLPRAT, CLFBIX,CLINTS,CLFCLR,CLHAIX,CLPTIX,CLFRPT)
      EQUIVALENCE (CLPRAT, CLPTBL,CLPTSZ,CLCTBL,CLASFS)
      EQUIVALENCE (CLESCE, CLESC), (CLEXTE, CLMESS,CLAPLD)
      COMMON /GKSENU/ GYES,  GNO,   GCONDI, GALWAY, GACTIV, GINACT
      COMMON /GKSENU/ GEMPTY,GNEMPT,GPEND,  GNPEND, GCLIP , GNCLIP
C
      INTEGER         GYES,  GNO,   GCONDI, GALWAY, GACTIV, GINACT
      INTEGER         GEMPTY,GNEMPT,GPEND,  GNPEND, GCLIP , GNCLIP
C
      INTEGER  NCIX, NBYTES, I, IPTR
C
C     SCAN COLOR TABLE TO SEE IF INDEX ALREADY EXISTS,
C     FIND ITS POSITION IN TABLE OTHERWISE (BINARY SEARCH
C     SHOULD BE USED HERE).
C
        NCIX = ID(2)
        DO 10 I=1,MOL
           IPTR = I
           IF (MCOLI(I)-NCIX)  10, 20, 15
10      CONTINUE
C
C     FALL THRU MEANS INDEX NOT DEFINED YET, AND ITS
C     HIGHER THAN THE HIGHEST DEFINED INDEX.
C
        IPTR = MOL + 1
C
C     INDEX UNDEFINED, BELONGS AT POSITION IPTR IN THE TABLE.
C     TEST FOR ROOM IN THE TABLE, MOVE TABLE DOWN.
C
15      CONTINUE
        IF (MOL.GE.MOLMAX)  THEN
C
C          ERROR; TABLE IS FULL, SET ERROR, MARK OVERFLOW, AND RETURN.
C            (WHICH ERROR IS APPLICABLE?)
C          RERR = 86?
           RERR = 301
           MCOVFL = 1
           RETURN
        ELSE
C
C          MOVE TABLE DOWN, INCREMENT COUNT OF DEFINED INDICES.
           DO 18 I=MOL,IPTR,-1
              MCOLI(I+1)  = MCOLI(I)
              SRED(I+1)   = SRED(I)
              SGREEN(I+1) = SGREEN(I)
              SBLUE(I+1)  = SBLUE(I)
18         CONTINUE
           MOL = MOL + 1
        END IF
C
C     INSERT/REPLACE NEW COLOR TABLE ENTRY.
C
20      CONTINUE
        MCOLI(IPTR)  = NCIX
        SRED(IPTR)   = RX(1)
        SGREEN(IPTR) = RX(2)
        SBLUE(IPTR)  = RX(3)
C
C     MARK CHANGE TO COLOR TABLE.  MARK BACKGROUND COLOR
C     CHANGE IF APPROPRIATE.
C
        MCTCHG = GYES
        IF (NCIX.EQ.0)  MBCCHG = GYES
C
C     NORMALIZE REAL COMPONENTS TO INTEGER RANGE.
C
        ID(1) = RX(1)*MDCCRG
        ID(2) = RX(2)*MDCCRG
        ID(3) = RX(3)*MDCCRG
C
C     GENERATE METAFILE INSTRUCTION WITH NEW ENTRY.
C
C       COMPUTE INSTRUCTION PARAMETER LIST LENGTH -- NUMBER OF BYTES
C         TO HOLD    START INDEX + RED + GREEN + BLUE
        NBYTES = 1 + (3*MDCCFW + MCIXFW - 1)/8
C
C       PUT OUT OPCODE (CLASS AND ID) AND LENGTH.
C                CLASS, ID, LENGTH
        CALL GPUTNI (CLCTBL, IDCTBL, NBYTES, RERR)
        IF (RERR.NE.0)  RETURN
C
C       PUT OUT PARAMETER INDEX.
C                    DATA, PRECIS, COUNT
        CALL GPUTPR (NCIX, MCIXFW, 1, RERR)
        IF (RERR.NE.0)  RETURN
C
C       PUT OUT 3 COLOR COMPONENTS.
C                  DATA, PRECIS, COUNT
        CALL GPUTPR (ID, MDCCFW, 3, RERR)
C
C     ALL DONE.
C
        RETURN
C
        END
