C
C	$Id: g01diq.f,v 1.1.1.1 1992-04-17 22:33:57 ncargd Exp $
C
        SUBROUTINE G01DIQ
C
C       WORKSTATION DESCRIPTION TABLE (WDT) INQUIRY.
C               (OPCODE -100 THRU -199)
C
      COMMON /GKSIN1/FCODE,CONT,IL1,IL2,ID(128),RL1,RL2,RX(128),
     - RY(128),STRL1,STRL2,RERR
      COMMON /GKSIN2/STR
      INTEGER FCODE, CONT, IL1, IL2, ID, RL1, RL2
      INTEGER STRL1, STRL2, RERR
      REAL  RX, RY
      CHARACTER*80 STR
      COMMON  /G01WDT/  LWTYPE, LWKCAT, MVERSN
        INTEGER         LWTYPE, LWKCAT, MVERSN
      COMMON  /G01INS/  MCODES  ,MCONTS ,
     +                  MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW ,
     +                  MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL ,
     +                  MINXVD  ,MAXXVD ,MINYVD ,MAXYVD ,
     +                  MCFRM   ,MCOPCL ,MCOPID ,MCNBYT ,
     +                  MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG ,
     +                  MBCCHG
        INTEGER         MCODES  ,MCONTS
        INTEGER         MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW
        INTEGER         MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL
        INTEGER         MINXVD  ,MAXXVD ,MINYVD ,MAXYVD
        INTEGER         MCFRM   ,MCOPCL ,MCOPID ,MCNBYT
        INTEGER         MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG
        INTEGER         MBCCHG
C
C
        INTEGER  ICODE
C
C
C       ALL DEFINED WDT INQUIRY CODES LIE IN RANGE -11O THRU -128.
C       ONLY -127 IS LEGAL FOR MO.  THE REST ARE ERROR 31 OR 39,
C       EXCEPT -125 AND -126, WHICH IS ARE UNDEFINED.  SEE DESIGN
C       SPEC OR INTERFACE SPEC FOR OPCODE DEFINITIONS.
C
C
        ICODE = IABS(MCODES) - 109
C
C        CODE -110 -111 -112 -113 -114 -115 -116 -117 -118 -119
        GOTO  ( 39,  39,  39,  39,  31,  39,  39,  39,  39,  39,
     +          39,  39,  39,  39,  39,   5,   5, 127,  31     )  ICODE
C        CODE -120 -121 -122 -123 -124 -125 -126 -127 -128
C
C       FALL THROUGH IS UNDEFINED OPCODE.
C
5       CONTINUE
        RERR = 320
        RETURN
C
C       ERROR 31, "SPECIFIED WORKSTATION IS OF CATEGORY MO".
C
31      CONTINUE
        RERR = 31
        RETURN
C
C       ERROR 39, "SPECIFIED WORKSTATION IS NEITHER OF CATEGORY OUTPUT
C       NOR OF CATEGORY OUTIN".
C
39      CONTINUE
        RERR = 39
        RETURN
C
C       INQUIRE WORKSTATION CATEGORY.
C
127     CONTINUE
        ID(2) = LWKCAT
        RETURN
C
        END
