C
C	$Id: g01iws.f,v 1.1.1.1 1992-04-17 22:33:58 ncargd Exp $
C
        SUBROUTINE G01IWS
C
C     INITIALIZATION OF CONSTANTS.
C
C
C     INITIALIZE WORKSTATION STATE LIST AND OTHER INTERNAL CONSTANTS
C     AS REQUIRED UPON OPEN WORKSTATION.
C
      COMMON  /G01WSL/  MWKID   ,MCONID ,MWTYPE ,MSTATE ,MOPEN  ,
     +                  MDEFMO  ,MREGMO ,MDEMPT ,MNFRAM ,MTUS   ,
     +                  RWINDO(4)       ,CWINDO(4)      ,
     +                  RWKVP (4)       ,CWKVP (4)      ,
     +                  MOLMAX  ,MOL    ,MCOVFL ,MCSORT ,MCOLI(256),
     +                  SRED(256)       ,SGREEN(256)    ,SBLUE(256),
     +                  MRCREC(4)       ,MRCLIP
        INTEGER         MWKID   ,MCONID ,MWTYPE ,MSTATE ,MOPEN
        INTEGER         MDEFMO  ,MREGMO ,MDEMPT ,MNFRAM ,MTUS
        INTEGER         MOLMAX  ,MOL    ,MCOVFL ,MCSORT ,MCOLI
        REAL            RWINDO          ,CWINDO
        REAL            RWKVP           ,CWKVP
        REAL            SRED            ,SGREEN         ,SBLUE
        INTEGER         MRCREC  ,MRCLIP
      COMMON  /G01INS/  MCODES  ,MCONTS ,
     +                  MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW ,
     +                  MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL ,
     +                  MINXVD  ,MAXXVD ,MINYVD ,MAXYVD ,
     +                  MCFRM   ,MCOPCL ,MCOPID ,MCNBYT ,
     +                  MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG ,
     +                  MBCCHG
        INTEGER         MCODES  ,MCONTS
        INTEGER         MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW
        INTEGER         MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL
        INTEGER         MINXVD  ,MAXXVD ,MINYVD ,MAXYVD
        INTEGER         MCFRM   ,MCOPCL ,MCOPID ,MCNBYT
        INTEGER         MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG
        INTEGER         MBCCHG
      COMMON /GKSENU/ GYES,  GNO,   GCONDI, GALWAY, GACTIV, GINACT
      COMMON /GKSENU/ GEMPTY,GNEMPT,GPEND,  GNPEND, GCLIP , GNCLIP
C
      INTEGER         GYES,  GNO,   GCONDI, GALWAY, GACTIV, GINACT
      INTEGER         GEMPTY,GNEMPT,GPEND,  GNPEND, GCLIP , GNCLIP
C
C     INTERNAL CONSTANTS.
C
C       MIN AND MAX VDC ADDRESS LIMITS IN X AND Y DIRECTIONS,
C       THE VDC EXTENT.
C
        MINXVD = 0
        MAXXVD = 32767
        MINYVD = 0
        MAXYVD = 32767
C
C       NDC TO VDC MAPPING COEFFICIENTS, X AND Y DIRECTIONS.
        MXOFF = 0
        MXSCAL = 32767
        MYOFF = 0
        MYSCAL = 32767
C
C       COLOR TABLE CHANGE, BACKGROUND COLOR CHANGE.
        MCTCHG = GNO
        MBCCHG = GNO
C
C     WSL ITEMS.
C
C       STATE IS INACTIVE (0=GINACT)
        MSTATE = GINACT
C
C       DEFERRAL MODE IS ASTI (3=GASTI)
        MDEFMO = 3
C
C       IMPLICIT REGENERATION MODE IS ALLOWED (1=GALLOW)
        MREGMO = 1
C
C       DISPLAY SURFACE IS EMPTY (1=GEMPTY)
        MDEMPT = GEMPTY
C
C       NEW FRAME NECESSARY AT UPDATE IS NO (0=GNO)
        MNFRAM = GNO
C
C       WORKSTATION TRANSFORMATION UPDATE STATE IS NOTPENDING (0=GNPEND)
        MTUS = GNPEND
C
C       REQUESTED WORKSTATION WINDOW IN NDC IS UNIT SQUARE
        RWINDO(1) = 0.0
        RWINDO(2) = 1.0
        RWINDO(3) = 0.0
        RWINDO(4) = 1.0
C
C       CURRENT WORKSTATION WINDOW IN NDC IS UNIT SQUARE
        CWINDO(1) = 0.0
        CWINDO(2) = 1.0
        CWINDO(3) = 0.0
        CWINDO(4) = 1.0
C
C       REQUESTED WORKSTATION VIEWPORT IS REAL METACODE ADDRESS
C       SPACE
        RWKVP(1) = 0.
        RWKVP(2) = 32767.
        RWKVP(3) = 0.
        RWKVP(4) = 32767.
C
C       CURRENT WORKSTATION VIEWPORT IS METACODE ADDRESS SPACE.
        CWKVP(1) = 0.
        CWKVP(2) = 32767.
        CWKVP(3) = 0.
        CWKVP(4) = 32767.
C
C       COLOR INDICES ARE SORTED BY DEFAULT.
        MCSORT = 1
C
C       NUMBER OF CURRENTLY DEFINED COLOR INDICES IS 0.
        MOL = 0
C
C       OVERFLOW FLAG FOR COLOR INDEX ARRAYS IS NO (0=GNO).
        MCOVFL = GNO
C
C     WSL CLIPPING CONTROL PARAMETERS.
C
C       CLIPPING INDICATOR IS ON (1=GCLIP)
        MRCLIP = GCLIP
C
C       CLIPPING RECTANGLE IS METACODE ADDRESS SPACE, CORNER-PT FORM.
        MRCREC(1) = MINXVD
        MRCREC(2) = MINYVD
        MRCREC(3) = MAXXVD
        MRCREC(4) = MAXYVD
C
        RETURN
C
        END
