#!/bin/csh -f

set utility = bwi

set source = g01mio.f

echo ""
echo "Generic to UNIX modifications for $utility/$source :"
echo "	Adding calls to C interface routines for UNIX version"

if (! -e $source ) then
	echo "Error: Cannot locate $source"
	exit 1
endif

ed <<'EOF' - $source >/dev/null
/SUBROUTINE/
a
C Modification for UNIX Version
C------------------------------------------------------------------------------
C
C	g01mio.f - UNIX Version of G01MIO().
C
C	The UNIX version of this routine allows the metafile
C	output to be specified using environment variables.
C	It does not actually use FORTRAN I/O.
C
C	Two environment variables play a part in this.
C
C	If NCARG_GKS_OUTPUT is not defined, the default file output
C	is determined by the procedure that calls G01MIO().
C
C	NCARG_GKS_OUTPUT can also be defined in two ways:
C
C	1. As a filename - CGM output will be directed to the
C	   file. (e.g. setenv NCARG_GKS_OUTPUT myfile)
C
C	2. A process, the name of which is preceeded by a pipe
C	   symbol. (e.g. setenv NCARG_GKS_OUTPUT "| translator")
C	   If no name follows the pipe symbol, a default translator
C	   is invoked.
C
C	(NOTE: stdout to a translator is not used because of
C	potential conflicts with user code writing to LU 6.
C
C------------------------------------------------------------------------------
C End of modification for UNIX Version
.
/      INTEGER  IRR,IAUNT/
.,$c
C Modification for UNIX Version
      INTEGER IAUNT
C
C
      ERROR = 0

      IAUNT = IABS(UNIT)

C Open the workstation with filename FNAME

      IF (OP.EQ.1) THEN
	CALL OPNWKS(IAUNT, FNAME, ERROR)

C Close the workstation attached to IAUNT

      ELSE IF (OP.EQ.2) THEN
	CALL CLSWKS(IAUNT, ERROR)

C Write the BUFFER to the workstation

      ELSE IF (OP.EQ.3) THEN
	CALL WRTWKS(IAUNT, BUFFER, LENGTH, ERROR)

C Read from current location into BUFFER

      ELSE IF (OP.EQ.4) THEN
	CALL RDWKS(IAUNT, BUFFER, LENGTH, ERROR)

C Move file pointer to beginning

      ELSE IF (OP.EQ.5) THEN
	CALL BEGWKS(IAUNT, ERROR)

C Move file pointer back one record

      ELSE IF (OP.EQ.6) THEN
	CALL LSTWKS(IAUNT, ERROR)

      ENDIF

      END
.
w
q
'EOF'
