C
C	$Id: gmpart.f,v 1.1.1.1 1992-04-17 22:34:00 ncargd Exp $
C
      SUBROUTINE GMPART(NBYTES,GKSERR)
C
C  THIS INSTRUCTION LOADS THE NEXT PARTITION OF AN ACTIVE INSTRUCTION
C
C  OUTPUT
C       GKSERR-THE ERROR STATUS FLAG
C
C  ALL DATA IS TYPE INTEGER UNLESS OTHERWISE INDICATED
C
      IMPLICIT INTEGER (A-Z)
C
C  COMMON FOR COMMUNICATION OF INSTRUCTION AND LENGTH
C
      COMMON  /G01INS/  MCODES  ,MCONTS ,
     +                  MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW ,
     +                  MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL ,
     +                  MINXVD  ,MAXXVD ,MINYVD ,MAXYVD ,
     +                  MCFRM   ,MCOPCL ,MCOPID ,MCNBYT ,
     +                  MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG ,
     +                  MBCCHG
        INTEGER         MCODES  ,MCONTS
        INTEGER         MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW
        INTEGER         MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL
        INTEGER         MINXVD  ,MAXXVD ,MINYVD ,MAXYVD
        INTEGER         MCFRM   ,MCOPCL ,MCOPID ,MCNBYT
        INTEGER         MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG
        INTEGER         MBCCHG
      COMMON  /G01IO/   MIOFLG  ,MRECNM ,MPXYSZ ,MPXPY(256)     ,
     +                  MOBFSZ  ,MOUTBF(720)    ,MBFPOS ,
     +                  MFGLUN  ,MXBITS         ,MDTYPE ,
     +                  MNFFLG  ,MBMFLG ,MEMFLG
        INTEGER         MIOFLG  ,MRECNM ,MPXYSZ ,MPXPY  ,MOBFSZ ,
     +                  MBFPOS  ,MFGLUN ,MOUTBF ,MXBITS ,MDTYPE ,
     +                  MNFFLG  ,MBMFLG ,MEMFLG
      COMMON  /G01CHA/  MFNAME  ,MPNAME
      CHARACTER*80      MFNAME  ,MPNAME
C
C  Define the CGM data element partition size.  To make the arithmetic
C  come out right in other parts of the code, this should be a multiple
C  of 256.
C
      DATA PARSIZ/32256/
C
C  DEFINE THE ALLOK STATUS.
C
      DATA ALLOK/0/
C
C  DEFINE THE SHORT FORMAT LENGTH, SHORT FORMAT COUNT, LONG FORMAT FLAG,
C    CONTINUE FLAG ON, CONTINUE FLAG OFF, CONTINUE LENGTH, LONG FORMAT
C    LENGTH
C
      DATA CONON,CONOFF,CFMLNG,LFMLNG
     1          /1,0,1,15/
C
C  SET ERROR STATUS TO ALL OK
C
      GKSERR = ALLOK
C
C  SET THE CURRENT PARTITION BYTE COUNT AND THE REMAINDER BYTE COUNT
C
      IF (NBYTES .GT. PARSIZ) THEN
        MCCBYT = PARSIZ
        MCNBYT = NBYTES - PARSIZ
      ELSE
        MCCBYT = NBYTES
        MCNBYT = 0
      END IF
C
C  SET THE CONTINUE FLAG
C
      IF (MCNBYT .NE. 0) THEN
C
C               THERE IS ANOTHER PARTITION
C
                CALL GMFLOD(CONON,CFMLNG,1,GKSERR)
      ELSE
C
C               LAST PARTITION
C
                CALL GMFLOD(CONOFF,CFMLNG,1,GKSERR)
      END IF
C
      IF (GKSERR .NE. ALLOK) RETURN
C
C  SET THE LONG FORMAT OPERAND LIST SIZE
C
      CALL GMFLOD(MCCBYT,LFMLNG,1,GKSERR)
C
      RETURN
      END
