C
C	$Id: gputmd.f,v 1.1.1.1 1992-04-17 22:34:01 ncargd Exp $
C
      SUBROUTINE GPUTMD (ERROR)
C
C  GENERATE METAFILE DESCRIPTOR.
C  FOR NOW, VERSION AND ELEMENTS LIST.
C
      INTEGER  ERROR
C
      COMMON  /G01WDT/  LWTYPE, LWKCAT, MVERSN
        INTEGER         LWTYPE, LWKCAT, MVERSN
C
C  Id code parameters for every element, and class codes for each class.
C
      COMMON /G01OPC/ IDNOOP, IDBEGM, IDENDM, IDBEGP, IDBGPB, IDENDP
      COMMON /G01OPC/ IDMVER, IDMELT, IDDREP, IDCSEL, IDVEXT, IDVINT
      COMMON /G01OPC/ IDCREC, IDCLIN, IDPLIN, IDPMRK, IDTEXT, IDPGON
      COMMON /G01OPC/ IDCARY, IDGDP,  IDLBIX, IDLTYP, IDLWID, IDLCLR
      COMMON /G01OPC/ IDMBIX, IDMTYP, IDMSIZ, IDMCLR, IDTBIX, IDTFON
      COMMON /G01OPC/ IDTPRE, IDCHEX, IDCHSP, IDTCLR, IDCHHT, IDCHOR
      COMMON /G01OPC/ IDTXPA, IDTXAL, IDFBIX, IDINTS, IDFCLR, IDHAIX
      COMMON /G01OPC/ IDPTIX, IDFRPT, IDPTBL, IDPTSZ, IDCTBL, IDASFS
      COMMON /G01OPC/ IDESC,  IDMESS, IDAPLD, IDBKGC, IDDSCR, IDFLST
      COMMON /G01OPC/ CLDELM, CLMDES, CLPDES, CLCNTL, CLPRIM, CLPRAT
      COMMON /G01OPC/ CLESCE, CLEXTE
C
C  Parameter data types.
C
      INTEGER         IDNOOP, IDBEGM, IDENDM, IDBEGP, IDBGPB, IDENDP
      INTEGER         IDMVER, IDMELT, IDDREP, IDCSEL, IDVEXT, IDVINT
      INTEGER         IDCREC, IDCLIN, IDPLIN, IDPMRK, IDTEXT, IDPGON
      INTEGER         IDCARY, IDGDP,  IDLBIX, IDLTYP, IDLWID, IDLCLR
      INTEGER         IDMBIX, IDMTYP, IDMSIZ, IDMCLR, IDTBIX, IDTFON
      INTEGER         IDTPRE, IDCHEX, IDCHSP, IDTCLR, IDCHHT, IDCHOR
      INTEGER         IDTXPA, IDTXAL, IDFBIX, IDINTS, IDFCLR, IDHAIX
      INTEGER         IDPTIX, IDFRPT, IDPTBL, IDPTSZ, IDCTBL, IDASFS
      INTEGER         IDESC,  IDMESS, IDAPLD, IDBKGC, IDDSCR, IDFLST
      INTEGER         CLDELM, CLMDES, CLPDES, CLCNTL, CLPRIM, CLPRAT
      INTEGER         CLESCE, CLEXTE
C
C Class code parameters for every element.
C
      INTEGER         CLNOOP, CLBEGM, CLENDM, CLBEGP, CLBGPB, CLENDP
      INTEGER         CLMVER, CLMELT, CLDREP, CLCSEL, CLVEXT, CLVINT
      INTEGER         CLCREC, CLCLIN, CLPLIN, CLPMRK, CLTEXT, CLPGON
      INTEGER         CLCARY, CLGDP,  CLLBIX, CLLTYP, CLLWID, CLLCLR
      INTEGER         CLMBIX, CLMTYP, CLMSIZ, CLMCLR, CLTBIX, CLTFON
      INTEGER         CLTPRE, CLCHEX, CLCHSP, CLTCLR, CLCHHT, CLCHOR
      INTEGER         CLTXPA, CLTXAL, CLFBIX, CLINTS, CLFCLR, CLHAIX
      INTEGER         CLPTIX, CLFRPT, CLPTBL, CLPTSZ, CLCTBL, CLASFS
      INTEGER         CLESC,  CLMESS, CLAPLD, CLBKGC, CLDSCR, CLFLST
C
C  Equivalence all individual class code parameters to the single
C  code for the class in which the element(s) belong.
C
      EQUIVALENCE (CLDELM, CLNOOP,CLBEGM,CLENDM,CLBEGP,CLBGPB,CLENDP)
      EQUIVALENCE (CLMDES, CLMVER,CLMELT,CLDREP,CLDSCR,CLFLST)
      EQUIVALENCE (CLPDES, CLCSEL,CLVEXT,CLBKGC)
      EQUIVALENCE (CLCNTL, CLVINT,CLCREC,CLCLIN)
      EQUIVALENCE (CLPRIM, CLPLIN,CLPMRK,CLTEXT,CLPGON,CLCARY,CLGDP)
      EQUIVALENCE (CLPRAT, CLLBIX,CLLTYP,CLLWID,CLLCLR,CLMBIX,CLMTYP)
      EQUIVALENCE (CLPRAT, CLMSIZ,CLMCLR,CLTBIX,CLTFON,CLTPRE,CLCHEX)
      EQUIVALENCE (CLPRAT, CLCHSP,CLTCLR,CLCHHT,CLCHOR,CLTXPA,CLTXAL)
      EQUIVALENCE (CLPRAT, CLFBIX,CLINTS,CLFCLR,CLHAIX,CLPTIX,CLFRPT)
      EQUIVALENCE (CLPRAT, CLPTBL,CLPTSZ,CLCTBL,CLASFS)
      EQUIVALENCE (CLESCE, CLESC), (CLEXTE, CLMESS,CLAPLD)
      COMMON  /G01INS/  MCODES  ,MCONTS ,
     +                  MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW ,
     +                  MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL ,
     +                  MINXVD  ,MAXXVD ,MINYVD ,MAXYVD ,
     +                  MCFRM   ,MCOPCL ,MCOPID ,MCNBYT ,
     +                  MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG ,
     +                  MBCCHG
        INTEGER         MCODES  ,MCONTS
        INTEGER         MVDCFW  ,MCIXFW ,MDCCFW ,MIXFW  ,MINTFW
        INTEGER         MDCCRG  ,MXOFF  ,MXSCAL ,MYOFF  ,MYSCAL
        INTEGER         MINXVD  ,MAXXVD ,MINYVD ,MAXYVD
        INTEGER         MCFRM   ,MCOPCL ,MCOPID ,MCNBYT
        INTEGER         MCCBYT  ,MCFPP  ,MSLFMT ,MEFW   ,MCTCHG
        INTEGER         MBCCHG
C
      INTEGER  NBYTES, DRSET(2)
      INTEGER  G01PBL
C
C     CLASS AND ID FOR DRAWING-SET AND CONTROL SET PSEUDO OP.
      DATA  DRSET /-1, 1/
C
      ERROR = 0
C
C  PUT OUT VERSION NUMBER ELEMENT.
C
      NBYTES = 1 + (MINTFW-1)/8
      CALL GPUTNI (CLMVER, IDMVER, NBYTES, ERROR)
      CALL GPUTPR (MVERSN, MINTFW, 1, ERROR)
      IF (ERROR.NE.0)  RETURN
C
C  PUT OUT METAFILE DESCRIPTION.
C
      NBYTES = G01PBL(24,0)
      CALL GPUTNI (CLDSCR, IDDSCR, NBYTES, ERROR)
      CALL GPUTPS ('NCAR_GKS0A--VERSION_3.01', 24, 24, 0, ERROR)
      IF (ERROR.NE.0)  RETURN
C
C  PUT OUT METAFILE ELEMENTS LIST, DRAWING-SET PSEUDO OP.
C
      NBYTES = 1 + (MINTFW + 2*MIXFW - 1)/8
      CALL GPUTNI (CLMELT, IDMELT, NBYTES, ERROR)
      CALL GPUTPR (1, MINTFW, 1, ERROR)
      CALL GPUTPR (DRSET, MIXFW, 2, ERROR)
C
C  PUT OUT MAXIMUM COLOR INDEX.
C
      NBYTES = 1 + (MCIXFW-1)/8
      ICLTMP = 1
      IELTMP = 9
      CALL GPUTNI (ICLTMP,IELTMP,NBYTES,ERROR)
      IMXTMP = 255
      CALL GPUTPR (IMXTMP,MCIXFW,1,ERROR)
C
C  PUT OUT FONT LIST.  THERE ARE 20 FONTS.
C
      NBYTES = 20 + ( 7+26+26+21+21+22+21+21+22+22+24+20+21+22+21+
     -               22+22+20+19+19)
      CALL GPUTNI(CLFLST,IDFLST,NBYTES,ERROR)
      CALL GPUTPS('DEFAULT'                   , 7, 7,0,ERROR)
      CALL GPUTPS('HERSHEY:CARTOGRAPHIC_ROMAN',26,26,0,ERROR)
      CALL GPUTPS('HERSHEY:CARTOGRAPHIC_GREEK',26,26,0,ERROR)
      CALL GPUTPS('HERSHEY:SIMPLEX_ROMAN'     ,21,21,0,ERROR)
      CALL GPUTPS('HERSHEY:SIMPLEX_GREEK'     ,21,21,0,ERROR)
      CALL GPUTPS('HERSHEY:SIMPLEX_SCRIPT'    ,22,22,0,ERROR)
      CALL GPUTPS('HERSHEY:COMPLEX_ROMAN'     ,21,21,0,ERROR)
      CALL GPUTPS('HERSHEY:COMPLEX_GREEK'     ,21,21,0,ERROR)
      CALL GPUTPS('HERSHEY:COMPLEX_SCRIPT'    ,22,22,0,ERROR)
      CALL GPUTPS('HERSHEY:COMPLEX_ITALIC'    ,22,22,0,ERROR)
      CALL GPUTPS('HERSHEY:COMPLEX_CYRILLIC'  ,24,24,0,ERROR)
      CALL GPUTPS('HERSHEY:DUPLEX_ROMAN'      ,20,20,0,ERROR)
      CALL GPUTPS('HERSHEY:TRIPLEX_ROMAN'     ,21,21,0,ERROR)
      CALL GPUTPS('HERSHEY:TRIPLEX_ITALIC'    ,22,22,0,ERROR)
      CALL GPUTPS('HERSHEY:GOTHIC_GERMAN'     ,21,21,0,ERROR)
      CALL GPUTPS('HERSHEY:GOTHIC_ENGLISH'    ,22,22,0,ERROR)
      CALL GPUTPS('HERSHEY:GOTHIC_ITALIAN'    ,22,22,0,ERROR)
      CALL GPUTPS('HERSHEY:MATH_SYMBOLS'      ,20,20,0,ERROR)
      CALL GPUTPS('HERSHEY:SYMBOL_SET1'       ,19,19,0,ERROR)
      CALL GPUTPS('HERSHEY:SYMBOL_SET2'       ,19,19,0,ERROR)
      RETURN
      END
