C
C	$Id: reset.f,v 1.1.1.1 1992-04-17 22:34:57 ncargd Exp $
C
      SUBROUTINE RESET
C
C USER ENTRY POINT.
C RESET INITIALIZES ALL POINTS IN THE MODEL PICTURE TO UNMARKED.
C
      LOGICAL LDUMMY
      SAVE
C
      CALL REMOVE (0,0,LDUMMY,1)
      RETURN
      END
