C
C $Id: e4fnz0.f,v 1.1 1999-04-02 23:05:49 kennison Exp $
C
      DOUBLE PRECISION FUNCTION E4FNZ0 (ECCENT)
C
C FUNCTION TO COMPUTE CONSTANT (E4).
C
      IMPLICIT DOUBLE PRECISION (A-Z)
      DATA ONE /1.0D0/
C
      CON = ONE + ECCENT
      COM = ONE - ECCENT
      E4FNZ0 = SQRT ((CON ** CON) * (COM ** COM))
C
      RETURN
      END
