C
C $Id: msfnz0.f,v 1.1 1999-04-02 23:05:52 kennison Exp $
C
      DOUBLE PRECISION FUNCTION MSFNZ0 (ECCENT,SINPHI,COSPHI)
C
C FUNCTION TO COMPUTE CONSTANT (SMALL M).
C
      IMPLICIT DOUBLE PRECISION (A-Z)
      DATA ONE /1.0D0/
C
      CON = ECCENT * SINPHI
      MSFNZ0 = COSPHI / SQRT (ONE - CON * CON)
C
      RETURN
      END
