C
C $Id: tsfnsp.f,v 1.1 1999-04-19 22:10:42 kennison Exp $
C
      REAL FUNCTION TSFNSP (ECCENT,PHI,SINPHI)
C
C FUNCTION TO COMPUTE CONSTANT (SMALL T).
C
      IMPLICIT REAL (A-Z)
      DATA HALF,ONE /0.5E0,1.0E0/
      DATA HALFPI /1.5707963267948966E0/
C
      CON = ECCENT * SINPHI
      COM = HALF * ECCENT
      CON = ((ONE - CON) / (ONE + CON)) ** COM
      TSFNSP = TAN (HALF * (HALFPI - PHI)) / CON
C
      RETURN
      END
