C
C	$Id: cpgetr.f,v 1.1.1.1 1992-04-17 22:32:44 ncargd Exp $
C
C
C-----------------------------------------------------------------------
C
      SUBROUTINE CPGETR (WHCH,RVAL)
C
      CHARACTER*(*) WHCH
C
C This subroutine is called to retrieve the real value of a specified
C parameter.
C
C WHCH is the name of the parameter whose value is to be retrieved.
C
C RVAL is a real variable in which the desired value is to be returned
C by CPGETR.
C
C
C Declare all of the CONPACK common blocks.
C
C
C CPCOM1 contains integer and real variables.
C
      COMMON /CPCOM1/ ANCF,ANHL,ANIL,ANLL,CDMX,CHWM,CINS,CINT(10)
      COMMON /CPCOM1/ CINU,CLDB(256),CLDL(256),CLDR(256)
      COMMON /CPCOM1/ CLDT(256),CLEV(256),CLWA(259),CXCF
      COMMON /CPCOM1/ CXIL,CYCF,CYIL,DBLF,DBLM,DBLN,DBLV,DFLD,DOPT
      COMMON /CPCOM1/ EPSI,FNCM,GRAV,GRSD,GSDM,HCHL,HCHS,IAIA(259)
      COMMON /CPCOM1/ IAIB(256),IBCF,IBHL,IBIL,IBLL,ICAF,ICCF
      COMMON /CPCOM1/ ICCL(259),ICFF,ICHI,ICHL,ICIL,ICLL(256)
      COMMON /CPCOM1/ ICLO,ICLP(256),ICLS,ICLU(259),ICLV,ICLW
      COMMON /CPCOM1/ IDUF,IGCL,IGLB,IGRM,IGRN,IGVS,IHCF,IHLX,IHLY
      COMMON /CPCOM1/ IIWS(2),IIWU,ILBC,IMPF,INCX(8),INCY(8)
      COMMON /CPCOM1/ INHL,INIL,INIT,INLL,IOCF,IOHL,IOLL,IPAI,IPCF
      COMMON /CPCOM1/ IPIC,IPIE,IPIL,IPLL,IRWS(4),IRWU,ISET,IWSO
      COMMON /CPCOM1/ IZD1,IZDM,IZDN,IZDS,JODP,JOMA,JOTZ,LCTM,LEA1
      COMMON /CPCOM1/ LEA2,LEA3,LEE1,LEE2,LEE3,LINS,LINT(10),LINU
      COMMON /CPCOM1/ LIWK,LIWM,LIWS(2),LNLG,LRWC,LRWG,LRWK
      COMMON /CPCOM1/ LRWM,LRWS(4),LSDD,LSDL,LSDM,LTCF,LTHI
      COMMON /CPCOM1/ LTIL,LTLO,MIRO,NCLB(256),NCLV,NDGL,NEXL
      COMMON /CPCOM1/ NEXT,NEXU,NLBS,NLSD,NLZF,NOMF,NOVS,NR04,NSDL
      COMMON /CPCOM1/ NSDR,OORV,SCFS,SCFU,SEGL,SVAL,T2DS,T3DS,UCMN
      COMMON /CPCOM1/ UCMX,UVPB,UVPL,UVPR,UVPS,UVPT,UWDB,UWDL,UWDR
      COMMON /CPCOM1/ UWDT,UXA1,UXAM,UYA1,UYAN,WCCF,WCHL,WCIL,WCLL
      COMMON /CPCOM1/ WLCF,WLHL,WLIL,WLLL,WOCH,WODA,WTCD,WTGR,WTNC
      COMMON /CPCOM1/ WTOD,WWCF,WWHL,WWIL,WWLL,XAT1,XATM,XLBC,XVPL
      COMMON /CPCOM1/ XVPR,XWDL,XWDR,YAT1,YATN,YLBC,YVPB,YVPT,YWDB
      COMMON /CPCOM1/ YWDT,ZDVL,ZMAX,ZMIN
      EQUIVALENCE (IIWS(1),II01),(LIWS(1),LI01)
      EQUIVALENCE (IIWS(2),II02),(LIWS(2),LI02)
      EQUIVALENCE (IRWS(1),IR01),(LRWS(1),LR01)
      EQUIVALENCE (IRWS(2),IR02),(LRWS(2),LR02)
      EQUIVALENCE (IRWS(3),IR03),(LRWS(3),LR03)
      EQUIVALENCE (IRWS(4),IR04),(LRWS(4),LR04)
      SAVE   /CPCOM1/
C
C CPCOM2 holds character parameters.
C
      COMMON /CPCOM2/ CHEX,CLBL(256),CLDP(259),CTMA,CTMB,FRMT
      COMMON /CPCOM2/ TXCF,TXHI,TXIL,TXLO
      CHARACTER*13 CHEX
      CHARACTER*40 CLBL
      CHARACTER*32 CLDP
      CHARACTER*500 CTMA,CTMB
      CHARACTER*8 FRMT
      CHARACTER*40 TXCF
      CHARACTER*20 TXHI
      CHARACTER*100 TXIL
      CHARACTER*20 TXLO
      SAVE   /CPCOM2/
C
C Check for a parameter name that is too short.
C
      IF (LEN(WHCH).LT.3) THEN
        CTMB(1:46)='CPGETI OR CPGETR - PARAMETER NAME TOO SHORT - '
        CTMB(47:46+LEN(WHCH))=WHCH
        CALL SETER (CTMB(1:46+LEN(WHCH)),1,2)
        STOP
      END IF
C
C Check for incorrect use of the index parameter.
C
      IF (WHCH(1:3).EQ.'AIA'.OR.WHCH(1:3).EQ.'CLC'.OR.WHCH(1:3).EQ.'CLL'
     +.OR.WHCH(1:3).EQ.'CLU') THEN
        IF (IPAI.GE.1.AND.IPAI.LE.NCLV) THEN
          JPAI=IPAI
        ELSE IF (IPAI.LE.-1.AND.IPAI.GE.-3) THEN
          JPAI=256+ABS(IPAI)
        ELSE
          GO TO 10002
        END IF
      ELSE IF ((WHCH(1:3).EQ.'AIB'.OR.WHCH(1:3).EQ.'CLV'.OR.WHCH(1:3).EQ
     +.'LLC').AND.(IPAI.LT.1.OR.IPAI.GT.NCLV)) THEN
        GO TO 10002
      ELSE IF ((WHCH(1:3).EQ.'CIT'.OR.WHCH(1:3).EQ.'LIT').AND.(IPAI.LT.1
     +.OR.IPAI.GT.10)) THEN
        GO TO 10002
      END IF
C
      GO TO 10005
10002 CONTINUE
        CTMB(1:46)='CPGETI OR CPGETR - GETTING XXX - PAI INCORRECT'
        CTMB(28:30)=WHCH(1:3)
        CALL SETER (CTMB(1:46),2,2)
        STOP
10005 CONTINUE
C
C Get the appropriate parameter value.
C
      IF (WHCH(1:3).EQ.'AIA') THEN
        RVAL=REAL(IAIA(JPAI))
      ELSE IF (WHCH(1:3).EQ.'AIB') THEN
        RVAL=REAL(IAIB(IPAI))
      ELSE IF (WHCH(1:3).EQ.'CAF') THEN
        RVAL=REAL(ICAF)
      ELSE IF (WHCH(1:3).EQ.'CFA') THEN
        RVAL=ANCF
      ELSE IF (WHCH(1:3).EQ.'CFB') THEN
        RVAL=REAL(IBCF)
      ELSE IF (WHCH(1:3).EQ.'CFC') THEN
        RVAL=REAL(ICCF)
      ELSE IF (WHCH(1:3).EQ.'CFF') THEN
        RVAL=ICFF
      ELSE IF (WHCH(1:3).EQ.'CFL') THEN
        RVAL=WLCF
      ELSE IF (WHCH(1:3).EQ.'CFP') THEN
        RVAL=REAL(IPCF)
      ELSE IF (WHCH(1:3).EQ.'CFS') THEN
        RVAL=WCCF
      ELSE IF (WHCH(1:3).EQ.'CFW') THEN
        RVAL=WWCF
      ELSE IF (WHCH(1:3).EQ.'CFX') THEN
        RVAL=CXCF
      ELSE IF (WHCH(1:3).EQ.'CFY') THEN
        RVAL=CYCF
      ELSE IF (WHCH(1:3).EQ.'CIS') THEN
        RVAL=CINS
      ELSE IF (WHCH(1:3).EQ.'CIT') THEN
        RVAL=CINT(IPAI)
      ELSE IF (WHCH(1:3).EQ.'CIU') THEN
        RVAL=CINU
      ELSE IF (WHCH(1:3).EQ.'CLC') THEN
        RVAL=REAL(ICCL(JPAI))
      ELSE IF (WHCH(1:3).EQ.'CLL') THEN
        RVAL=CLWA(JPAI)
      ELSE IF (WHCH(1:3).EQ.'CLS') THEN
        RVAL=REAL(ICLS)
      ELSE IF (WHCH(1:3).EQ.'CLU') THEN
        RVAL=REAL(ICLU(JPAI))
      ELSE IF (WHCH(1:3).EQ.'CLV') THEN
        RVAL=CLEV(IPAI)
      ELSE IF (WHCH(1:3).EQ.'CMN') THEN
        RVAL=UCMN
      ELSE IF (WHCH(1:3).EQ.'CMX') THEN
        RVAL=UCMX
      ELSE IF (WHCH(1:3).EQ.'CWM') THEN
        RVAL=CHWM
      ELSE IF (WHCH(1:3).EQ.'DPS') THEN
        RVAL=WOCH
      ELSE IF (WHCH(1:3).EQ.'DPU') THEN
        RVAL=REAL(IDUF)
      ELSE IF (WHCH(1:3).EQ.'DPV') THEN
        RVAL=WODA
      ELSE IF (WHCH(1:3).EQ.'GIC') THEN
        RVAL=REAL(IGCL)
      ELSE IF (WHCH(1:3).EQ.'GIL') THEN
        RVAL=REAL(IGLB)
      ELSE IF (WHCH(1:3).EQ.'GIS') THEN
        RVAL=REAL(IGVS)
      ELSE IF (WHCH(1:3).EQ.'HCF') THEN
        RVAL=REAL(IHCF)
      ELSE IF (WHCH(1:3).EQ.'HCL') THEN
        RVAL=HCHL
      ELSE IF (WHCH(1:3).EQ.'HCS') THEN
        RVAL=HCHS
      ELSE IF (WHCH(1:3).EQ.'HIC') THEN
        RVAL=REAL(ICHI)
      ELSE IF (WHCH(1:3).EQ.'HLA') THEN
        RVAL=ANHL
      ELSE IF (WHCH(1:3).EQ.'HLB') THEN
        RVAL=REAL(IBHL)
      ELSE IF (WHCH(1:3).EQ.'HLC') THEN
        RVAL=REAL(ICHL)
      ELSE IF (WHCH(1:3).EQ.'HLL') THEN
        RVAL=WLHL
      ELSE IF (WHCH(1:3).EQ.'HLO') THEN
        RVAL=REAL(IOHL)
      ELSE IF (WHCH(1:3).EQ.'HLS') THEN
        RVAL=WCHL
      ELSE IF (WHCH(1:3).EQ.'HLW') THEN
        RVAL=WWHL
      ELSE IF (WHCH(1:3).EQ.'HLX') THEN
        RVAL=REAL(IHLX)
      ELSE IF (WHCH(1:3).EQ.'HLY') THEN
        RVAL=REAL(IHLY)
      ELSE IF (WHCH(1:3).EQ.'ILA') THEN
        RVAL=ANIL
      ELSE IF (WHCH(1:3).EQ.'ILB') THEN
        RVAL=REAL(IBIL)
      ELSE IF (WHCH(1:3).EQ.'ILC') THEN
        RVAL=REAL(ICIL)
      ELSE IF (WHCH(1:3).EQ.'ILL') THEN
        RVAL=WLIL
      ELSE IF (WHCH(1:3).EQ.'ILP') THEN
        RVAL=REAL(IPIL)
      ELSE IF (WHCH(1:3).EQ.'ILS') THEN
        RVAL=WCIL
      ELSE IF (WHCH(1:3).EQ.'ILW') THEN
        RVAL=WWIL
      ELSE IF (WHCH(1:3).EQ.'ILX') THEN
        RVAL=CXIL
      ELSE IF (WHCH(1:3).EQ.'ILY') THEN
        RVAL=CYIL
      ELSE IF (WHCH(1:3).EQ.'IWM') THEN
        RVAL=REAL(LIWM)
      ELSE IF (WHCH(1:3).EQ.'IWU') THEN
        RVAL=REAL(IIWU)
      ELSE IF (WHCH(1:3).EQ.'LBC') THEN
        RVAL=REAL(ILBC)
      ELSE IF (WHCH(1:3).EQ.'LBX') THEN
        RVAL=XLBC
      ELSE IF (WHCH(1:3).EQ.'LBY') THEN
        RVAL=YLBC
      ELSE IF (WHCH(1:3).EQ.'LIS') THEN
        RVAL=REAL(LINS)
      ELSE IF (WHCH(1:3).EQ.'LIT') THEN
        RVAL=REAL(LINT(IPAI))
      ELSE IF (WHCH(1:3).EQ.'LIU') THEN
        RVAL=REAL(LINU)
      ELSE IF (WHCH(1:3).EQ.'LLA') THEN
        RVAL=ANLL
      ELSE IF (WHCH(1:3).EQ.'LLB') THEN
        RVAL=REAL(IBLL)
      ELSE IF (WHCH(1:3).EQ.'LLC') THEN
        RVAL=REAL(ICLL(IPAI))
      ELSE IF (WHCH(1:3).EQ.'LLL') THEN
        RVAL=WLLL
      ELSE IF (WHCH(1:3).EQ.'LLO') THEN
        RVAL=REAL(IOLL)
      ELSE IF (WHCH(1:3).EQ.'LLP') THEN
        RVAL=REAL(IPLL)
      ELSE IF (WHCH(1:3).EQ.'LLS') THEN
        RVAL=WCLL
      ELSE IF (WHCH(1:3).EQ.'LLW') THEN
        RVAL=WWLL
      ELSE IF (WHCH(1:3).EQ.'LOC') THEN
        RVAL=REAL(ICLO)
      ELSE IF (WHCH(1:3).EQ.'MAP') THEN
        RVAL=REAL(IMPF)
      ELSE IF (WHCH(1:3).EQ.'NCL') THEN
        RVAL=REAL(NCLV)
      ELSE IF (WHCH(1:3).EQ.'NEL') THEN
        RVAL=REAL(NEXL)
      ELSE IF (WHCH(1:3).EQ.'NET') THEN
        RVAL=REAL(NEXT)
      ELSE IF (WHCH(1:3).EQ.'NEU') THEN
        RVAL=REAL(NEXU)
      ELSE IF (WHCH(1:3).EQ.'NLS') THEN
        RVAL=REAL(NLSD)
      ELSE IF (WHCH(1:3).EQ.'NLZ') THEN
        RVAL=REAL(NLZF)
      ELSE IF (WHCH(1:3).EQ.'NOF') THEN
        RVAL=REAL(NOMF)
      ELSE IF (WHCH(1:3).EQ.'NSD') THEN
        RVAL=REAL(NSDL)
      ELSE IF (WHCH(1:3).EQ.'NVS') THEN
        RVAL=REAL(NOVS)
      ELSE IF (WHCH(1:3).EQ.'ORV') THEN
        RVAL=OORV
      ELSE IF (WHCH(1:3).EQ.'PAI') THEN
        RVAL=REAL(IPAI)
      ELSE IF (WHCH(1:3).EQ.'PC1') THEN
        RVAL=GSDM
      ELSE IF (WHCH(1:3).EQ.'PC2') THEN
        RVAL=FNCM
      ELSE IF (WHCH(1:3).EQ.'PC3') THEN
        RVAL=CDMX
      ELSE IF (WHCH(1:3).EQ.'PC4') THEN
        RVAL=DOPT
      ELSE IF (WHCH(1:3).EQ.'PC5') THEN
        RVAL=DFLD
      ELSE IF (WHCH(1:3).EQ.'PC6') THEN
        RVAL=DBLM
      ELSE IF (WHCH(1:3).EQ.'PIC') THEN
        RVAL=REAL(IPIC)
      ELSE IF (WHCH(1:3).EQ.'PIE') THEN
        RVAL=REAL(IPIE)
      ELSE IF (WHCH(1:3).EQ.'PW1') THEN
        RVAL=WTGR
      ELSE IF (WHCH(1:3).EQ.'PW2') THEN
        RVAL=WTNC
      ELSE IF (WHCH(1:3).EQ.'PW3') THEN
        RVAL=WTCD
      ELSE IF (WHCH(1:3).EQ.'PW4') THEN
        RVAL=WTOD
      ELSE IF (WHCH(1:3).EQ.'RC1') THEN
        RVAL=DBLF
      ELSE IF (WHCH(1:3).EQ.'RC2') THEN
        RVAL=DBLN
      ELSE IF (WHCH(1:3).EQ.'RC3') THEN
        RVAL=DBLV
      ELSE IF (WHCH(1:3).EQ.'RWC') THEN
        RVAL=REAL(LRWC)
      ELSE IF (WHCH(1:3).EQ.'RWG') THEN
        RVAL=REAL(LRWG)
      ELSE IF (WHCH(1:3).EQ.'RWM') THEN
        RVAL=REAL(LRWM)
      ELSE IF (WHCH(1:3).EQ.'RWU') THEN
        RVAL=REAL(IRWU)
      ELSE IF (WHCH(1:3).EQ.'SET') THEN
        RVAL=REAL(ISET)
      ELSE IF (WHCH(1:3).EQ.'SFS') THEN
        RVAL=SCFS
      ELSE IF (WHCH(1:3).EQ.'SFU') THEN
        RVAL=SCFU
      ELSE IF (WHCH(1:3).EQ.'SPV') THEN
        RVAL=SVAL
      ELSE IF (WHCH(1:3).EQ.'SSL') THEN
        RVAL=SEGL
      ELSE IF (WHCH(1:3).EQ.'T2D') THEN
        RVAL=T2DS
      ELSE IF (WHCH(1:3).EQ.'T3D') THEN
        RVAL=T3DS
      ELSE IF (WHCH(1:3).EQ.'VPB') THEN
        RVAL=UVPB
      ELSE IF (WHCH(1:3).EQ.'VPL') THEN
        RVAL=UVPL
      ELSE IF (WHCH(1:3).EQ.'VPR') THEN
        RVAL=UVPR
      ELSE IF (WHCH(1:3).EQ.'VPS') THEN
        RVAL=UVPS
      ELSE IF (WHCH(1:3).EQ.'VPT') THEN
        RVAL=UVPT
      ELSE IF (WHCH(1:3).EQ.'WDB') THEN
        RVAL=UWDB
      ELSE IF (WHCH(1:3).EQ.'WDL') THEN
        RVAL=UWDL
      ELSE IF (WHCH(1:3).EQ.'WDR') THEN
        RVAL=UWDR
      ELSE IF (WHCH(1:3).EQ.'WDT') THEN
        RVAL=UWDT
      ELSE IF (WHCH(1:3).EQ.'WSO') THEN
        RVAL=REAL(IWSO)
      ELSE IF (WHCH(1:3).EQ.'XC1') THEN
        RVAL=UXA1
      ELSE IF (WHCH(1:3).EQ.'XCM') THEN
        RVAL=UXAM
      ELSE IF (WHCH(1:3).EQ.'YC1') THEN
        RVAL=UYA1
      ELSE IF (WHCH(1:3).EQ.'YCN') THEN
        RVAL=UYAN
      ELSE IF (WHCH(1:3).EQ.'ZD1') THEN
        RVAL=REAL(IZD1)
      ELSE IF (WHCH(1:3).EQ.'ZDM') THEN
        RVAL=REAL(IZDM)
      ELSE IF (WHCH(1:3).EQ.'ZDN') THEN
        RVAL=REAL(IZDN)
      ELSE IF (WHCH(1:3).EQ.'ZDS') THEN
        RVAL=REAL(IZDS)
      ELSE IF (WHCH(1:3).EQ.'ZDV') THEN
        RVAL=ZDVL
      ELSE IF (WHCH(1:3).EQ.'ZMN') THEN
        RVAL=ZMIN
      ELSE IF (WHCH(1:3).EQ.'ZMX') THEN
        RVAL=ZMAX
      ELSE
        CTMB(1:46)='CPGETI OR CPGETR - PARAMETER NAME NOT KNOWN - '
        CTMB(47:49)=WHCH(1:3)
        CALL SETER (CTMB(1:49),3,2)
        STOP
      END IF
C
C Done.
C
      RETURN
C
      END
