C
C $Id: cpinlb.f,v 1.7 1996-02-29 17:44:13 kennison Exp $
C
      SUBROUTINE CPINLB (ZDAT,RWRK,IWRK)
C
      DIMENSION ZDAT(IZD1,*),RWRK(*),IWRK(*)
C
C CPINLB generates the informational label; the quantities defining the
C label are added to the lists in real workspaces 3 and 4.
C
C
C Declare all of the CONPACK common blocks.
C
C
C CPCOM1 contains integer and real variables.
C
      COMMON /CPCOM1/ ANCF,ANHL,ANIL,ANLL,CDMX,CHWM,CINS,CINT(10)
      COMMON /CPCOM1/ CINU,CLDB(256),CLDL(256),CLDR(256)
      COMMON /CPCOM1/ CLDT(256),CLEV(256),CLWA(259),CXCF
      COMMON /CPCOM1/ CXIL,CYCF,CYIL,DBLF,DBLM,DBLN,DBLV,DFLD,DOPT
      COMMON /CPCOM1/ EPSI,FNCM,GRAV,GRSD,GSDM,HCHL,HCHS,IAIA(259)
      COMMON /CPCOM1/ IAIB(256),IBCF,IBHL,IBIL,IBLL,ICAF,ICCF
      COMMON /CPCOM1/ ICCL(259),ICFF,ICHI,ICHL,ICIL,ICLL(256)
      COMMON /CPCOM1/ ICLO,ICLP(256),ICLS,ICLU(259),ICLV,ICLW
      COMMON /CPCOM1/ IDUF,IGCL,IGLB,IGRM,IGRN,IGVS,IHCF,IHLX,IHLY
      COMMON /CPCOM1/ IIWS(2),IIWU,ILBC,IMPF,INCX(8),INCY(8)
      COMMON /CPCOM1/ INHL,INIL,INIT,INLL,IOCF,IOHL,IOLL,IPAI,IPCF
      COMMON /CPCOM1/ IPIC,IPIE,IPIL,IPLL,IRWS(4),IRWU,ISET,IWSO
      COMMON /CPCOM1/ IZD1,IZDM,IZDN,IZDS,JODP,JOMA,JOTZ,LCTM,LEA1
      COMMON /CPCOM1/ LEA2,LEA3,LEE1,LEE2,LEE3,LINS,LINT(10),LINU
      COMMON /CPCOM1/ LIWK,LIWM,LIWS(2),LNLG,LRWC,LRWG,LRWK
      COMMON /CPCOM1/ LRWM,LRWS(4),LSDD,LSDL,LSDM,LTCF,LTHI
      COMMON /CPCOM1/ LTIL,LTLO,MIRO,NCLB(256),NCLV,NDGL,NEXL
      COMMON /CPCOM1/ NEXT,NEXU,NLBS,NLSD,NLZF,NOMF,NOVS,NR04,NSDL
      COMMON /CPCOM1/ NSDR,OORV,PITH,SCFS,SCFU,SEGL,SVAL,T2DS,T3DS
      COMMON /CPCOM1/ UCMN,UCMX,UVPB,UVPL,UVPR,UVPS,UVPT,UWDB,UWDL
      COMMON /CPCOM1/ UWDR,UWDT,UXA1,UXAM,UYA1,UYAN,WCCF,WCHL,WCIL
      COMMON /CPCOM1/ WCLL,WLCF,WLHL,WLIL,WLLL,WOCH,WODA,WTCD,WTGR
      COMMON /CPCOM1/ WTNC,WTOD,WWCF,WWHL,WWIL,WWLL,XAT1,XATM,XLBC
      COMMON /CPCOM1/ XVPL,XVPR,XWDL,XWDR,YAT1,YATN,YLBC,YVPB,YVPT
      COMMON /CPCOM1/ YWDB,YWDT,ZDVL,ZMAX,ZMIN
      EQUIVALENCE (IIWS(1),II01),(LIWS(1),LI01)
      EQUIVALENCE (IIWS(2),II02),(LIWS(2),LI02)
      EQUIVALENCE (IRWS(1),IR01),(LRWS(1),LR01)
      EQUIVALENCE (IRWS(2),IR02),(LRWS(2),LR02)
      EQUIVALENCE (IRWS(3),IR03),(LRWS(3),LR03)
      EQUIVALENCE (IRWS(4),IR04),(LRWS(4),LR04)
      SAVE   /CPCOM1/
C
C CPCOM2 holds character parameters.
C
      COMMON /CPCOM2/ CHEX,CLBL(256),CLDP(259),CTMA,CTMB,FRMT
      COMMON /CPCOM2/ TXCF,TXHI,TXIL,TXLO
      CHARACTER*13 CHEX
      CHARACTER*64 CLBL
      CHARACTER*128 CLDP
      CHARACTER*500 CTMA,CTMB
      CHARACTER*8 FRMT
      CHARACTER*64 TXCF
      CHARACTER*32 TXHI
      CHARACTER*128 TXIL
      CHARACTER*32 TXLO
      SAVE   /CPCOM2/
C
C If the text string for the informational label is blank, do nothing.
C
      IF (TXIL(1:LTIL).EQ.' ') RETURN
C
C Otherwise, form the informational label ...
C
      CALL CPSBST (TXIL(1:LTIL),CTMA,LCTM)
C
C ... get sizing information for the label ...
C
      XPFS=XVPL+CXIL*(XVPR-XVPL)
      YPFS=YVPB+CYIL*(YVPT-YVPB)
      XLBC=CFUX(XPFS)
      IF (ICFELL('CPINLB',1).NE.0) RETURN
      YLBC=CFUY(YPFS)
      IF (ICFELL('CPINLB',2).NE.0) RETURN
      WCFS=CHWM*WCIL*(XVPR-XVPL)
      WWFS=CHWM*WWIL*(XVPR-XVPL)
C
      CALL PCGETI ('TE',ITMP)
      IF (ICFELL('CPINLB',3).NE.0) RETURN
      CALL PCSETI ('TE',1)
      IF (ICFELL('CPINLB',4).NE.0) RETURN
      CALL HLUCPCHIL (+1)
      IF (ICFELL('CPINLB',5).NE.0) RETURN
      IF (CTMA(1:LCTM).EQ.' ') GO TO 101
      CALL PLCHHQ (XLBC,YLBC,CTMA(1:LCTM),WCFS,360.,0.)
      IF (ICFELL('CPINLB',6).NE.0) RETURN
      CALL HLUCPCHIL (-1)
      IF (ICFELL('CPINLB',7).NE.0) RETURN
      CALL PCGETR ('DL',DSTL)
      IF (ICFELL('CPINLB',8).NE.0) RETURN
      CALL PCGETR ('DR',DSTR)
      IF (ICFELL('CPINLB',9).NE.0) RETURN
      CALL PCGETR ('DB',DSTB)
      IF (ICFELL('CPINLB',10).NE.0) RETURN
      CALL PCGETR ('DT',DSTT)
      IF (ICFELL('CPINLB',11).NE.0) RETURN
      CALL PCSETI ('TE',ITMP)
      IF (ICFELL('CPINLB',12).NE.0) RETURN
      DSTL=DSTL+WWFS
      DSTR=DSTR+WWFS
      DSTB=DSTB+WWFS
      DSTT=DSTT+WWFS
C
C ... and then put information about the label into the lists.
C
      SINA=SIN(.017453292519943*ANIL)
      COSA=COS(.017453292519943*ANIL)
C
      IXPO=MOD(IPIL+4,3)-1
C
      IF (IXPO.LT.0) THEN
        XPFS=XPFS+DSTL*COSA
        YPFS=YPFS+DSTL*SINA
      ELSE IF (IXPO.GT.0) THEN
        XPFS=XPFS-DSTR*COSA
        YPFS=YPFS-DSTR*SINA
      END IF
C
      IYPO=(IPIL+4)/3-1
C
      IF (IYPO.LT.0) THEN
        XPFS=XPFS-DSTB*SINA
        YPFS=YPFS+DSTB*COSA
      ELSE IF (IYPO.GT.0) THEN
        XPFS=XPFS+DSTT*SINA
        YPFS=YPFS-DSTT*COSA
      END IF
C
      XLBC=CFUX(XPFS)
      IF (ICFELL('CPINLB',13).NE.0) RETURN
      YLBC=CFUY(YPFS)
      IF (ICFELL('CPINLB',14).NE.0) RETURN
C
      NLBS=NLBS+1
      IF (4*NLBS.GT.LR03) THEN
        CALL CPGRWS (RWRK,3,MAX(4*NLBS,LR03+100),IWSE)
        IF (IWSE.NE.0.OR.ICFELL('CPINLB',15).NE.0) THEN
          NLBS=NLBS-1
          RETURN
        END IF
      END IF
      RWRK(IR03+4*(NLBS-1)+1)=XPFS
      RWRK(IR03+4*(NLBS-1)+2)=YPFS
      RWRK(IR03+4*(NLBS-1)+3)=.017453292519943*ANIL
      RWRK(IR03+4*(NLBS-1)+4)=-NR04
      NR04=NR04+6
      IF (NR04.GT.LR04) THEN
        CALL CPGRWS (RWRK,4,MAX(NR04,LR04+100),IWSE)
        IF (IWSE.NE.0.OR.ICFELL('CPINLB',16).NE.0) THEN
          NLBS=NLBS-1
          RETURN
        END IF
      END IF
      RWRK(IR04+NR04-5)=0.
      RWRK(IR04+NR04-4)=0.
      RWRK(IR04+NR04-3)=DSTL
      RWRK(IR04+NR04-2)=DSTR
      RWRK(IR04+NR04-1)=DSTB
      RWRK(IR04+NR04  )=DSTT
C
C Done.
C
  101 RETURN
C
      END
