C
C	$Id: cpsetr.f,v 1.1.1.1 1992-04-17 22:32:46 ncargd Exp $
C
C
C-----------------------------------------------------------------------
C
      SUBROUTINE CPSETR (WHCH,RVAL)
C
      CHARACTER*(*) WHCH
C
C This subroutine is called to set the real value of a specified
C parameter.
C
C WHCH is the name of the parameter whose value is to be set.
C
C RVAL is a real variable containing the new value of the parameter.
C
C
C Declare all of the CONPACK common blocks.
C
C
C CPCOM1 contains integer and real variables.
C
      COMMON /CPCOM1/ ANCF,ANHL,ANIL,ANLL,CDMX,CHWM,CINS,CINT(10)
      COMMON /CPCOM1/ CINU,CLDB(256),CLDL(256),CLDR(256)
      COMMON /CPCOM1/ CLDT(256),CLEV(256),CLWA(259),CXCF
      COMMON /CPCOM1/ CXIL,CYCF,CYIL,DBLF,DBLM,DBLN,DBLV,DFLD,DOPT
      COMMON /CPCOM1/ EPSI,FNCM,GRAV,GRSD,GSDM,HCHL,HCHS,IAIA(259)
      COMMON /CPCOM1/ IAIB(256),IBCF,IBHL,IBIL,IBLL,ICAF,ICCF
      COMMON /CPCOM1/ ICCL(259),ICFF,ICHI,ICHL,ICIL,ICLL(256)
      COMMON /CPCOM1/ ICLO,ICLP(256),ICLS,ICLU(259),ICLV,ICLW
      COMMON /CPCOM1/ IDUF,IGCL,IGLB,IGRM,IGRN,IGVS,IHCF,IHLX,IHLY
      COMMON /CPCOM1/ IIWS(2),IIWU,ILBC,IMPF,INCX(8),INCY(8)
      COMMON /CPCOM1/ INHL,INIL,INIT,INLL,IOCF,IOHL,IOLL,IPAI,IPCF
      COMMON /CPCOM1/ IPIC,IPIE,IPIL,IPLL,IRWS(4),IRWU,ISET,IWSO
      COMMON /CPCOM1/ IZD1,IZDM,IZDN,IZDS,JODP,JOMA,JOTZ,LCTM,LEA1
      COMMON /CPCOM1/ LEA2,LEA3,LEE1,LEE2,LEE3,LINS,LINT(10),LINU
      COMMON /CPCOM1/ LIWK,LIWM,LIWS(2),LNLG,LRWC,LRWG,LRWK
      COMMON /CPCOM1/ LRWM,LRWS(4),LSDD,LSDL,LSDM,LTCF,LTHI
      COMMON /CPCOM1/ LTIL,LTLO,MIRO,NCLB(256),NCLV,NDGL,NEXL
      COMMON /CPCOM1/ NEXT,NEXU,NLBS,NLSD,NLZF,NOMF,NOVS,NR04,NSDL
      COMMON /CPCOM1/ NSDR,OORV,SCFS,SCFU,SEGL,SVAL,T2DS,T3DS,UCMN
      COMMON /CPCOM1/ UCMX,UVPB,UVPL,UVPR,UVPS,UVPT,UWDB,UWDL,UWDR
      COMMON /CPCOM1/ UWDT,UXA1,UXAM,UYA1,UYAN,WCCF,WCHL,WCIL,WCLL
      COMMON /CPCOM1/ WLCF,WLHL,WLIL,WLLL,WOCH,WODA,WTCD,WTGR,WTNC
      COMMON /CPCOM1/ WTOD,WWCF,WWHL,WWIL,WWLL,XAT1,XATM,XLBC,XVPL
      COMMON /CPCOM1/ XVPR,XWDL,XWDR,YAT1,YATN,YLBC,YVPB,YVPT,YWDB
      COMMON /CPCOM1/ YWDT,ZDVL,ZMAX,ZMIN
      EQUIVALENCE (IIWS(1),II01),(LIWS(1),LI01)
      EQUIVALENCE (IIWS(2),II02),(LIWS(2),LI02)
      EQUIVALENCE (IRWS(1),IR01),(LRWS(1),LR01)
      EQUIVALENCE (IRWS(2),IR02),(LRWS(2),LR02)
      EQUIVALENCE (IRWS(3),IR03),(LRWS(3),LR03)
      EQUIVALENCE (IRWS(4),IR04),(LRWS(4),LR04)
      SAVE   /CPCOM1/
C
C CPCOM2 holds character parameters.
C
      COMMON /CPCOM2/ CHEX,CLBL(256),CLDP(259),CTMA,CTMB,FRMT
      COMMON /CPCOM2/ TXCF,TXHI,TXIL,TXLO
      CHARACTER*13 CHEX
      CHARACTER*40 CLBL
      CHARACTER*32 CLDP
      CHARACTER*500 CTMA,CTMB
      CHARACTER*8 FRMT
      CHARACTER*40 TXCF
      CHARACTER*20 TXHI
      CHARACTER*100 TXIL
      CHARACTER*20 TXLO
      SAVE   /CPCOM2/
C
C Check for a parameter name that is too short.
C
      IF (LEN(WHCH).LT.3) THEN
        CTMB(1:46)='CPSETI OR CPSETR - PARAMETER NAME TOO SHORT - '
        CTMB(47:46+LEN(WHCH))=WHCH
        CALL SETER (CTMB(1:46+LEN(WHCH)),1,2)
        STOP
      END IF
C
C Check for incorrect use of the index parameter.
C
      IF (WHCH(1:3).EQ.'AIA'.OR.WHCH(1:3).EQ.'CLC'.OR.WHCH(1:3).EQ.'CLD'
     +.OR.WHCH(1:3).EQ.'CLL'.OR.WHCH(1:3).EQ.'CLU') THEN
        IF (IPAI.GE.1.AND.IPAI.LE.NCLV) THEN
          JPAI=IPAI
        ELSE IF (IPAI.LE.-1.AND.IPAI.GE.-3) THEN
          JPAI=256+ABS(IPAI)
        ELSE
          GO TO 10002
        END IF
      ELSE IF ((WHCH(1:3).EQ.'AIB'.OR.WHCH(1:3).EQ.'CLV'.OR.WHCH(1:3).EQ
     +.'LLC').AND.(IPAI.LT.1.OR.IPAI.GT.NCLV)) THEN
        GO TO 10002
      ELSE IF ((WHCH(1:3).EQ.'CIT'.OR.WHCH(1:3).EQ.'LIT').AND.(IPAI.LT.1
     +.OR.IPAI.GT.10)) THEN
        GO TO 10002
      END IF
C
      GO TO 10005
10002 CONTINUE
        CTMB(1:46)='CPSETI OR CPSETR - SETTING XXX - PAI INCORRECT'
        CTMB(28:30)=WHCH(1:3)
        CALL SETER (CTMB(1:46),2,2)
        STOP
10005 CONTINUE
C
C Set the appropriate parameter value.
C
      IF (WHCH(1:3).EQ.'AIA') THEN
        IAIA(JPAI)=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'AIB') THEN
        IAIB(IPAI)=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'CAF') THEN
        ICAF=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'CFA') THEN
        ANCF=RVAL
      ELSE IF (WHCH(1:3).EQ.'CFB') THEN
        IBCF=MAX(0,MIN(3,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'CFC') THEN
        ICCF=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'CFL') THEN
        WLCF=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'CFP') THEN
        IPCF=MAX(-4,MIN(4,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'CFS') THEN
        WCCF=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'CFW') THEN
        WWCF=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'CFX') THEN
        CXCF=RVAL
      ELSE IF (WHCH(1:3).EQ.'CFY') THEN
        CYCF=RVAL
      ELSE IF (WHCH(1:3).EQ.'CIS') THEN
        CINS=RVAL
      ELSE IF (WHCH(1:3).EQ.'CIT') THEN
        CINT(IPAI)=RVAL
      ELSE IF (WHCH(1:3).EQ.'CIU') THEN
        CINU=RVAL
      ELSE IF (WHCH(1:3).EQ.'CLC') THEN
        ICCL(JPAI)=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'CLD') THEN
        CLDP(JPAI)=' '
        ITMP=INT(RVAL)
        DO 10006 I=16,1,-1
          IF (IAND(ITMP,1).NE.0) THEN
            CLDP(JPAI)(I:I)='$'
          ELSE
            CLDP(JPAI)(I:I)=''''
          END IF
          ITMP=ISHIFT(ITMP,-1)
10006   CONTINUE
      ELSE IF (WHCH(1:3).EQ.'CLL') THEN
        CLWA(JPAI)=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'CLS') THEN
        ICLS=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'CLU') THEN
        ICLU(JPAI)=MAX(0,MIN(3,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'CLV') THEN
        CLEV(IPAI)=RVAL
        ICLU(IPAI)=1
        IAIA(IPAI)=IPAI+1
        IAIB(IPAI)=IPAI
        CLBL(IPAI)=' '
        NCLB(IPAI)=-1
        CLDP(IPAI)='$$$$$$$$$$$$$$$$'
        ICCL(IPAI)=-1
        ICLL(IPAI)=-1
        CLWA(IPAI)=0.
        IF (IPAI.EQ.1) CINU=0.
      ELSE IF (WHCH(1:3).EQ.'CMN') THEN
        UCMN=RVAL
      ELSE IF (WHCH(1:3).EQ.'CMX') THEN
        UCMX=RVAL
      ELSE IF (WHCH(1:3).EQ.'CWM') THEN
        CHWM=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'DPS') THEN
        WOCH=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'DPU') THEN
        IDUF=MAX(0,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'DPV') THEN
        WODA=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'GIC') THEN
        IGCL=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'GIL') THEN
        IGLB=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'GIS') THEN
        IGVS=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'HCF') THEN
        IHCF=MAX(-4,MIN(+4,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'HCL') THEN
        HCHL=RVAL
      ELSE IF (WHCH(1:3).EQ.'HCS') THEN
        HCHS=MAX(.0001,MIN(10.,RVAL))
      ELSE IF (WHCH(1:3).EQ.'HIC') THEN
        ICHI=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'HLA') THEN
        ANHL=RVAL
      ELSE IF (WHCH(1:3).EQ.'HLB') THEN
        IBHL=MAX(0,MIN(3,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'HLC') THEN
        ICHL=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'HLL') THEN
        WLHL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'HLO') THEN
        IOHL=MAX(0,MIN(15,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'HLS') THEN
        WCHL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'HLW') THEN
        WWHL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'HLX') THEN
        IHLX=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'HLY') THEN
        IHLY=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'ILA') THEN
        ANIL=RVAL
      ELSE IF (WHCH(1:3).EQ.'ILB') THEN
        IBIL=MAX(0,MIN(3,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'ILC') THEN
        ICIL=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'ILL') THEN
        WLIL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'ILP') THEN
        IPIL=MAX(-4,MIN(4,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'ILS') THEN
        WCIL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'ILW') THEN
        WWIL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'ILX') THEN
        CXIL=RVAL
      ELSE IF (WHCH(1:3).EQ.'ILY') THEN
        CYIL=RVAL
      ELSE IF (WHCH(1:3).EQ.'IWM') THEN
        LIWM=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'LBC') THEN
        ILBC=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'LIS') THEN
        LINS=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'LIT') THEN
        LINT(IPAI)=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'LLA') THEN
        ANLL=RVAL
      ELSE IF (WHCH(1:3).EQ.'LLB') THEN
        IBLL=MAX(0,MIN(3,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'LLC') THEN
        ICLL(IPAI)=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'LLL') THEN
        WLLL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'LLO') THEN
        IOLL=MAX(0,MIN(1,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'LLP') THEN
        IPLL=MAX(-3,MIN(3,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'LLS') THEN
        WCLL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'LLW') THEN
        WWLL=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'LOC') THEN
        ICLO=MAX(-1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'MAP') THEN
        IMPF=MAX(0,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'NCL') THEN
        NCLV=INT(RVAL)
        IF (NCLV.LT.1.OR.NCLV.GT.256) THEN
          CALL SETER ('CPSETI OR CPSETR - NCL LESS THAN 1 OR GREATER THA
     +N 256',3,2)
          STOP
        END IF
      ELSE IF (WHCH(1:3).EQ.'NEL') THEN
        NEXL=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'NET') THEN
        NEXT=MAX(0,MIN(2,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'NEU') THEN
        NEXU=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'NLS') THEN
        NLSD=MAX(0,MIN(1,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'NLZ') THEN
        NLZF=MAX(0,MIN(1,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'NOF') THEN
        NOMF=MAX(0,MIN(7,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'NSD') THEN
        NSDL=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'NVS') THEN
        NOVS=MAX(0,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'ORV') THEN
        OORV=RVAL
      ELSE IF (WHCH(1:3).EQ.'PAI') THEN
        IPAI=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'PC1') THEN
        GSDM=RVAL
      ELSE IF (WHCH(1:3).EQ.'PC2') THEN
        FNCM=RVAL
      ELSE IF (WHCH(1:3).EQ.'PC3') THEN
        CDMX=RVAL
      ELSE IF (WHCH(1:3).EQ.'PC4') THEN
        DOPT=RVAL
      ELSE IF (WHCH(1:3).EQ.'PC5') THEN
        DFLD=RVAL
      ELSE IF (WHCH(1:3).EQ.'PC6') THEN
        DBLM=RVAL
      ELSE IF (WHCH(1:3).EQ.'PIC') THEN
        IPIC=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'PIE') THEN
        IPIE=INT(RVAL)
      ELSE IF (WHCH(1:3).EQ.'PW1') THEN
        WTGR=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'PW2') THEN
        WTNC=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'PW3') THEN
        WTCD=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'PW4') THEN
        WTOD=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'RC1') THEN
        DBLF=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'RC2') THEN
        DBLN=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'RC3') THEN
        DBLV=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'RWC') THEN
        LRWC=MAX(5,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'RWG') THEN
        LRWG=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'RWM') THEN
        LRWM=MAX(2,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'SET') THEN
        ISET=MAX(0,MIN(1,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'SFS'.OR.WHCH(1:3).EQ.'SFU') THEN
        SCFS=RVAL
      ELSE IF (WHCH(1:3).EQ.'SPV') THEN
        SVAL=RVAL
      ELSE IF (WHCH(1:3).EQ.'SSL') THEN
        SEGL=MAX(.0001,RVAL)
      ELSE IF (WHCH(1:3).EQ.'T2D') THEN
        T2DS=RVAL
      ELSE IF (WHCH(1:3).EQ.'T3D') THEN
        T3DS=MAX(0.,RVAL)
      ELSE IF (WHCH(1:3).EQ.'VPB') THEN
        UVPB=MAX(0.,MIN(1.,RVAL))
      ELSE IF (WHCH(1:3).EQ.'VPL') THEN
        UVPL=MAX(0.,MIN(1.,RVAL))
      ELSE IF (WHCH(1:3).EQ.'VPR') THEN
        UVPR=MAX(0.,MIN(1.,RVAL))
      ELSE IF (WHCH(1:3).EQ.'VPS') THEN
        UVPS=RVAL
      ELSE IF (WHCH(1:3).EQ.'VPT') THEN
        UVPT=MAX(0.,MIN(1.,RVAL))
      ELSE IF (WHCH(1:3).EQ.'WDB') THEN
        UWDB=RVAL
      ELSE IF (WHCH(1:3).EQ.'WDL') THEN
        UWDL=RVAL
      ELSE IF (WHCH(1:3).EQ.'WDR') THEN
        UWDR=RVAL
      ELSE IF (WHCH(1:3).EQ.'WDT') THEN
        UWDT=RVAL
      ELSE IF (WHCH(1:3).EQ.'XC1') THEN
        UXA1=RVAL
      ELSE IF (WHCH(1:3).EQ.'XCM') THEN
        UXAM=RVAL
      ELSE IF (WHCH(1:3).EQ.'YC1') THEN
        UYA1=RVAL
      ELSE IF (WHCH(1:3).EQ.'YCN') THEN
        UYAN=RVAL
      ELSE IF (WHCH(1:3).EQ.'WSO') THEN
        IWSO=MAX(0,MIN(2,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'ZD1') THEN
        IZD1=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'ZDM') THEN
        IZDM=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'ZDN') THEN
        IZDN=MAX(1,INT(RVAL))
      ELSE IF (WHCH(1:3).EQ.'ZDS') THEN
        IZDS=MAX(0,MIN(1,INT(RVAL)))
      ELSE IF (WHCH(1:3).EQ.'ZDV') THEN
        ZDVL=RVAL
      ELSE
        CTMB(1:46)='CPSETI OR CPSETR - PARAMETER NAME NOT KNOWN - '
        CTMB(47:49)=WHCH(1:3)
        CALL SETER (CTMB(1:49),4,2)
        STOP
      END IF
C
C Done.
C
      RETURN
C
      END
