C
C	$Id: e9rin.f,v 1.1.1.1 1992-04-17 22:32:37 ncargd Exp $
C
      SUBROUTINE E9RIN(MESSG,NERR,SAVE)
C
C  THIS ROUTINE STORES THE CURRENT ERROR MESSAGE OR PRINTS THE OLD ONE,
C  IF ANY, DEPENDING ON WHETHER OR NOT SAVE = .TRUE. .
C
      CHARACTER*(*) MESSG
      CHARACTER*113 MESSGP
      SAVE MESSGP,NERRP
      LOGICAL SAVE
      COMMON /UERRF/IERF
C
C  MESSGP STORES THE FIRST 113 CHARACTERS OF THE PREVIOUS MESSAGE
C
C
C  START WITH NO PREVIOUS MESSAGE.
C
      DATA MESSGP/'1'/
      DATA NERRP/0/
C
      IF (.NOT.SAVE) GO TO 20
C
C  SAVE THE MESSAGE.
C
        NERRP=NERR
        MESSGP = MESSG
C
        GO TO 30
C
 20   IF (I8SAV(1,0,.FALSE.).EQ.0) GO TO 30
C
C  PRINT THE MESSAGE.
C
      WRITE(IERF,9000) NERRP,MESSGP
 9000 FORMAT(' ERROR ',I4,' IN ',A113)
C
 30   RETURN
C
      END
