C
C	$Id: eprin.f,v 1.1.1.1 1992-04-17 22:32:37 ncargd Exp $
C
      SUBROUTINE EPRIN
C
C  THIS SUBROUTINE PRINTS THE LAST ERROR MESSAGE, IF ANY.
C
      CHARACTER*1 MESSG
C
      CALL E9RIN(MESSG,1,.FALSE.)
      RETURN
C
      END
