C
C	$Id: i8sav.f,v 1.1.1.1 1992-04-17 22:32:37 ncargd Exp $
C
      INTEGER FUNCTION I8SAV(ISW,IVALUE,SET)
C
C  IF (ISW = 1) I8SAV RETURNS THE CURRENT ERROR NUMBER AND
C               SETS IT TO IVALUE IF SET = .TRUE. .
C
C  IF (ISW = 2) I8SAV RETURNS THE CURRENT RECOVERY SWITCH AND
C               SETS IT TO IVALUE IF SET = .TRUE. .
C
      LOGICAL SET
C
C  START EXECUTION ERROR FREE AND WITH RECOVERY TURNED OFF.
C
      SAVE LERROR,LRECOV
      DATA LERROR/0/ , LRECOV/2/
      IF (ISW .EQ. 1) THEN
        I8SAV = LERROR
        IF (SET) LERROR = IVALUE
      ELSE IF (ISW .EQ. 2) THEN
        I8SAV = LRECOV
        IF (SET) LRECOV = IVALUE
      ENDIF
      RETURN
      END
