      SUBROUTINE  IDGRID(XD,YD,NT,IPT,NL,IPL,NXI,NYI,XI,YI,
     1                   NGP,IGP)
C THIS SUBROUTINE ORGANIZES GRID POINTS FOR SURFACE FITTING BY
C SORTING THEM IN ASCENDING ORDER OF TRIANGLE NUMBERS AND OF THE
C BORDER LINE SEGMENT NUMBER.
C THE INPUT PARAMETERS ARE
C     XD,YD = ARRAYS OF DIMENSION NDP CONTAINING THE X AND Y
C           COORDINATES OF THE DATA POINTS, WHERE NDP IS THE
C           NUMBER OF THE DATA POINTS,
C     NT  = NUMBER OF TRIANGLES,
C     IPT = INTEGER ARRAY OF DIMENSION 3*NT CONTAINING THE
C           POINT NUMBERS OF THE VERTEXES OF THE TRIANGLES,
C     NL  = NUMBER OF BORDER LINE SEGMENTS,
C     IPL = INTEGER ARRAY OF DIMENSION 3*NL CONTAINING THE
C           POINT NUMBERS OF THE END POINTS OF THE BORDER
C           LINE SEGMENTS AND THEIR RESPECTIVE TRIANGLE
C           NUMBERS,
C     NXI = NUMBER OF GRID POINTS IN THE X COORDINATE,
C     NYI = NUMBER OF GRID POINTS IN THE Y COORDINATE,
C     XI,YI = ARRAYS OF DIMENSION NXI AND NYI CONTAINING
C           THE X AND Y COORDINATES OF THE GRID POINTS,
C           RESPECTIVELY.
C THE OUTPUT PARAMETERS ARE
C     NGP = INTEGER ARRAY OF DIMENSION 2*(NT+2*NL) WHERE THE
C           NUMBER OF GRID POINTS THAT BELONG TO EACH OF THE
C           TRIANGLES OR OF THE BORDER LINE SEGMENTS ARE TO
C           BE STORED,
C     IGP = INTEGER ARRAY OF DIMENSION NXI*NYI WHERE THE
C           GRID POINT NUMBERS ARE TO BE STORED IN ASCENDING
C           ORDER OF THE TRIANGLE NUMBER AND THE BORDER LINE
C           SEGMENT NUMBER.
C DECLARATION STATEMENTS
      DIMENSION XD(1), YD(1), IPT(1), IPL(1), XI(1), YI(1), NGP(1),
     1          IGP(1)
C STATEMENT FUNCTIONS
      SPDT(U1,V1,U2,V2,U3,V3)=(U1-U2)*(U3-U2)+(V1-V2)*(V3-V2)
      VPDT(U1,V1,U2,V2,U3,V3)=(U1-U3)*(V2-V3)-(V1-V3)*(U2-U3)
C PRELIMINARY PROCESSING
   10 NT0=NT
      NL0=NL
      NXI0=NXI
      NYI0=NYI
      NXINYI=NXI0*NYI0
      XIMN=AMIN1(XI(1),XI(NXI0))
      XIMX=AMAX1(XI(1),XI(NXI0))
      YIMN=AMIN1(YI(1),YI(NYI0))
      YIMX=AMAX1(YI(1),YI(NYI0))
C DETERMINES GRID POINTS INSIDE THE DATA AREA.
   20 JNGP0=0
      JNGP1=2*(NT0+2*NL0)+1
      JIGP0=0
      JIGP1=NXINYI+1
      DO 39  IT0=1,NT0
        NGP0=0
        NGP1=0
        IT0T3=IT0*3
        IP1=IPT(IT0T3-2)
        IP2=IPT(IT0T3-1)
        IP3=IPT(IT0T3)
        X1=XD(IP1)
        Y1=YD(IP1)
        X2=XD(IP2)
        Y2=YD(IP2)
        X3=XD(IP3)
        Y3=YD(IP3)
        XMN=AMIN1(X1,X2,X3)
        XMX=AMAX1(X1,X2,X3)
        YMN=AMIN1(Y1,Y2,Y3)
        YMX=AMAX1(Y1,Y2,Y3)
        INSD=0
        DO 22  IXI=1,NXI0
          IF(XI(IXI).GE.XMN.AND.XI(IXI).LE.XMX)    GO TO 21
          IF(INSD.EQ.0)   GO TO 22
          IXIMX=IXI-1
          GO TO 23
   21     IF(INSD.EQ.1)   GO TO 22
          INSD=1
          IXIMN=IXI
   22   CONTINUE
        IF(INSD.EQ.0)     GO TO 38
        IXIMX=NXI0
   23   DO 37  IYI=1,NYI0
          YII=YI(IYI)
          IF(YII.LT.YMN.OR.YII.GT.YMX)        GO TO 37
          DO 36  IXI=IXIMN,IXIMX
            XII=XI(IXI)
            L=0
            IF(VPDT(X1,Y1,X2,Y2,XII,YII))     36,25,26
   25       L=1
   26       IF(VPDT(X2,Y2,X3,Y3,XII,YII))     36,27,28
   27       L=1
   28       IF(VPDT(X3,Y3,X1,Y1,XII,YII))     36,29,30
   29       L=1
   30       IZI=NXI0*(IYI-1)+IXI
            IF(L.EQ.1)    GO TO 31
            NGP0=NGP0+1
            JIGP0=JIGP0+1
            IGP(JIGP0)=IZI
            GO TO 36
   31       IF(JIGP1.GT.NXINYI)     GO TO 33
            DO 32  JIGP1I=JIGP1,NXINYI
              IF(IZI.EQ.IGP(JIGP1I))     GO TO 36
   32       CONTINUE
   33       NGP1=NGP1+1
            JIGP1=JIGP1-1
            IGP(JIGP1)=IZI
   36     CONTINUE
   37   CONTINUE
   38   JNGP0=JNGP0+1
        NGP(JNGP0)=NGP0
        JNGP1=JNGP1-1
        NGP(JNGP1)=NGP1
   39 CONTINUE
C DETERMINES GRID POINTS OUTSIDE THE DATA AREA.
C - IN SEMI-INFINITE RECTANGULAR AREA.
   40 DO 79  IL0=1,NL0
        NGP0=0
        NGP1=0
        IL0T3=IL0*3
        IP1=IPL(IL0T3-2)
        IP2=IPL(IL0T3-1)
        X1=XD(IP1)
        Y1=YD(IP1)
        X2=XD(IP2)
        Y2=YD(IP2)
        XMN=XIMN
        XMX=XIMX
        YMN=YIMN
        YMX=YIMX
        IF(Y2.GE.Y1)      XMN=AMIN1(X1,X2)
        IF(Y2.LE.Y1)      XMX=AMAX1(X1,X2)
        IF(X2.LE.X1)      YMN=AMIN1(Y1,Y2)
        IF(X2.GE.X1)      YMX=AMAX1(Y1,Y2)
        INSD=0
        DO 42  IXI=1,NXI0
          IF(XI(IXI).GE.XMN.AND.XI(IXI).LE.XMX)    GO TO 41
          IF(INSD.EQ.0)   GO TO 42
          IXIMX=IXI-1
          GO TO 43
   41     IF(INSD.EQ.1)   GO TO 42
          INSD=1
          IXIMN=IXI
   42   CONTINUE
        IF(INSD.EQ.0)     GO TO 58
        IXIMX=NXI0
   43   DO 57  IYI=1,NYI0
          YII=YI(IYI)
          IF(YII.LT.YMN.OR.YII.GT.YMX)        GO TO 57
          DO 56  IXI=IXIMN,IXIMX
            XII=XI(IXI)
            L=0
            IF(VPDT(X1,Y1,X2,Y2,XII,YII))     46,45,56
   45       L=1
   46       IF(SPDT(X2,Y2,X1,Y1,XII,YII))     56,47,48
   47       L=1
   48       IF(SPDT(X1,Y1,X2,Y2,XII,YII))     56,49,50
   49       L=1
   50       IZI=NXI0*(IYI-1)+IXI
            IF(L.EQ.1)    GO TO 51
            NGP0=NGP0+1
            JIGP0=JIGP0+1
            IGP(JIGP0)=IZI
            GO TO 56
   51       IF(JIGP1.GT.NXINYI)     GO TO 53
            DO 52  JIGP1I=JIGP1,NXINYI
              IF(IZI.EQ.IGP(JIGP1I))     GO TO 56
   52       CONTINUE
   53       NGP1=NGP1+1
            JIGP1=JIGP1-1
            IGP(JIGP1)=IZI
   56     CONTINUE
   57   CONTINUE
   58   JNGP0=JNGP0+1
        NGP(JNGP0)=NGP0
        JNGP1=JNGP1-1
        NGP(JNGP1)=NGP1
C - IN SEMI-INFINITE TRIANGULAR AREA.
   60   NGP0=0
        NGP1=0
        ILP1=MOD(IL0,NL0)+1
        ILP1T3=ILP1*3
        IP3=IPL(ILP1T3-1)
        X3=XD(IP3)
        Y3=YD(IP3)
        XMN=XIMN
        XMX=XIMX
        YMN=YIMN
        YMX=YIMX
        IF(Y3.GE.Y2.AND.Y2.GE.Y1)   XMN=X2
        IF(Y3.LE.Y2.AND.Y2.LE.Y1)   XMX=X2
        IF(X3.LE.X2.AND.X2.LE.X1)   YMN=Y2
        IF(X3.GE.X2.AND.X2.GE.X1)   YMX=Y2
        INSD=0
        DO 62  IXI=1,NXI0
          IF(XI(IXI).GE.XMN.AND.XI(IXI).LE.XMX)    GO TO 61
          IF(INSD.EQ.0)   GO TO 62
          IXIMX=IXI-1
          GO TO 63
   61     IF(INSD.EQ.1)   GO TO 62
          INSD=1
          IXIMN=IXI
   62   CONTINUE
        IF(INSD.EQ.0)     GO TO 78
        IXIMX=NXI0
   63   DO 77  IYI=1,NYI0
          YII=YI(IYI)
          IF(YII.LT.YMN.OR.YII.GT.YMX)        GO TO 77
          DO 76  IXI=IXIMN,IXIMX
            XII=XI(IXI)
            L=0
            IF(SPDT(X1,Y1,X2,Y2,XII,YII))     66,65,76
   65       L=1
   66       IF(SPDT(X3,Y3,X2,Y2,XII,YII))     70,67,76
   67       L=1
   70       IZI=NXI0*(IYI-1)+IXI
            IF(L.EQ.1)    GO TO 71
            NGP0=NGP0+1
            JIGP0=JIGP0+1
            IGP(JIGP0)=IZI
            GO TO 76
   71       IF(JIGP1.GT.NXINYI)     GO TO 73
            DO 72  JIGP1I=JIGP1,NXINYI
              IF(IZI.EQ.IGP(JIGP1I))     GO TO 76
   72       CONTINUE
   73       NGP1=NGP1+1
            JIGP1=JIGP1-1
            IGP(JIGP1)=IZI
   76     CONTINUE
   77   CONTINUE
   78   JNGP0=JNGP0+1
        NGP(JNGP0)=NGP0
        JNGP1=JNGP1-1
        NGP(JNGP1)=NGP1
   79 CONTINUE
      RETURN
      END
