C
C	$Id: nerro.f,v 1.1.1.1 1992-04-17 22:32:36 ncargd Exp $
C
      INTEGER FUNCTION NERRO(NERR)
C
C  RETURNS NERRO = NERR = THE VALUE OF THE ERROR FLAG LERROR.
C
      NERRO=I8SAV(1,0,.FALSE.)
      NERR=NERRO
      RETURN
C
      END
