C
C	$Id: retsr.f,v 1.1.1.1 1992-04-17 22:32:36 ncargd Exp $
C
      SUBROUTINE RETSR(IROLD)
C
C  THIS ROUTINE SETS LRECOV = IROLD.
C
C  IF THE CURRENT ERROR BECOMES UNRECOVERABLE,
C  THE MESSAGE IS PRINTED AND EXECUTION STOPS.
C
C  ERROR STATES -
C
C    1 - ILLEGAL VALUE OF IROLD.
C
      IF (IROLD.LT.1 .OR. IROLD.GT.2)
     1  CALL SETER(' RETSR - ILLEGAL VALUE OF IROLD',1,2)
C
      ITEMP=I8SAV(2,IROLD,.TRUE.)
C
C  IF THE CURRENT ERROR IS NOW UNRECOVERABLE, PRINT AND STOP.
C
      IF (IROLD.EQ.1 .OR. I8SAV(1,0,.FALSE.).EQ.0) RETURN
C
        CALL EPRIN
        CALL FDUM
        STOP
C
      END
