C
C $Id: hlumapeod.f,v 1.3 1999-04-02 22:59:24 kennison Exp $
C
      SUBROUTINE HLUMAPEOD (NOUT,NSEG,IDLS,IDRS,NPTS,PNTS)
      DIMENSION PNTS(*)
      CALL MAPEOD (NOUT,NSEG,IDLS,IDRS,NPTS,PNTS)
      RETURN
      END
