C
C $Id: hlumapeod.f,v 1.2 1998-05-23 20:19:26 kennison Exp $
C
      SUBROUTINE HLUMAPEOD (NOUT,NSEG,IDLS,IDRS,NPTS,PNTS)
      DIMENSION PNTS(*)
      CALL MAPEOD (NOUT,NSEG,IDLS,IDRS,NPTS,PNTS)
      RETURN
      END
