C
C $Id: hlumapeod.f,v 1.1 1995-04-26 23:34:47 kennison Exp $
C
      SUBROUTINE HLUMAPEOD (NOUT,NSEG,IDLS,IDRS,NPTS,PNTS)
      DIMENSION PNTS(*)
      CALL MAPEOD (NOUT,NSEG,IDLS,IDRS,NPTS,PNTS)
      RETURN
      END
