C
C P A C K A G E   E Z M A P   -   I N T R O D U C T I O N
C
C This file contains implementation instructions and the code for the
C package EZMAP.  The code itself is separated into three sections:
C user-level routines, internal routines, and the block data routine
C which determines the default values of internal parameters.  Within
C each section, routines appear in alphabetical order.
C
C P A C K A G E   E Z M A P   -   I M P L E M E N T A T I O N
C
C The EZMAP package is written in FORTRAN-77 and should be relatively
C easy to implement.  The outline data required may be generated by
C running the program
C
C     PROGRAM CONVRT
C       DIMENSION FLIM(4),PNTS(200)
C       REWIND 1
C       REWIND 2
C   1   READ (1,3,END=2) NPTS,IGID,IDLS,IDRS,(FLIM(I),I=1,4)
C       IF (NPTS.GT.1) READ (1,4,END=2) (PNTS(I),I=1,NPTS)
C       WRITE (2) NPTS,IGID,IDLS,IDRS,(FLIM(I),I=1,4),(PNTS(I),I=1,NPTS)
C       GO TO 1
C   2   STOP
C   3   FORMAT (4I4,4F8.3)
C   4   FORMAT (10F8.3)
C     END
C
C with the EZMAP card-image dataset on unit 1.  The output file, on unit
C 2, contains the binary outline data to be used by EZMAP.  The EZMAP
C routine MAPIO (which see) must then be modified to access this file.
C
C T H E   C O D E   ( U S E R - L E V E L   A N D   I N T E R N A L )
C
C $Id: mapdrw.f,v 1.7 1994-12-06 00:50:29 kennison Exp $
C
      SUBROUTINE MAPDRW
C
C Declare required common blocks.  See MAPBD for descriptions of these
C common blocks and the variables in them.
C
      COMMON /MAPCM4/ INTF,JPRJ,PHIA,PHIO,ROTA,ILTS,PLA1,PLA2,PLA3,PLA4,
     +                PLB1,PLB2,PLB3,PLB4,PLTR,GRID,IDSH,IDOT,LBLF,PRMF,
     +                ELPF,XLOW,XROW,YBOW,YTOW,IDTL,GRDR,SRCH,ILCW
      LOGICAL         INTF,LBLF,PRMF,ELPF
      SAVE /MAPCM4/
      COMMON /MAPCMB/ IIER
      SAVE /MAPCMB/
C
C Initialize the package, draw and label the grid, and draw outlines.
C
C Check for an uncleared prior error.
C
      IF (ICFELL('MAPDRW - UNCLEARED PRIOR ERROR',1).NE.0) THEN
        IIER=-1
        RETURN
      END IF
C
C Do it to it.
C
      IF (INTF) THEN
        CALL MAPINT
        IF (ICFELL('MAPDRW',2).NE.0) RETURN
      END IF
      CALL MAPGRD
      IF (ICFELL('MAPDRW',3).NE.0) RETURN
      CALL MAPLBL
      IF (ICFELL('MAPDRW',4).NE.0) RETURN
      CALL MAPLOT
      IF (ICFELL('MAPDRW',5).NE.0) RETURN
C
      RETURN
      END
