C
C $Id: mapfst.f,v 1.6 1998-05-23 20:19:34 kennison Exp $
C
      SUBROUTINE MAPFST (XLAT,XLON)
      IF (ICFELL('MAPFST - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPIT (XLAT,XLON,0)
      IF (ICFELL('MAPFST',2).NE.0) RETURN
      RETURN
      END
