C
C $Id: mpgetl.f,v 1.8 1999-04-02 22:59:44 kennison Exp $
C
      SUBROUTINE MPGETL (WHCH,LVAL)
      CHARACTER*(*) WHCH
      LOGICAL LVAL
      IF (ICFELL('MPGETL - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPGTL (WHCH,LVAL)
      IF (ICFELL('MPGETL',2).NE.0) RETURN
      RETURN
      END
