C
C $Id: mpgetr.f,v 1.5 1994-03-18 23:51:06 kennison Exp $
C
      SUBROUTINE MPGETR (WHCH,RVAL)
      CHARACTER*(*) WHCH
      COMMON /MAPCMB/ IIER
      SAVE /MAPCMB/
      IF (ICFELL('MPGETR - UNCLEARED PRIOR ERROR',1).NE.0) THEN
        IIER=-1
        RETURN
      END IF
      CALL MAPGTR (WHCH,RVAL)
      IF (ICFELL('MPGETR',2).NE.0) RETURN
      RETURN
      END
