C
C $Id: mpgetr.f,v 1.8 1999-04-02 22:59:44 kennison Exp $
C
      SUBROUTINE MPGETR (WHCH,RVAL)
      CHARACTER*(*) WHCH
      IF (ICFELL('MPGETR - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPGTR (WHCH,RVAL)
      IF (ICFELL('MPGETR',2).NE.0) RETURN
      RETURN
      END
