C
C $Id: mpgeti.f,v 1.5 1994-03-18 23:51:02 kennison Exp $
C
      SUBROUTINE MPGETI (WHCH,IVAL)
      CHARACTER*(*) WHCH
      COMMON /MAPCMB/ IIER
      SAVE /MAPCMB/
      IF (ICFELL('MPGETI - UNCLEARED PRIOR ERROR',1).NE.0) THEN
        IIER=-1
        RETURN
      END IF
      CALL MAPGTI (WHCH,IVAL)
      IF (ICFELL('MPGETI',2).NE.0) RETURN
      RETURN
      END
