C
C $Id: mpgeti.f,v 1.8 1999-04-02 22:59:44 kennison Exp $
C
      SUBROUTINE MPGETI (WHCH,IVAL)
      CHARACTER*(*) WHCH
      IF (ICFELL('MPGETI - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPGTI (WHCH,IVAL)
      IF (ICFELL('MPGETI',2).NE.0) RETURN
      RETURN
      END
