C
C $Id: mpgetc.f,v 1.6 1998-04-16 20:21:28 kennison Exp $
C
      SUBROUTINE MPGETC (WHCH,CVAL)
      CHARACTER*(*) WHCH,CVAL
      IF (ICFELL('MPGETC - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPGTC (WHCH,CVAL)
      IF (ICFELL('MPGETC',2).NE.0) RETURN
      RETURN
      END
