C
C $Id: mpseti.f,v 1.5 1994-03-18 23:51:10 kennison Exp $
C
      SUBROUTINE MPSETI (WHCH,IVAL)
      CHARACTER*(*) WHCH
      COMMON /MAPCMB/ IIER
      SAVE /MAPCMB/
      IF (ICFELL('MPSETI - UNCLEARED PRIOR ERROR',1).NE.0) THEN
        IIER=-1
        RETURN
      END IF
      CALL MAPSTI (WHCH,IVAL)
      IF (ICFELL('MPSETI',2).NE.0) RETURN
      RETURN
      END
