C
C $Id: mpsetc.f,v 1.7 1998-05-23 20:20:10 kennison Exp $
C
      SUBROUTINE MPSETC (WHCH,CVAL)
      CHARACTER*(*) WHCH,CVAL
      IF (ICFELL('MPSETC - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPSTC (WHCH,CVAL)
      IF (ICFELL('MPSETC',2).NE.0) RETURN
      RETURN
      END
