C
C $Id: mpseti.f,v 1.7 1998-05-23 20:20:10 kennison Exp $
C
      SUBROUTINE MPSETI (WHCH,IVAL)
      CHARACTER*(*) WHCH
      IF (ICFELL('MPSETI - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPSTI (WHCH,IVAL)
      IF (ICFELL('MPSETI',2).NE.0) RETURN
      RETURN
      END
