C
C $Id: supcon.f,v 1.5 1998-04-16 20:21:35 kennison Exp $
C
      SUBROUTINE SUPCON (RLAT,RLON,UVAL,VVAL)
      IF (ICFELL('SUPCON - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MAPTRN (RLAT,RLON,UVAL,VVAL)
      IF (ICFELL('SUPCON',2).NE.0) RETURN
      RETURN
      END
