C
C $Id: supcon.f,v 1.2 1993-12-21 00:34:17 kennison Exp $
C
      SUBROUTINE SUPCON (RLAT,RLON,UVAL,VVAL)
      CALL MAPTRN (RLAT,RLON,UVAL,VVAL)
      IF (ICFELL('SUPCON',1).NE.0) RETURN
      RETURN
      END
