C
C $Id: supcon.f,v 1.4 1994-03-18 23:51:15 kennison Exp $
C
      SUBROUTINE SUPCON (RLAT,RLON,UVAL,VVAL)
      COMMON /MAPCMB/ IIER
      SAVE /MAPCMB/
      IF (ICFELL('SUPCON - UNCLEARED PRIOR ERROR',1).NE.0) THEN
        IIER=-1
        RETURN
      END IF
      CALL MAPTRN (RLAT,RLON,UVAL,VVAL)
      IF (ICFELL('SUPCON',2).NE.0) RETURN
      RETURN
      END
