C
C  $Id: cscomn.h,v 1.2 2000-03-10 01:06:05 fred Exp $
C
      DOUBLE PRECISION  USSIG, TOLIC, TOLSG, RMVAL
      INTEGER           NUMLS, NUMIT, ICSIG, IGFLG
      COMMON /CSCOMI/   NUMLS, NUMIT, ICSIG, IGFLG
      COMMON /CSCOMD/   USSIG, TOLIC, TOLSG, RMVAL
