C
C  $Id: cscomn.h,v 1.1 2000-01-12 22:56:10 fred Exp $
C
      DOUBLE PRECISION  USSIG, TOLIC, TOLSG
      INTEGER           NUMLS, NUMIT, ICSIG, IGFLG
      COMMON /CSCOMI/   NUMLS, NUMIT, ICSIG, IGFLG
      COMMON /CSCOMD/   USSIG, TOLIC, TOLSG
