.\"
.\"	$Id: strmln.m,v 1.1 1993-03-11 16:33:49 haley Exp $
.\"
.TH STRMLN 3NCARG "March 1993" UNIX "NCAR GRAPHICS"
.SH NAME
STRMLN - STRMLN draws a streamline representation of the flow
field.  The representation is independent of the flow speed.
.SH SYNOPSIS
CALL STRMLN (U,V,WORK,IMAX,IPTSX,JPTSY,NSET,IER)
.SH C-BINDING SYNOPSIS
#include <ncarg/ncargC.h>
.sp
void c_strmln (float *u, float *v, float *work, int imax, int iptsx, int jptsy, int nset, int *ier)
.SH DESCRIPTION 
.IP U,V 12
Two dimensional arrays containing the velocity fields
to be plotted.  Note: If the U and V components are,
for example, defined in Cartesian coordinates and the
user wishes to plot them on a different projection
(such as stereographic), then the appropriate
transformation must be made to the U and V components
via the functions FU and FV (located in DRWSTR).
.IP WORK 12
User provided work array. The dimension of this array
must be .GE. 2*IMAX*JPTSY.
.sp
Caution: This routine does not check the size of the
work array.
.sp
.IP IMAX 12
The first dimension of U and V in the calling program
(X-direction).
.IP IPTSX 12
The number of points to be plotted in the first
subscript direction (X-direction).
.IP JPTSY 12
The number of points to be plotted in the second
subscript direction (Y-direction)..
IP NSET 12
Flag to control scaling
> 0     STRMLN assumes that the window and viewport
have been set by the user in such a way as to
properly scale the plotting instructions
generated by STRMLN. PERIM is not called.
= 0     STRMLN will establish the window and viewport
to properly scale the plotting instructions to
the standard configuration. PERIM is called to
draw the border.
< 0     STRMLN establishes the window and viewport so
as to place the streamlines within the limits
of the user's window. PERIM is not called.
.IP IER 12
0	when no errors are detected
-1      when the routine is called with ICYC, .NE. 0
and the data are not cyclic (ICYC is an
internal parameter described below); in this
case the routine will draw the streamlines with
the non-cyclic interpolation formulas.
.SH C-BINDING DESCRIPTION
The C-binding argument descriptions are the same as the Fortran 
argument descriptions, with the following exceptions:
.sp
.IP imax 12
The second dimension of u and v in the calling program
.IP iptsx 12
The number of points to be plotted in the second
subscript direction.
.IP jptsy 12
The number of points to be plotted in the first
subscript direction.
.SH ACCESS
To use STRMLN load the NCAR Graphics libraries ncarg,
ncarg_gks, and ncarg_loc, preferably in that order.  To use 
c_strmln load the NCAR Graphics libraries ncargC, ncarg_gksC,
ncarg, ncarg_gks, and ncarg_loc, preferably in that order.
.SH SEE ALSO
Online:
strmln, ezstrm, ncarg_cbind
.sp
Hardcopy:  "NCAR Graphics User's Guide, Version 2.00"
.SH COPYRIGHT
(c) Copyright 1987, 1988, 1989, 1991, 1993 University Corporation
for Atmospheric Research
.br
All Rights Reserved

