.TH STRMLN 3NCARG "March 1993" UNIX "NCAR GRAPHICS"
.na
.nh
.SH NAME
STRMLN - 
Plots a streamline representation of a flow field,
given two 2-dimensional vector component arrays, U and V.
Certain characteristics of the plot may be controlled by
adjusting the values given to the input arguments. Other
less frequently changed characteristics may be affected by
modifying the initial values assigned to members of the
common blocks STR02 and STR03 at the beginning of the
executable code section of STRMLN. In addition, depending
on the value given to the compatibility parameter, CPM,
many options may be controlled by setting internal
parameters using STSETx routines.
.SH UTILITY
This routine is part of the Streamlines utility in NCAR Graphics. To see
the overview man page for this utility, type "man streamlines". 
.SH SYNOPSIS
CALL STRMLN (U,V,WORK,IMAX,IPTSX,JPTSY,NSET,IER)
.SH C-BINDING SYNOPSIS
#include <ncarg/ncargC.h>
.sp
void c_strmln (float *u, float *v, float *work, int imax, int iptsx, int jptsy, int nset, int *ier)
.SH DESCRIPTION 
.IP U 12
(REAL 2-dimensional array, dimensioned IMAX x n: n >=
JPTSY, input): By default, assumed to contain the first
dimensional Cartesian components of the vector field.
However, if PLR is non-zero, it is treated as containing
the vector magnitudes.
.IP V 12
(REAL 2-dimensional array, dimensioned IMAX x n: n >=
JPTSY, input): By default, assumed to contain the second
dimensional Cartesian components of the vector field.
However, if PLR is non-zero, it is treated as containing
the vector angles.
.IP WORK 12
(REAL array, dimensioned n: n>= 2*IPTSX*JPTSY, working
space): User provided work array used to store the
normalized vector component values, and also to keep track
of the grid boxes eligible for starting a streamline or
placement of a directional arrow.
.IP IMAX 12
(INTEGER, input): Actual value of the first dimension
of arrays U and V.
.IP IPTSX 12
(INTEGER, input): Number of contiguous elements along
the first dimensional axis containing data to be processed
in each of the arrays, U and V.
.IP JPTSY 12
(INTEGER, input): Number of contiguous elements along
the second dimensional axis containing data to be processed
in each of the arrays, U and V.
.IP NSET 12
(INTEGER, input) Flag that controls how and when the
SET call is invoked. If NSET is 0, STRMLN establishes the
viewport and the window to properly scale plotting
instructions to the standard configuration. PERIM is called
to draw a border. If NSET is greater than zero, STRMLN
assumes that the user has established the window and
viewport in such a way as to properly scale the plotting
instructions generated by STRMLN. PERIM is not called. If
NSET is less than zero, STRMLN places the contour plot
within the limits of the user\'s current window and
viewport. PERIM is not called.
.IP IER 12
(INTEGER, output) If no error is detected IER contains
the value 0 on exit from STRMLN. If the routine is called
with the common block variable ICYC containing a non-zero
value indicating the data is considered to be cyclic, but
the data is found not to be cyclic, STRMLN will still
process the data using non-cyclic interpolation formulas,
but returns the value of -1 in IER.
.SH C-BINDING DESCRIPTION
The C-binding argument descriptions are the same as the Fortran 
argument descriptions, with the following exceptions:
.sp
.IP imax 12
The second dimension of u and v in the calling program
.IP iptsx 12
The number of points to be plotted in the second
subscript direction.
.IP jptsy 12
The number of points to be plotted in the first
subscript direction.
.SH EXAMPLES
Use the ncargex command to see the following relevant
example: 
stex02,
tstrml.
.SH ACCESS
To use STRMLN, load the NCAR Graphics libraries ncarg, ncarg_gks,
and ncarg_loc, preferably in that order.
.SH SEE ALSO
Online:
streamlines,
streamlines_params,
ezstrm,
fx,
fy,
stgeti,
stgetr,
stinit,
stream,
strset,
stseti,
stsetr,
stuixy,
stumsl,
stumta,
stumxy,
ncarg_cbind.
.SH COPYRIGHT
Copyright 1987, 1988, 1989, 1991, 1993 University Corporation
for Atmospheric Research
.br
All Rights Reserved
