C
C	$Id: ezcntr.f,v 1.1.1.1 1992-04-17 22:35:07 ncargd Exp $
C
      SUBROUTINE EZCNTR (Z,M,N)
C
C USER ENTRY.  SEE COMMENT CARD DESCRIPTION CONTAINED IN CONEC.
C
      SAVE
      DIMENSION       Z(M,N)
      DATA NSET,NHI,NDASH/0,0,682/
C
C                             682=1252B
C THE FOLLOWING CALL IS FOR GATHERING STATISTICS ON LIBRARY USE AT NCAR
      CALL Q8QST4 ('GRAPHX', 'CONRECSUPR', 'EZCNTR', 'VERSION 01')
C
      CALL CONREC (Z,M,M,N,0.,0.,0.,NSET,NHI,-NDASH)
      CALL FRAME
      RETURN
      END
