C
C	$Id: lastd.f,v 1.1.1.1 1992-04-17 22:35:00 ncargd Exp $
C
      SUBROUTINE LASTD
      SAVE
C USER ENTRY POINT. SEE DOCUMENTATION FOR PURPOSE.
      DATA IDUMMY /0/
      CALL CFVLD (3,IDUMMY,IDUMMY)
      CALL PLOTIT (0,0,0)
      RETURN
      END
