.TH LASTD 3NCARG "March 1993" UNIX "NCAR GRAPHICS"
.na
.nh
.SH NAME
LASTD - Completes drawing of a line with interspersed characters
generated by FRSTD and VECTD calls.
.SH SYNOPSIS
CALL LASTD 
.SH C-BINDING SYNOPSIS
#include <ncarg/ncargC.h>
.sp
void c_lastd()
.SH USAGE
When using FRSTD and VECTD, LASTD may be called.  If the dashed
line package was leaving space for characters and the line ended
before there was enough space for the characters, the space left
will be filled in if LASTD is called.
.SH EXAMPLES
Use the ncargex command to see the following relevant examples: 
tdashp.f, tdashs.f
.SH ACCESS
To use LASTD load the NCAR Graphics libraries ncarg, ncarg_gks,
and ncarg_loc, preferably in that order.  To use c_lastd load 
the NCAR Graphics libraries ncargC, ncarg_gksC, ncarg, ncarg_gks,
and ncarg_loc, preferably in that order.
.SH SEE ALSO
Online:
dashline, dashline_params, curved,
dashdb, dashdc, frstd, lastd, lined, reset, ncarg_cbind
.sp
Hardcopy:  
NCAR Graphics Contouring and Mapping Tutorial;
NCAR Graphics Fundamentals, UNIX Version;
User's Guide for NCAR GKS-0A Graphics
.SH COPYRIGHT
Copyright 1987, 1988, 1989, 1991, 1993 University Corporation
for Atmospheric Research
.br
All Rights Reserved
