#!/bin/csh -f
#
# This script is a very basic one for creating the two 
# NCL binary distributions for each system: OPeNDAP and 
# non-OPenDAP. There are certain assumptions about this
# script:
#
#  1. The non-OPeDNAP version of the NetCDF C library
#     is in $NCARG_EXTERNAL/nodap, and the OPeNDAP
#     version is in $NCARG_EXTERNAL.
#
#  2. The OPenDAP-enabled ESMF_RegridWeightGen is installed to
#     $NCARG_EXTERNAL/bin/ESMF_RegridWeightGen.dap and the 
#     non-OPenDAP-enabled one to 
#     $NCARG_EXTERNAL/bin/ESMF_RegridWeightGen.nodap
#
#  3. The $NCARG/config/Site.local,Site.local.dap,Site.local.nodap
#     $NCARG/config/Project,Project.dap,Project.nodap
#     files all exist. The Site.local.nodap should just have an
#     extra -L$NCARG_EXTERNAL/nodap/lib path so that the non
#     OPenDAP NetCDF gets loaded first. The Project.nodap file
#     has the "-lcurl" stuff removed from the netcdf libs line.
#
#  4. You are able to display an NCL X11 window, because various
#     X11 tests are executed.
#
# set echo verbose timestamp

set un=`uname -n`
set um=`uname -m`
set os=`uname -s`
set SCP_FILES       # Whether to scp files to yellowstone
set TAR_FILES       # Whether to tar up files
set ASK             # Whether to ask to continue at various locations

if ("$os" == "Darwin") then
  set ldd = "otool -L"
  set macosv = `sw_vers -productVersion`
  if( $macosv = "10.9.4") then
    set un="riley.local"
  endif
else
  set ldd = "ldd"
endif

if ($?COMPILER_VERSION) then
  if ( "$COMPILER_VERSION" == "4.7.2" ) then
    set un="yellowstone_gnu472"
  else if ( "$COMPILER_VERSION" == "4.4.7" ) then
    set un="yellowstone_gnu447"
  else if ( "$COMPILER_VERSION" == "12.1.5" ) then
    set un="yellowstone_intel1215"
  else
    echo "I don't recognize this yellowstone system"
  endif
endif

if ("$un" == "yellowstone_gnu447" || "$un" == "yellowstone_gnu472" || "$un" == "yellowstone_intel1215") then
  echo "----------------------------------------------------------------------"
  echo "ON YELLOWSTONE: building a binary for $un"
  echo "----------------------------------------------------------------------"
  if ("$un" == "yellowstone_gnu447" || "$un" == "yellowstone_gnu472") then
    gcc --version
    echo "----------------------------------------------------------------------"
    gfortran --version
  else
    icc --version
    echo "----------------------------------------------------------------------"
    ifort --version
  endif
  echo "----------------------------------------------------------------------"
  if( $?ASK ) then
    echo -n "Continue? (y/n) "
    set answer="$<"
    if ("$answer" != "y") then
      exit
    endif
  endif
endif

if ("$un" == "harmon.cgd.ucar.edu") then
  setenv NCARGTEST /project/yampa02/haley/ncargtest
  setenv NCARG_EXTERNAL /contrib/ncl-6.2.1/external
  setenv NCARG_ROOT /contrib/ncl-6.2.1
  setenv NCARG /contrib/ncl-6.2.1/src/ncarg
  set dap_string   = "Linux_SL6.5_x86_64_gcc447"
  set nodap_string = "Linux_SL6.5_x86_64_nodap_gcc447"
else if ("$un" == "k5") then
  setenv NCARGTEST /d2/haley/ncargtest
  setenv NCARG_EXTERNAL /d2/haley/external
  setenv NCARG_ROOT /d2/haley/ncl-6.2.1
  setenv NCARG /d2/haley/src/ncarg
  set dap_string   = "Linux_RHEL5.10_i686_gcc412"
  set nodap_string = "Linux_RHEL5.10_i686_nodap_gcc412"
else if ("$un" == "k6") then
  setenv NCARGTEST /d2/haley/ncargtest
  setenv NCARG_EXTERNAL /d2/haley/external
  setenv NCARG_ROOT /d2/haley/ncl-6.2.1
  setenv NCARG /d2/haley/src/ncarg
  set dap_string   = "Linux_Debian6.0_i686_gcc445"
  set nodap_string = "Linux_Debian6.0_i686_nodap_gcc445"
else if ("$un" == "k7") then
  setenv NCARGTEST /d2/haley/ncargtest
  setenv NCARG_EXTERNAL /d2/haley/external
  setenv NCARG_ROOT /d2/haley/ncl-6.2.1
  setenv NCARG /d2/haley/src/ncarg
  set dap_string   = "Linux_Debian6.0_x86_64_gcc445"
  set nodap_string = "Linux_Debian6.0_x86_64_nodap_gcc445"
else if ("$un" == "k8") then
  setenv NCARGTEST /d2/haley/ncargtest
  setenv NCARG_EXTERNAL /d2/haley/external
  setenv NCARG_ROOT /d2/haley/ncl-6.2.1
  setenv NCARG /d2/haley/src/ncarg
  set dap_string   = "Linux_RHEL5.10_x86_64_gcc412"
  set nodap_string = "Linux_RHEL5.10_x86_64_nodap_gcc412"
else if ("$un" == "k9") then
  setenv NCARGTEST /d2/haley/ncargtest
  setenv NCARG_EXTERNAL /d2/haley/external
  setenv NCARG_ROOT /d2/haley/ncl-6.2.1
  setenv NCARG /d2/haley/src/ncarg
  set dap_string   = "Linux_Debian7.6_x86_64_gcc472"
  set nodap_string = "Linux_Debian7.6_x86_64_nodap_gcc472"
  set gccv = `gcc --version`
else if ("$un" == "yellowstone_gnu447") then
  setenv NCARGTEST /glade/u/ncldev/test/ncargtest
  setenv NCARG_EXTERNAL /glade/p/work/haley/dev/external/gnu/4.4.7
  setenv NCARG_ROOT /glade/apps/opt/ncl/6.2.1/gnu/4.4.7
  setenv NCARG /glade/p/work/haley/src/ncl-trunk-gnu447

  unsetenv LIB_NCAR
  unsetenv INC_NCAR
  unsetenv NETCDF

  set path=($NCARG_ROOT/bin /ncar/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/etc /ncar/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/bin /usr/lib64/qt-3.3/bin /glade/apps/opt/usr/bin /usr/bin /bin /usr/sbin /sbin /usr/local/openssh/5.7p1krb/bin /usr/lpp/mmfs/bin /opt/ibutils/bin /ncar/opt/hpss)
  rehash

  set dap_string   = "Linux_RHEL6.4_x86_64_gcc447"
  set nodap_string = "Linux_RHEL6.4_x86_64_nodap_gcc447"
else if ("$un" == "yellowstone_gnu472") then
  setenv NCARGTEST /glade/u/ncldev/test/ncargtest
  setenv NCARG_EXTERNAL /glade/p/work/haley/dev/external/gnu/4.7.2
  setenv NCARG_ROOT /glade/p/work/haley/dev/ncl-trunk-gnu472-opt
  setenv NCARG /glade/p/work/haley/src/ncl-trunk-gnu472

  unsetenv LIB_NCAR
  unsetenv INC_NCAR
  unsetenv NETCDF

  set path=($NCARG_ROOT/bin /glade/apps/opt/gnu/4.7.2/bin /usr/lib64/qt-3.3/bin /glade/apps/opt/usr/bin /ncar/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/etc /ncar/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/bin /usr/bin /bin /usr/sbin /sbin /usr/local/openssh/5.7p1krb/bin /usr/lpp/mmfs/bin /opt/ibutils/bin /ncar/opt/hpss)
  rehash

  set dap_string   = "Linux_RHEL6.4_x86_64_gcc472"
  set nodap_string = "Linux_RHEL6.4_x86_64_nodap_gcc472"
else if ("$un" == "yellowstone_intel1215") then
  setenv NCARG /glade/p/work/haley/src/ncl-trunk-intel
  setenv NCARGTEST /glade/u/ncldev/test/ncargtest
  setenv NCARG_EXTERNAL /glade/p/work/haley/dev/external/intel/12.1.5
  setenv NCARG_ROOT /glade/apps/opt/ncl/6.2.1/intel/12.1.5
  setenv YMAKE_DEV_FILE $NCARG/ymakedevfile

  unsetenv LIB_NCAR
  unsetenv INC_NCAR
  unsetenv NETCDF

  set path=($NCARG_ROOT/bin /usr/lib64/qt-3.3/bin /ncar/opt/intel/12.1.0.233/composer_xe_2011_sp1.11.339/bin/intel64 /glade/apps/opt/usr/bin /ncar/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/etc /ncar/opt/lsf/9.1/linux2.6-glibc2.3-x86_64/bin /usr/bin /bin /usr/sbin /sbin /usr/local/openssh/5.7p1krb/bin /usr/lpp/mmfs/bin /opt/ibutils/bin /ncar/opt/hpss /glade/apps/opt/netcdf/4.3.0/intel/12.1.5/bin)
  rehash

  set dap_string   = "Linux_RHEL6.4_x86_64_intel1215"
  set nodap_string = "Linux_RHEL6.4_x86_64_nodap_intel1215"
else if ("$un" == "riley.local") then
  setenv NCARGTEST /Users/haley/ncargtest
  setenv NCARG_EXTERNAL /Users/haley/dev/external
  setenv NCARG_ROOT /Users/haley/dev
  setenv NCARG /Users/haley/src/ncarg
  set dap_string   = "MacOS_10.9_64bit_gcc481"
  set nodap_string = "MacOS_10.9_64bit_nodap_gcc481"
else if ("$un" == "cisl-denton.scd.ucar.edu" ||"$un" == "cisl-denton.local") then
  setenv NCARGTEST /Users/haley/ncargtest
  setenv NCARG_EXTERNAL /Users/haley/dev/external
  setenv NCARG_ROOT /Users/haley/dev
  setenv NCARG /Users/haley/src/ncarg
  set dap_string   = "MacOS_10.8_64bit_gcc471"
  set nodap_string = "MacOS_10.8_64bit_nodap_gcc471"
else
  echo "I DON'T RECOGNIZE THIS SYSTEM. EXITING..."
  exit
endif

# harmon doesn't have enough disk space in /contrib for tar files.
if ("$un" == "harmon.cgd.ucar.edu") then
  set tar_dir="/project/yampa02/haley"
else
  set tar_dir="$NCARG_ROOT"
endif

setenv PATH $NCARG_ROOT/bin:$PATH
rehash

# Error checking
set copy_files   = ("Site.local" "Project")
cd $NCARG/config
foreach f($copy_files)
  if(! -f  $f) then
    echo "$f doesn't exist...can't continue"
    exit
  endif
  if(! -f  $f.dap) then
    echo "$f.dap doesn't exist...can't continue"
    exit
  endif
  if(! -f  $f.nodap) then
    echo "$f.nodap doesn't exist...can't continue"
    exit
  endif
end

# Test to see if ESMF_RegridWeightGen is to be tarred up.
set ESMF
set esmf_files = ("$NCARG_EXTERNAL/bin/ESMF_RegridWeightGen.nodap $NCARG_EXTERNAL/bin/ESMF_RegridWeightGen.dap")
foreach f($esmf_files)
  if(! -f  $f) then
    echo "$f doesn't exist...unsetting ESMF..."
    unset ESMF
  endif
endif

set path=($NCARG_ROOT/bin $path)
rehash
set version=`ncl -V`
set dap_tarfile   = "ncl_ncarg-$version.$dap_string.tar"
set nodap_tarfile = "ncl_ncarg-$version.$nodap_string.tar"
set dap_gzfile    = "$dap_tarfile.gz"
set nodap_gzfile  = "$nodap_tarfile.gz"

set sys_name = "yellowstone.ucar.edu"
set sys_dir  = "/glade/u/ncldev/src/tarfiles/dist/ncl/$version"

# Clean up
cd $tar_dir
/bin/rm $dap_gzfile $nodap_gzfile $dap_tarfile $nodap_tarfile

set opendap_test  = "$NCARGTEST/nclscripts/opendap.ncl"
set esmf_test     = "$NCARGTEST/nclscripts/plotting/ESMF_1.ncl"
set ncargex_tests = ("cpex08" "c_shex03")
set ng4ex_tests   = ("cn02c" "xy04f" "nm04c") 

#----------------------------------------------------------------------
# Get ready to create non-opendap ncl
#----------------------------------------------------------------------
cd $NCARG/config
foreach f($copy_files)
  /bin/cp $f.nodap $f
end

set dirs = ($NCARG/ni/src/ncl)
foreach dir($dirs)
  cd $dir
  /bin/rm ncl
  make me
  make all install
  echo "----------------------------------------------------------------------"
  echo "Executing ldd on this non-OPenDAP binary..."
  echo "----------------------------------------------------------------------"
  $ldd ncl
  if( $?ASK ) then
    echo -n "Continue? (y/n) "
    set answer="$<"
    if ("$answer" != "y") then
      exit
    endif
  endif
end

echo "----------------------------------------------------------------------"
  echo "Running opendap test...should fail"
  echo "----------------------------------------------------------------------"
ncl $opendap_test

if( $?ASK ) then
  echo -n "Continue? (y/n) "
  set answer="$<"
  if ("$answer" != "y") then
    exit
  endif
endif

#----------------------------------------------------------------------
# Copy over non-OPeNDAP ESMF_RegridWeightGen
#----------------------------------------------------------------------
if( $?ESMF ) then
  /bin/rm $NCARG_ROOT/bin/ESMF_RegridWeightGen
  /bin/cp $NCARG_EXTERNAL/bin/ESMF_RegridWeightGen.nodap $NCARG_ROOT/bin/ESMF_RegridWeightGen
  echo "----------------------------------------------------------------------"
  echo "Executing ldd on this non-OPenDAP binary..."
  echo "----------------------------------------------------------------------"
  $ldd $NCARG_ROOT/bin/ESMF_RegridWeightGen

  echo "----------------------------------------------------------------------"
  echo "Running ESMF_RegridWeightGen test...should succeed"
  echo "----------------------------------------------------------------------"
  ncl 'wtype="x11"' $esmf_test

  if( $?ASK ) then
    echo -n "Continue? (y/n) "
    set answer="$<"
    if ("$answer" != "y") then
      exit
    endif
  endif
endif

if ("$un" == "yellowstone_gnu447" || "$un" == "yellowstone_gnu472" || "$un" == "yellowstone_intel1215") then
  ncargex cpex08 c_shex03 -W x11 -n
  ncargf77 -L$e/lib cpexcc.f cpex08.f -o cpex08
  ./cpex08
  ncargcc -ngmath -L$e/lib c_shex03.c -o c_shex03
  ./c_shex03
  /bin/rm cpex08* cpexcc* c_shex*
else
  foreach f($ncargex_tests)
    ncargex $f -clean -W x11
  end
endif

if( $?ASK ) then
  echo -n "Continue? (y/n) "
  set answer="$<"
  if ("$answer" != "y") then
    exit
  endif
endif

if ("$un" == "yellowstone_gnu447" || "$un" == "yellowstone_gnu472" || "$un" == "yellowstone_intel1215") then
  ng4ex xy04f cn02c nm04c -W x11 -n 
  nhlf77 -L$e/lib xy04f.f -o xy04f
  ./xy04f
  nhlcc -L$e/lib cn02c.c -o cn02c
  ./cn02c
  nhlcc -L$e/lib -ngmath nm04c.c -o nm04c
  ./nm04c
  /bin/rm xy04* cn02* nm04*
else
  foreach f($ng4ex_tests)
    ng4ex $f -clean -W x11
  end
endif

if( $?ASK ) then
  echo -n "Continue? (y/n) "
  set answer="$<"
  if ("$answer" != "y") then
    exit
  endif
endif

echo "----------------------------------------------------------------------"
echo "Running check_files..."
echo "----------------------------------------------------------------------"
$NCARG/install/make-tarfile/check_files

if( $?ASK ) then
  echo -n "Continue? (y/n) "
  set answer="$<"
  if ("$answer" != "y") then
    exit
  endif
endif

# Create the tarfile
if ($?TAR_FILES) then
  echo "----------------------------------------------------------------------"
  echo "Creating tarfile..."
  echo "----------------------------------------------------------------------"
  cd $NCARG_ROOT
  $NCARG/install/make-tarfile/create_dist -p -d $tar_dir -f $nodap_string
  if( $?ASK ) then
    echo -n "Continue? (y/n) "
    set answer="$<"
    if ("$answer" != "y") then
      exit
    endif
  endif
endif

#----------------------------------------------------------------------
# Get ready to create opendap ncl                                           
#----------------------------------------------------------------------
cd $NCARG/config
foreach f($copy_files)
  /bin/cp $f.dap $f
end

set dirs = ($NCARG/ni/src/ncl)
foreach dir($dirs)
  cd $dir
  /bin/rm ncl
  make me
  make all install
  echo "----------------------------------------------------------------------"
  echo "Executing ldd on this OPenDAP binary..."
  echo "----------------------------------------------------------------------"
  $ldd ncl
  if( $?ASK ) then
    echo -n "Continue? (y/n) "
    set answer="$<"
    if ("$answer" != "y") then
      exit
    endif
  endif
end

echo "----------------------------------------------------------------------"
echo "Running opendap test...should succeed"
echo "----------------------------------------------------------------------"
ncl $opendap_test

if( $?ASK ) then
  echo -n "Continue? (y/n) "
  set answer="$<"
  if ("$answer" != "y") then
    exit
  endif
endif

#----------------------------------------------------------------------
# Copy over DAP ESMF_RegridWeightGen
#----------------------------------------------------------------------
if( $?ESMF ) then
  /bin/rm $NCARG_ROOT/bin/ESMF_RegridWeightGen
  /bin/cp $NCARG_EXTERNAL/bin/ESMF_RegridWeightGen.dap $NCARG_ROOT/bin/ESMF_RegridWeightGen

  echo "----------------------------------------------------------------------"
  echo "Executing ldd on this OPenDAP binary..."
  echo "----------------------------------------------------------------------"
  $ldd $NCARG_ROOT/bin/ESMF_RegridWeightGen
 
  echo "----------------------------------------------------------------------"
  echo "Running ESMF_RegridWeightGen test...should succeed"
  echo "----------------------------------------------------------------------"
  ncl 'wtype="x11"' $esmf_test

  if( $?ASK ) then
    echo -n "Continue? (y/n) "
    set answer="$<"
    if ("$answer" != "y") then
      exit
    endif
  endif
endif

echo "----------------------------------------------------------------------"
echo "Running check_files..."
echo "----------------------------------------------------------------------"
$NCARG/install/make-tarfile/check_files

if( $?ASK ) then
  echo -n "Continue? (y/n) "
  set answer="$<"
  if ("$answer" != "y") then
    exit
  endif
endif

# Create the tarfile
if ($?TAR_FILES) then
  echo "----------------------------------------------------------------------"
  echo "Creating tarfile..."
  echo "----------------------------------------------------------------------"
  cd $NCARG_ROOT
  $NCARG/install/make-tarfile/create_dist -p -d $tar_dir -f $dap_string
  if( $?ASK ) then
    echo -n "Continue? (y/n) "
    set answer="$<"
    if ("$answer" != "y") then
      exit
    endif
  endif

# Copy files over to yellowstone                                                
  if ($?SCP_FILES) then
    echo "----------------------------------------------------------------------"
    echo "Copying files to yellowstone..."
    echo "----------------------------------------------------------------------"
    cd $tar_dir
    if ("$un" == "yellowstone_gnu447" || "$un" == "yellowstone_gnu472" || "$un" == "yellowstone_intel1215") then
      /bin/cp $nodap_gzfile $dap_gzfile ${sys_dir}/.
    else
      scp $nodap_gzfile $dap_gzfile ${sys_name}:${sys_dir}/.
    endif
  endif
endif
