	PROGRAM CCPKCL

        PARAMETER (K=40,N=40,LRWK=1000,LIWK=1000)
	REAL ZREG(K,N), RWRK(LRWK)
	INTEGER M, NOCL, IWRK(LIWK)

	CALL GETDAT (ZREG, K, M, N) 

C Open GKS
	CALL OPNGKS

	CALL CPSETI('CLS - CONTOUR LEVEL SELECTION FLAG',-20)
	CALL CPRECT(ZREG,K,M,N,RWRK,LRWK,IWRK,LIWK)

C Force contour lines to be chosen
	CALL CPPKCL (ZREG, RWRK, IWRK)
C Get the number of contour levels chosen
	CALL CPGETI ('NCL - NUMBER OF CONTOUR LEVELS',NOCL)
	CALL CPSETI ('NCL - NUMBER OF CONTOUR LEVELS',NOCL+1)
	CALL CPSETI ('PAI - PARAMETER ARRAY INDEX',NOCL+1)
	CALL CPSETR ('CLV - CONTOUR LEVEL VALUE',0.0)

	CALL CPBACK(ZREG, RWRK, IWRK)
	CALL CPCLDR(ZREG,RWRK,IWRK)

C Close frame and close GKS
	CALL FRAME
	CALL CLSGKS

	STOP
	END

	SUBROUTINE GETDAT (ZREG, K, M, N)
	INTEGER I,J,K,M,N
	REAL ZREG(K,N)

	M=K
	DO 10, I=1,M
	  DO 20, J=1,N
	    ZREG(I,J)= 10.E-5*(-16.*REAL(I**2*J) +
     +		    34*REAL(I*J**2) - REAL(6*I) + 93.)
  20	  CONTINUE
  10	CONTINUE

	RETURN
	END

