#!/bin/csh -f
#
#	$Id: ymake,v 1.5 1993-02-20 00:16:29 clyne Exp $
#
######################################################################
#
# Program:	ymake
#
# Purpose:	"ymake" processes a "yMakefile" or "ymakefile"
#		that may have imbedded "cpp" commands. In producing
#		the output file, "Makefile" or "makefile", "ymake"
#		first reads in a "configuration file", based on
#		what the host system is, and then runs the
#		yMakefile/ymakefile through "cpp", thus producing
#		"Makefile" or "makefile". The result is a standard,
#		portable Makefile.
#
#		This mechanism is used for generating a machine-dependent 
#		hierarchy of Makefiles at installation time.
#
#		Warning: this script WILL overwrite the existing
#		Makefile IF a yMakefile exists!
#
# Author:	Don Middleton-Link
#
# Revision History:
#		Created June 1988
#		Revised October 1988 - extensions added for IBM/AIX
#		Moved to Bourne shell version for UNICOS 5.0 beta
#		Revised November 1989
#
# Warning:	This script WILL overwrite the existing
#		Makefile IF a yMakefile exists!
#
######################################################################

#

if (-e /usr/ccs/lib/cpp) then
	set cpp = /usr/ccs/lib/cpp
else 
	set cpp = /lib/cpp
endif

set defines

if ("$NCARG" == "") then
	echo "NCARG environment variable must be set"
	exit 1
endif

set ymakefile
set outfile

set tmp1="ymake.tmp1"
/bin/rm -f $tmp1

if (-e "ymakefile") then
	set ymakefile="ymakefile"
	set outfile = "makefile"
else if (-e "yMakefile") then
	set ymakefile="yMakefile"
	set outfile = "Makefile"
else
	echo "no y(mM)akefile found"
	exit 1
endif

if (-e $outfile) then
	if (-e $outfile.bak) then
		/bin/rm -f $outfile.bak
	endif
	cp $outfile $outfile.bak
endif

onintr error_cleanup

# Determine the hostname of the machine, create a definition
# for it, and pass that to "cpp" so that yMakefiles can key
# off of it. This is used to install local host-specific
# configuration options permanently with the distribution.

set hostname

if (-e /bin/hostname) then
	set hostname    = `/bin/hostname`
endif

if (-e /usr/bsd/hostname) then
	set hostname    = `/usr/bsd/hostname`
endif

set hostname=host$hostname

set defines=($defines -D$hostname)

#
#	Figure out what kind of system we are on. We need to know the OS
#	and the machine architecture. 
#
set line = `$NCARG/install/install/uname -M -s`
if ($status != 0) then
	echo "ymake : Unknown operating system"
	exit 1
endif

set arch = $line[1]
set os = $line[2]

#
#	add os and arch to our defines list
#
set defines=($defines -D$os -D$arch)


# Leave the cpp commands unmolested but insert a C null comment
# in front of Makefile comment lines.  cpp will later remove these
# restoring the original form (plus a few blank lines).

sed <$ymakefile >! $tmp1 \
	-e '/^#[ 	]*if/b' \
	-e '/^#[ 	]*ifdef/b' \
	-e '/^#[ 	]*ifndef/b' \
	-e '/^#[ 	]*else/b' \
	-e '/^#[ 	]*elif/b' \
	-e '/^#[ 	]*endif/b' \
	-e '/^#[ 	]*define/b' \
	-e '/^#[ 	]*undef/b' \
	-e '/^#[ 	]*line/b' \
	-e '/^#[ 	]*include/b' \
	-e '/^#/s$$/**/_COMMENT_&$'

cat <<'EOF' >! $outfile
#######################################################################
#
#	This Makefile was created by the "ymake" utility.
#	If you wish to make changes in the "Makefile" or "makefile", 
#	do so by making changes to "yMakefile" or "ymakefile" 
#       and executing "make local-Makefile".
#
#######################################################################

'EOF'

echo '#include "Template"' | \
$cpp $argv[1-] -I. -D_COMMENT_="" -I$NCARG/config $defines \
-DYMAKEFILE=\"$tmp1\" | $NCARG/config/ymake-filter >>$outfile

/bin/rm -f $outfile.bak $tmp1
onintr
exit 0

error_cleanup:
echo ""
echo "Error in <ymake>: Interrupted in" `pwd` "- restoring $outfile"
/bin/rm -f $outfile $tmp1
cp $outfile.bak $outfile
/bin/rm -f $outfile.bak
exit 1
onintr


