C
C	$Id: example.f,v 1.1.1.1 1992-04-17 22:33:18 ncargd Exp $
C
      PROGRAM EXMPLE
      REAL Y(21)
C
C OPEN GKS, OPEN WORKSTATION OF TYPE 1, ACTIVATE WORKSTATION
C
      CALL GOPKS (6,IDUM) 
      CALL GOPWK (1, 2, 1)
      CALL GACWK (1) 
C
C Fill Y array for entry EZY of AUTOGRAPH.
C
      DO  10 I=1,21
         Y(I) = EXP(-.1*FLOAT(I))*COS(FLOAT(I)*.5)
   10 CONTINUE
C
      CALL EZY (Y(1),21,'DEMONSTRATING EZY ENTRY OF AUTOGRAPH$')
C
C     DEACTIVATE AND CLOSE WORKSTATION, CLOSE GKS.
C
      CALL GDAWK (1)
      CALL GCLWK (1)
      CALL GCLKS
C
      END
