C
C	$Id: pcfcls.f,v 1.1.1.1 1992-04-17 22:32:19 ncargd Exp $
C
      SUBROUTINE PCFCLS (IBNU,NFNT)
	IF (NFNT.EQ.0) THEN
	  CLOSE (UNIT=IBNU,STATUS='KEEP',ERR=101)
	ELSE
	  CALL BCLRED (IBNU,IOST,ISTA)
	  IF (ISTA.NE.0) THEN
	    PRINT * , 'PCFCLS - ERROR CLOSING FONT ',NFNT
	    STOP
	  END IF
	END IF
	RETURN
  101   PRINT * , 'PCFCLS - ERROR CLOSING PWRITX DATABASE'
	STOP
      END
