C
C	$Id: pcfred.f,v 1.1.1.1 1992-04-17 22:32:19 ncargd Exp $
C
      SUBROUTINE PCFRED (IBNU,NFNT,IBUF,LBUF)
	DIMENSION IBUF(LBUF)
	IF (NFNT.EQ.0) THEN
	  READ (IBNU,ERR=101) (IBUF(I),I=1,LBUF)
	ELSE
	  CALL BINRED (IBNU,LBUF,IBUF,IOST,ISTA)
	  IF (ISTA.NE.0) THEN
	    PRINT * , 'PCFRED - ERROR READING FONT ',NFNT
	    STOP
	  END IF
	END IF
	RETURN
  101   PRINT * , 'PCFRED - ERROR READING PWRITX DATABASE'
	STOP
      END
