C
C	$Id: pwrybd.f,v 1.1.1.1 1992-04-17 22:31:35 ncargd Exp $
C
      BLOCKDATA PWRYBD
      COMMON /PWRCOM/ USABLE
      LOGICAL         USABLE
      DATA USABLE/.FALSE./
C REVISION HISTORY------
C FEBURARY 1979    CREATED NEW ALGORITHM PWRITY TO REPLACE PWRY
C                  ADDED REVISION HISTORY
C JUNE 1979        CHANGE ARGUMENT THETA IN PWRITY FROM FLOATING TO
C                  INTEGER, USING ITHETA AS THE NEW NAME.  ITS
C                  MEANING IS NOW DEGREES INSTEAD OF RADIANS.
C JULY 1984        CONVERTED TO FORTRAN 77 AND GKS
C-----------------------------------------------------------------------
      END
