C
C	$Id: pwrxbd.f,v 1.5 2008-07-27 00:17:21 haley Exp $
C                                                                      
C                Copyright (C)  2000
C        University Corporation for Atmospheric Research
C                All Rights Reserved
C
C The use of this Software is governed by a License Agreement.
C
C
      SUBROUTINE PWRXBD
C
C Calling this do-nothing subroutine forces "ld" to load the following
C block data routine (but only if they are in the same ".f" file).
C
        RETURN
C
      END
CNOSPLIT
      BLOCKDATA PWRXBDX
C
C
C  SAVE DATA VALUES FOR LATER PASSES
C
      COMMON/PWRSV1/NNWD,NUMU5,INDLEN,IDDLEN,NUNIT
C
C  INITIALIZATION FOR MASK GENERATION
C
      COMMON/PINIT1/IFRST
      LOGICAL IFRST
C
C  MASKING AND OTHER MACHINE-DEPENDENT CONSTANTS WHICH MUST BE
C  CALCULATED.
C
      COMMON/PINIT/MASK(4),MASK6(64),MASK12(64),LAST6,LAST12,IBIT15,
     +        MASK14,NUM15U,NBWD
C
C INITIALIZATION FOR SUBROUTINES PWRITX AND XTCH.
      COMMON /PWRC2/ INDZER
C
C INITIALIZATION FOR SUBROUTINE PWRITX.
      LOGICAL FINIT
      COMMON /PSAV1/ FINIT,IFNT,IC,IT,ITO,RLX,RLY,RLOX,RLOY
C
C INITIALIZATION FOR SUBROUTINE PWRITX.
      COMMON /PUSER/ MODE
C
C
C  IFRST IS USED BY XTCH TO DECIDE IF MASKS HAVE BEEN GENERATED
C
      DATA IFRST/.FALSE./
C INDZER IS PUT INTO ARRAY LC BY ROUTINE XTCH TO INDICATE TO ROUTINE
C PWRITX THAT AN ALL-0-BITS UNIT WAS ENCOUNTERED.
C
      DATA INDZER /-2048/
C
C FINIT IS USED IN SUBROUTINE PWRITX. IT IS A FLAG TO INDICATE IF SOME
C REQUIRED INITIALIZATION HAS BEEN DONE.
C
      DATA FINIT /.FALSE./
C
C INITIALIZE INDICES TO ROMAN,PRINCIPAL, AND UPPER.
C
      DATA IFNT,IC,IT /0,0,0/
C
C INITIALIZE PREVIOUS CHARACTER SIZE TO PRINCIPAL.
C
      DATA ITO /0/
C
C INITIALIZE CHARACTER SIZE AND PREVIOUS CHARACTER SIZE TO PRINCIPAL.
C
      DATA RLX,RLY,RLOX,RLOY /16.0,32.0,16.0,32.0/
C
C INITIALIZE THE CHARACTER SET TO BE USED TO COMPLEX.
C
      DATA MODE /0/
C
C
      END
