      SUBROUTINE DSSETC(PNAM,CVAL)
C
      CHARACTER*(*) PNAM,CVAL
C
      ILEN = LEN(CVAL)
      CALL FDSSETC(PNAM,CVAL,ILEN)
C
      RETURN
      END
      SUBROUTINE DSGETC(PNAM,CVAL)
C
      CHARACTER*(*) PNAM,CVAL
C
      ILEN = LEN(CVAL)
      CALL FDSGETC(PNAM,CVAL,ILEN)
C
      RETURN
      END
