C
C	$Id: frst3.f,v 1.1.1.1 1992-04-17 22:31:46 ncargd Exp $
C
      SUBROUTINE FRST3 (U,V,W)
      SAVE
C
C THE FOLLOWING CALL IS FOR GATHERING STATISTICS ON LIBRARY USE AT NCAR
C
      CALL Q8QST4 ('GRAPHX','THREED','FRST3','VERSION  1')
      XDUM = 5.
      CALL TRN32T (U,V,W,X,Y,XDUM,2)
      CALL PLOTIT  (32*IFIX(X),32*IFIX(Y),0)
      RETURN
      END
