C
C	$Id: tick3.f,v 1.1.1.1 1992-04-17 22:31:48 ncargd Exp $
C
      SUBROUTINE TICK3 (MAG,MIN)
      SAVE
C
C THE FOLLOWING CALL IS FOR GATHERING STATISTICS ON LIBRARY USE AT NCAR
C
      CALL Q8QST4 ('GRAPHX','THREED','TICK3','VERSION  1')
      CALL TICK43 (MAG,MIN,MAG,MIN,MAG,MIN)
      RETURN
      END
