C
C	$Id: vect3.f,v 1.1.1.1 1992-04-17 22:31:46 ncargd Exp $
C
      SUBROUTINE VECT3 (U,V,W)
      SAVE
C
C THE FOLLOWING CALL IS FOR GATHERING STATISTICS ON LIBRARY USE AT NCAR
C
      CALL Q8QST4 ('GRAPHX','THREED','VECT3','VERSION  1')
      CALL TRN32T (U,V,W,X,Y,ZDUM,2)
      IIX = 32*IFIX(X)
      IIY = 32*IFIX(Y)
      CALL PLOTIT  (IIX,IIY,1)
C
C     FLUSH PLOTIT BUFFER
C
      CALL PLOTIT  (IIX,IIY,0)
      RETURN
      END
