C
C	$Id: cmptit.f,v 1.1 1992-09-29 16:10:22 ncargd Exp $
C
	PROGRAM MAPTIT
C
C The program EXMPL5 produces a single frame with maximal-area
C views of all the EZMAP projections of the globe.
C
C Define area map array and size for area fill applications
C
	PARAMETER (LMAP=250000, MCS=10000, NIDS=2)
	INTEGER MAP(LMAP), IAREA(NIDS), IGRP(NIDS)
	REAL XCS(MCS), YCS(MCS)
C
C Declare masking and area shading routines external
C
	EXTERNAL MASK
	EXTERNAL SHADE1
	EXTERNAL SHADE2
	EXTERNAL CFILL
C
C Open GKS.
C
	CALL OPNGKS
C
C Turn off the clipping indicator.
C
	CALL GSCLIP (0)
C
C Set up color table
C 
	CALL COLOR
C
C Set the outline-dataset parameter.
C
	CALL MAPSTC ('OU - OUTLINE DATASET SELECTOR','CO')
	CALL MAPSTI ('LA - LABEL FLAG',0)
C
C Put meridians and parallels every 15 degrees.
C
	CALL MAPSTI ('GR - GRID SPACING',15)
C
C Don't draw labels
C
	CALL MAPSTI ('LA - LABEL FLAG',0)
C
C Do draw elliptical perimeter
C
	CALL MAPSTI ('EL - ELLIPTICAL-PERIMETER SELECTOR',1)
C
C Lambert conformal conic.
C
	CALL MAPPOS (.025,.24375,.63125,.85)
	CALL MAPROJ ('LC',30.,0.,45.)
	CALL MAPINT
C Yellow Grid
	CALL GSPLCI (13)
	CALL MAPGRD
	CALL MAPLBL
C Green Contenental Outline
	CALL GSPLCI (6)
	CALL MAPLOT
C
C Stereographic.
C
	CALL MAPPOS (.26875,.4875,.63125,.85)
	CALL MAPROJ ('ST',0.,0.,0.)
C Aqua
	CALL MAPINT
	CALL GSPLCI (8)
	CALL MAPGRD
	CALL MAPLBL
C Chartreuse
	CALL GSPLCI (2)
	CALL MAPLOT
C
C Orthographic.
C
	CALL MAPPOS (.5125,.73125,.63125,.85)
	CALL MAPROJ ('OR',0.,0.,0.)
C Orchid
	CALL MAPINT
	CALL GSPLCI (15)
	CALL MAPGRD
	CALL MAPLBL
C SlateBlue
	CALL GSPLCI (8)
	CALL MAPLOT
C
C Lambert equal-area.
C
	CALL MAPPOS (.75625,.975,.63125,.85)
	CALL MAPROJ ('LE',0.,0.,0.)
C Red
	CALL MAPINT
	CALL GSPLCI (3)
	CALL MAPGRD
	CALL MAPLBL
C Yellow
	CALL GSPLCI (6)
	CALL MAPLOT
C
C Gnomonic.
C
C Draw lat/lon lines only over the oceans
	CALL GSPLCI (1)
	CALL MAPPOS (.025,.24375,.3875,.60625)
	CALL MAPROJ ('GN',0.,0.,0.)
	CALL ARINAM (MAP, LMAP)
	CALL MAPINT
	CALL MAPBLA (MAP)
	CALL MAPGRM (MAP, XCS, YCS, MCS, IAREA, IGRP, NIDS, MASK)
	CALL MAPLBL
	CALL MAPLOT
C
C Azimuthal equidistant.
C
	CALL ARINAM (MAP, LMAP)
	CALL MAPPOS (.26875,.4875,.3875,.60625)
	CALL MAPROJ ('AE',0.,0.,0.)
	CALL MAPINT
	CALL MAPBLA (MAP)
	CALL MAPGRM (MAP, XCS, YCS, MCS, IAREA, IGRP, NIDS, MASK)
	CALL GSPLCI (2)
	CALL MAPLBL
	CALL MAPLOT 
C
C Satellite-view.
C
C Do this plot in white with Softfill over the water and no lat/lon
C lines
	CALL ARINAM (MAP, LMAP)
	CALL GSPLCI (1)
	CALL MAPPOS (.5125,.73125,.3875,.60625)
	CALL MAPROJ ('SV',0.,0.,0.)
	CALL MAPSTR ('SA - SATELLITE DISTANCE',2.)
	CALL MAPSTC ('OU - OUTLINE DATASET SELECTOR','PO')
	CALL MAPINT
	CALL MAPBLA (MAP)
	CALL ARSCAM (MAP, XCS, YCS, MCS, IAREA, IGRP, NIDS, SHADE1)
	CALL MAPLBL
	CALL MAPLOT
C
C Mercator.
C
	CALL ARINAM (MAP, LMAP)
	CALL GSPLCI (1)
	CALL MAPPOS (.75625,.975,.3875,.60625)
	CALL MAPROJ ('ME',0.,0.,0.)
	CALL MAPINT
	CALL MAPBLA (MAP)
	CALL ARSCAM (MAP, XCS, YCS, MCS, IAREA, IGRP, NIDS, SHADE2)
	CALL MAPLBL
	CALL MAPLOT
C
C Cylindrical equidistant.
C
	CALL ARINAM (MAP, LMAP)
	CALL GSPLCI (1)
	CALL MAPPOS (.025,.4875,.13125,.3625)
	CALL MAPROJ ('CE',0.,0.,0.)
	CALL MAPINT
	CALL MAPBLA (MAP)
	CALL ARSCAM (MAP, XCS, YCS, MCS, IAREA, IGRP, NIDS, CFILL)
	CALL MAPLBL
	CALL MAPLOT
C
C Mollweide type.
C
	CALL ARINAM (MAP, LMAP)
	CALL GSPLCI (1)
	CALL MAPPOS (.5125,.975,.13125,.3625)
	CALL MAPROJ ('MO',0.,0.,0.)
	CALL MAPINT
	CALL MAPBLA (MAP)
	CALL ARSCAM (MAP, XCS, YCS, MCS, IAREA, IGRP, NIDS, CFILL)
	CALL MAPLBL
	CALL MAPLOT
C
C and the labels under each sub-plot.
C
	CALL SET (0.,1.,0.,1.,0.,1.,0.,1.,1)
	CALL PLCHHQ (.134375,.61875,'LAMBERT CONFORMAL CONIC',
     +                                          .0085,0.,0.)
	CALL PLCHHQ (.378125,.61875,'STEREOGRAPHIC',
     +						.0085,0.,0.)
	CALL PLCHHQ (.621875,.61875,'ORTHOGRAPHIC',
     +						.0085,0.,0.)
	CALL PLCHHQ (.865625,.61875,'LAMBERT EQUAL-AREA',
     +						.0085,0.,0.)
	CALL PLCHHQ (.134375,.375,'GNOMONIC',
     +						.0085,0.,0.)
	CALL PLCHHQ (.378125,.375,'AZIMUTHAL EQUIDISTANT',
     +						.0085,0.,0.)
	CALL PLCHHQ (.621875,.375,'SATELLITE-VIEW',
     +						.0085,0.,0.)
	CALL PLCHHQ (.865625,.375,'MERCATOR',
     +						.0085,0.,0.)
	CALL PLCHHQ (.25625,.11875,'CYLINDRICAL EQUIDISTANT',
     +                                          .0085,0.,0.)
	CALL PLCHHQ (.74375,.11875,'MOLLWEIDE TYPE',
     +						.0085,0.,0.)
C
C Draw a boundary around the edge of the plotter frame.
C
c      CALL BNDARY
C
C Advance the frame.
C
	CALL FRAME
C
C Close GKS.
C
	CALL CLSGKS
C
C Done.
C
	STOP
C
	END
*	SUBROUTINE MAPEOD (NOUT,NSEG,IDLS,IDRS,NPTS,PNTS)
C
*	DIMENSION PNTS(*)
C
C This version of MAPEOD uses area identifiers for the outline
C dataset 'CO' to suppress all but the major global land masses.
C
*	IF (IDLS.NE.  2.AND.IDRS.NE.  2) NPTS=0
C
*	IF (IDLS.NE.  1.AND.IDRS.NE.  1.AND.
*     +    IDLS.NE.  3.AND.IDRS.NE.  3.AND.
*     +    IDLS.NE. 11.AND.IDRS.NE. 11.AND.
*     +    IDLS.NE. 79.AND.IDRS.NE. 79.AND.
*     +    IDLS.NE. 99.AND.IDRS.NE. 99.AND.
*     +    IDLS.NE.104.AND.IDRS.NE.104.AND.
*     +    IDLS.NE.107.AND.IDRS.NE.107.AND.
*     +    IDLS.NE.163.AND.IDRS.NE.163     ) NPTS=0
C
C Done.
C
*	RETURN
C
*	END
