      SUBROUTINE NNSETC(PNAM,CVAL)
C
      CHARACTER*(*) PNAM,CVAL
C
      ILEN = LEN(CVAL)
      CALL FNNSETC(PNAM,CVAL,ILEN)
C
      RETURN
      END
      SUBROUTINE NNGETC(PNAM,CVAL)
C
      CHARACTER*(*) PNAM,CVAL
C
      ILEN = LEN(CVAL)
      CALL FNNGETC(PNAM,CVAL,ILEN)
C
      RETURN
      END
