      SUBROUTINE NNSETC(PNAM,CVAL)
C
      CHARACTER*(*) PNAM,CVAL
C
      ILEN = LEN(CVAL)
      CALL F_NNSETC(PNAM,CVAL,ILEN)
C
      RETURN
      END
      SUBROUTINE NNGETC(PNAM,CVAL)
C
      CHARACTER*(*) PNAM,CVAL
C
      ILEN = LEN(CVAL)
      CALL F_NNGETC(PNAM,CVAL,ILEN)
C
      RETURN
      END
