C
C       $Id: gerlog.f,v 1.4 1994-05-28 00:42:20 fred Exp $
C
      SUBROUTINE GERLOG(ERRNR,FCTID,ERRFIL)
C
C  ERROR LOGGING
C
      include 'gkscom.h'
C
      INTEGER ERRNR,FCTID,ERRFIL
C
C  Number of error messages.  To add a new error message, increase this
C  parameter appropriately and add the error number and error message
C  to the arrays IERNMS and ERMSGS defined in DATA statements below.
C
      PARAMETER(NUMERS=115)
C
C  Array containing the GKS error numbers.
C
      INTEGER      IERNMS(NUMERS)
C
C  Array containing the error messages associated with the error numbers
C  in the IERNMS array.
C
      CHARACTER*90 ERMSGS(NUMERS)
C
      CHARACTER*6  IFMT
C
      SAVE
C
C  Define the error numbers and associated messages.
C
      DATA IERNMS(  1)/   1/
      DATA ERMSGS(  1)/' --GKS NOT IN PROPER STATE: GKS SHALL BE IN STAT
     +E GKCL'/
C
      DATA IERNMS(  2)/   2/
      DATA ERMSGS(  2)/' --GKS NOT IN PROPER STATE: GKS SHALL BE IN STAT
     +E GKOP'/
C
      DATA IERNMS(  3)/   3/
      DATA ERMSGS(  3)/' --GKS NOT IN PROPER STATE: GKS SHALL BE IN STAT
     +E WSAC'/
C
      DATA IERNMS(  4)/   4/
      DATA ERMSGS(  4)/' --GKS NOT IN PROPER STATE: GKS SHALL BE IN STAT
     +E SGOP'/
C
      DATA IERNMS(  5)/   5/
      DATA ERMSGS(  5)/' --GKS NOT IN PROPER STATE: GKS SHALL BE EITHER 
     +IN THE STATE WSAC OR IN THE STATE SGOP'/
C
      DATA IERNMS(  6)/   6/
      DATA ERMSGS(  6)/' --GKS NOT IN PROPER STATE: GKS SHALL BE EITHER 
     +IN THE STATE WSOP OR IN THE STATE WSAC'/
C
      DATA IERNMS(  7)/   7/
      DATA ERMSGS(  7)/' --GKS NOT IN PROPER STATE: GKS SHALL BE IN ONE 
     +OF THE STATES  WSOP, WSAC, OR SGOP'/
C
      DATA IERNMS(  8)/   8/
      DATA ERMSGS(  8)/' --GKS NOT IN PROPER STATE: GKS SHALL BE IN ONE 
     +OF THE STATES  GKOP, WSOP, WSAC, OR SGOP'/
C
      DATA IERNMS(  9)/  20/
      DATA ERMSGS(  9)/' --SPECIFIED WORKSTATION IDENTIFIER IS INVALID  
     +'/
C
      DATA IERNMS( 10)/  21/
      DATA ERMSGS( 10)/' --SPECIFIED CONNECTION IDENTIFIER IS INVALID'/
C
      DATA IERNMS( 11)/  22/
      DATA ERMSGS( 11)/' --SPECIFIED WORKSTATION TYPE IS INVALID'/
C
      DATA IERNMS( 12)/  23/
      DATA ERMSGS( 12)/' --SPECIFIED WORKSTATION TYPE DOES NOT EXIST'/
C
      DATA IERNMS( 13)/  24/
      DATA ERMSGS( 13)/' --SPECIFIED WORKSTATION IS OPEN'/
C
      DATA IERNMS( 14)/  25/
      DATA ERMSGS( 14)/' --SPECIFIED WORKSTATION IS NOT OPEN'/
C
      DATA IERNMS( 15)/  26/
      DATA ERMSGS( 15)/' --SPECIFIED WORKSTATION CANNOT BE OPENED'/
C
      DATA IERNMS( 16)/  27/
      DATA ERMSGS( 16)/' --WORKSTATION INDEPENDENT SEGMENT STORAGE IS NO       
     +T OPEN'/
C
      DATA IERNMS( 17)/  28/
      DATA ERMSGS( 17)/' --WORKSTATION INDEPENDENT SEGMENT STORAGE IS AL
     +READY OPEN'/
C
      DATA IERNMS( 18)/  29/
      DATA ERMSGS( 18)/' --SPECIFIED WORKSTATION IS ACTIVE'/
C
      DATA IERNMS( 19)/  30/
      DATA ERMSGS( 19)/' --SPECIFIED WORKSTATION IS NOT ACTIVE'/
C
      DATA IERNMS( 20)/  32/
      DATA ERMSGS( 20)/' --SPECIFIED WORKSTATION IS NOT OF CATEGORY MO'/
C
      DATA IERNMS( 21)/  33/
      DATA ERMSGS( 21)/' --SPECIFIED WORKSTATION IS OF CATEGORY MI'/
C
      DATA IERNMS( 22)/  34/
      DATA ERMSGS( 22)/' --SPECIFIED WORKSTATION IS NOT OF CATEGORY MI'/
C
      DATA IERNMS( 23)/  35/
      DATA ERMSGS( 23)/' --SPECIFIED WORKSTATION IS OF CATEGORY INPUT'/
C
      DATA IERNMS( 24)/  36/
      DATA ERMSGS( 24)/' --SPECIFIED WORKSTATION IS WORKSTATION INDEPEND       
     +ENT SEGMENT STORAGE'/
C
      DATA IERNMS( 25)/  38/
      DATA ERMSGS( 25)/' --SPECIFIED WORKSTATION IS NEITHER OF CATEGORY 
     +INPUT NOR OF CATEGORY OUTIN'/
C
      DATA IERNMS( 26)/  50/
      DATA ERMSGS( 26)/' --TRANSFORMATION NUMBER IS INVALID'/
C
      DATA IERNMS( 27)/  51/
      DATA ERMSGS( 27)/' --RECTANGLE DEFINITION IS INVALID'/
C
      DATA IERNMS( 28)/  52/
      DATA ERMSGS( 28)/' --VIEWPORT IS NOT WITHIN THE NORMALIZED DEVICE 
     +COORDINATE UNIT SQUARE'/
C
      DATA IERNMS( 29)/  53/
      DATA ERMSGS( 29)/' --WORKSTATION WINDOW IS NOT WITHIN THE NORMALIZ
     +ED DEVICE COORDINATE UNIT SQUARE'/
C
      DATA IERNMS( 30)/  54/
      DATA ERMSGS( 30)/' --WORKSTATION VIEWPORT IS NOT WITHIN THE DISPLA
     +Y SPACE'/
C
      DATA IERNMS( 31)/  60/
      DATA ERMSGS( 31)/' --POLYLINE INDEX IS INVALID'/
C
      DATA IERNMS( 32)/  63/
      DATA ERMSGS( 32)/' --LINETYPE IS LESS THAN OR EQUAL TO ZERO'/
C
      DATA IERNMS( 33)/  65/
      DATA ERMSGS( 33)/' --LINEWIDTH SCALE FACTOR IS LESS THAN ZERO'/
C
      DATA IERNMS( 34)/  66/
      DATA ERMSGS( 34)/' --POLYMARKER INDEX IS INVALID'/
C
      DATA IERNMS( 35)/  69/
      DATA ERMSGS( 35)/' --MARKER TYPE IS LESS THAN OR EQUAL TO ZERO'/
C
      DATA IERNMS( 36)/  72/
      DATA ERMSGS( 36)/' --TEXT INDEX IS INVALID'/
C
      DATA IERNMS( 37)/  75/
      DATA ERMSGS( 37)/' --TEXT FONT IS EQUAL TO ZERO'/
C
      DATA IERNMS( 38)/  77/
      DATA ERMSGS( 38)/' --CHARACTER EXPANSION FACTOR IS LESS THAN OR EQ
     +UAL TO ZERO'/
C
      DATA IERNMS( 39)/  78/
      DATA ERMSGS( 39)/' --CHARACTER HEIGHT IS LESS THAN OR EQUAL TO ZER
     +O'/
C
      DATA IERNMS( 40)/  79/
      DATA ERMSGS( 40)/' --LENGTH OF CHARACTER UP VECTOR IS ZERO'/
C
      DATA IERNMS( 41)/  80/
      DATA ERMSGS( 41)/' --FILL AREA INDEX IS INVALID'/
C
      DATA IERNMS( 42)/  84/
      DATA ERMSGS( 42)/' --STYLE (PATTERN OR HATCH) INDEX IS LESS THAN O
     +R EQUAL TO ZERO'/
C
      DATA IERNMS( 43)/  85/
      DATA ERMSGS( 43)/' --SPECIFIED PATTERN INDEX IS INVALID'/
C
      DATA IERNMS( 44)/  87/
      DATA ERMSGS( 44)/' --PATTERN SIZE VALUE IS NOT POSITIVE'/
C
      DATA IERNMS( 45)/  91/
      DATA ERMSGS( 45)/' --DIMENSIONS OF COLOR ARRAY ARE INVALID'/
C
      DATA IERNMS( 46)/  92/
      DATA ERMSGS( 46)/' --COLOR INDEX IS LESS THAN ZERO'/
C
      DATA IERNMS( 47)/  93/
      DATA ERMSGS( 47)/' --COLOR INDEX IS INVALID'/
C
      DATA IERNMS( 48)/  96/
      DATA ERMSGS( 48)/' --COLOR IS OUTSIDE RANGE ZERO TO ONE INCLUSIVE'
     +/      
C
      DATA IERNMS( 49)/ 100/
      DATA ERMSGS( 49)/' --NUMBER OF POINTS IS INVALID'/
C
      DATA IERNMS( 50)/ 101/
      DATA ERMSGS( 50)/' --INVALID CODE IN STRING'/
C
      DATA IERNMS( 51)/ 102/
      DATA ERMSGS( 51)/' --GENERALIZED DRAWING PRIMITIVE IDENTIFIER IS I       
     +NVALID'/
C
      DATA IERNMS( 52)/ 103/
      DATA ERMSGS( 52)/' --CONTENT OF GENERALIZED DRAWING PRIMITIVE DATA
     + RECORD IS INVALID'/
C
      DATA IERNMS( 53)/ 120/
      DATA ERMSGS( 53)/' --SPECIFIED SEGMENT NAME IS INVALID'/
C
      DATA IERNMS( 54)/ 121/
      DATA ERMSGS( 54)/' --SPECIFIED SEGMENT NAME IS ALREADY IN USE'/
C
      DATA IERNMS( 55)/ 122/
      DATA ERMSGS( 55)/' --SPECIFIED SEGMENT DOES NOT EXIST'/
C
      DATA IERNMS( 56)/ 124/
      DATA ERMSGS( 56)/' --SPECIFIED SEGMENT DOES NOT EXIST ON WORKSTATI
     +ON INDEPENDENT SEGMENT STORAGE'/
C
      DATA IERNMS( 57)/ 160/
      DATA ERMSGS( 57)/' --ITEM TYPE IS NOT ALLOWED FOR USER ITEMS'/
C
      DATA IERNMS( 58)/ 161/
      DATA ERMSGS( 58)/' --ITEM LENGTH IS INVALID'/
C
      DATA IERNMS( 59)/ 162/
      DATA ERMSGS( 59)/' --NO ITEM IS LEFT IN GKS METAFILE INPUT'/
C
      DATA IERNMS( 60)/ 163/
      DATA ERMSGS( 60)/' --METAFILE ITEM IS INVALID'/
C
      DATA IERNMS( 61)/ 165/
      DATA ERMSGS( 61)/' --CONTENT OF ITEM DATA RECORD IS INVALID FOR TH
     +E SPECIFIED ITEM TYPE'/
C
      DATA IERNMS( 62)/ 166/
      DATA ERMSGS( 62)/' --MAXIMUM ITEM DATA RECORD LENGTH IS INVALID'/
C
      DATA IERNMS( 63)/ 167/
      DATA ERMSGS( 63)/' --USER ITEM CANNOT BE INTERPRETED'/
C
      DATA IERNMS( 64)/ 168/
      DATA ERMSGS( 64)/' --SPECIFIED FUNCTION IS NOT SUPPORTED IN THIS L
     +EVEL OF GKS'/
C
      DATA IERNMS( 65)/ 180/
      DATA ERMSGS( 65)/' --SPECIFIED ESCAPE FUNCTION IS NOT SUPPORTED'/
C
      DATA IERNMS( 66)/ 182/
      DATA ERMSGS( 66)/' --CONTENTS OF ESCAPE DATA RECORD ARE INVALID'/
C
      DATA IERNMS( 67)/ 300/
      DATA ERMSGS( 67)/' --STORAGE OVERFLOW HAS OCCURRED IN GKS'/
C
      DATA IERNMS( 68)/ 302/
      DATA ERMSGS( 68)/' --INPUT/OUTPUT ERROR HAS OCCURRED WHILE READING
     +'/     
C
      DATA IERNMS( 69)/ 303/
      DATA ERMSGS( 69)/' --INPUT/OUTPUT ERROR HAS OCCURRED WHILE WRITING
     +'/
C
      DATA IERNMS( 70)/ 304/
      DATA ERMSGS( 70)/' --INPUT/OUTPUT ERROR HAS OCCURRED WHILE SENDING
     + DATA TO A WORKSTATION'/
C
      DATA IERNMS( 71)/ 305/
      DATA ERMSGS( 71)/' --INPUT/OUTPUT ERROR HAS OCCURRED WHILE RECEIVI
     +NG DATA FROM A WORKSTATION'/
C
      DATA IERNMS( 72)/ 306/
      DATA ERMSGS( 72)/' --INPUT/OUTPUT ERROR HAS OCCURRED DURING PROGRA
     +M LIBRARY MANAGEMENT'/
C
      DATA IERNMS( 73)/ 307/
      DATA ERMSGS( 73)/' --INPUT/OUTPUT ERROR HAS OCCURRED WHILE READING
     + WORKSTATION DESCRIPTION TABLE'/
C
      DATA IERNMS( 74)/ 308/
      DATA ERMSGS( 74)/' --ARITHMETIC ERROR HAS OCCURRED'/
C
      DATA IERNMS( 75)/2000/
      DATA ERMSGS( 75)/' --ENUMERATION TYPE OUT OF RANGE'/
C
      DATA IERNMS( 76)/2001/
      DATA ERMSGS( 76)/' --OUTPUT PARAMETER SIZE INSUFFICIENT'/
C
      DATA IERNMS( 77)/2002/
      DATA ERMSGS( 77)/' --LIST OR SET ELEMENT NOT AVAILABLE'/
C
      DATA IERNMS( 78)/2003/
      DATA ERMSGS( 78)/' --INVALID DATA RECORD'/
C
      DATA IERNMS( 79)/-100/
      DATA ERMSGS( 79)/' --UNKNOWN ERROR CODE'/
C
      DATA IERNMS( 80)/-101/
      DATA ERMSGS( 80)/' --NO ADDITIONAL WORKSTATIONS MAY BE ACTIVATED'/       
C
      DATA IERNMS( 81)/-102/
      DATA ERMSGS( 81)/' --GKS SYSTEM ERROR--IMPROPER CONTINUATION SEQUE
     +NCE'/
C
      DATA IERNMS( 82)/-103/
      DATA ERMSGS( 82)/' --THE NCAR GKS IMPLEMENTATION REQUIRES THAT WIS
     +S BE ACTIVE BEFORE A SEGMENT IS CREATED'/
C
      DATA IERNMS( 83)/-105/
      DATA ERMSGS( 83)/' --ERROR OPENING DISK FILE'/
C
      DATA IERNMS( 84)/-106/
      DATA ERMSGS( 84)/' --LOGICAL UNIT NUMBER FOR SEGMENT STORAGE CANNO
     +T BE THE SAME AS THAT FOR METAFILE OUTPUT'/
C
      DATA IERNMS( 85)/-107/
      DATA ERMSGS( 85)/' --MAXIMUM NUMBER OF ERROR MESSAGES EXCEEDED'/
C
      DATA IERNMS( 86)/-108/
      DATA ERMSGS( 86)/' --ILLEGAL PLACEMENT OF A CALL TO ASSIGN A PICTU
     +RE NAME'/
C
      DATA IERNMS( 87)/-109/
      DATA ERMSGS( 87)/' --THIS FUNCTION NOT YET IMPLEMENTED FOR WORKSTA
     +TIONS OF CATEGORY OUTPUT'/
C
      DATA IERNMS( 88)/-110/
      DATA ERMSGS( 88)/' --CHARACTER STRING TOO LARGE'/
C
      DATA IERNMS( 89)/-111/
      DATA ERMSGS( 89)/' --SYSTEM ERROR'/
C
      DATA IERNMS( 90)/-112/
      DATA ERMSGS( 90)/' --ONLY ONE METAFILE WORKSTATION CAN BE OPEN AT 
     +A TIME'/
C
      DATA IERNMS( 91)/-200/
      DATA ERMSGS( 91)/' --X driver error: memory allocation in processi
     +ng a character from a fontcap'/
C
      DATA IERNMS( 92)/-201/
      DATA ERMSGS( 92)/' --X driver error: error opening fontcap'/
C
      DATA IERNMS( 93)/-202/
      DATA ERMSGS( 93)/' --X driver error: error reading fontcap'/
C
      DATA IERNMS( 94)/-203/
      DATA ERMSGS( 94)/' --X driver warning: invalid font index, using t
     +he default font'/
C
      DATA IERNMS( 95)/-204/
      DATA ERMSGS( 95)/' --X driver error: memory allocation error in cr
     +eating device table'/
C
      DATA IERNMS( 96)/-205/
      DATA ERMSGS( 96)/' --X driver error: too many open devices'/
C
      DATA IERNMS( 97)/-206/
      DATA ERMSGS( 97)/' --X driver error: error in internal memory mana
     +gement'/
C
      DATA IERNMS( 98)/-207/
      DATA ERMSGS( 98)/' --X driver error: error in allocating memory fo
     +r device dependent table'/
C
      DATA IERNMS( 99)/-208/
      DATA ERMSGS( 99)/' --X driver error: DISPLAY environment variable 
     +not set'/
C
      DATA IERNMS(100)/-209/
      DATA ERMSGS(100)/' --X driver error: error opening display'/
C
      DATA IERNMS(101)/-210/
      DATA ERMSGS(101)/' --X driver error: error getting window attribut
     +es'/
C
      DATA IERNMS(102)/-211/
      DATA ERMSGS(102)/' --X driver error: error creating pixmap'/
C
      DATA IERNMS(103)/-212/
      DATA ERMSGS(103)/' --X driver error: cell array has zero width or 
     +height'/
C
      DATA IERNMS(104)/-213/
      DATA ERMSGS(104)/' --X driver error: memory allocation error in pr
     +ocessing cell array'/
C
      DATA IERNMS(105)/-214/
      DATA ERMSGS(105)/' --X driver error: error creating X image'/
C
      DATA IERNMS(106)/-215/
      DATA ERMSGS(106)/' --X driver error: memory allocation error in cr
     +eating X image'/
C
      DATA IERNMS(107)/-216/
      DATA ERMSGS(107)/' --X driver error: pixel size must be byte multi
     +ple'/
C
      DATA IERNMS(108)/-300/
      DATA ERMSGS(108)/' --PostScript error: Encapsulated PostScript can
     + have only one page'/
C
      DATA IERNMS(109)/-301/
      DATA ERMSGS(109)/' --PostScript error: error in allocating memory 
     +for device dependent table'/
C
      DATA IERNMS(110)/-302/
      DATA ERMSGS(110)/' --PostScript error: error opening output file'/
C
      DATA IERNMS(111)/-303/
      DATA ERMSGS(111)/' --PostScript error: a character in the string h
     +as no PostScript equivalent, use Plotchar'/
C
      DATA IERNMS(112)/-217/
      DATA ERMSGS(112)/' --X driver error: error in retrieving fontcap n
     +ame'/
C
      DATA IERNMS(113)/-218/
      DATA ERMSGS(113)/' --X driver error: invalid index into GKS workst
     +ation identifiers'/
C
      DATA IERNMS(114)/-219/
      DATA ERMSGS(114)/' --X driver error: color index exceeds maximum a
     +llowed'/
C
      DATA IERNMS(115)/-220/
      DATA ERMSGS(115)/' --X driver error: cannot allocate color'/
C
C  Write the first line of the GKS error message to the error file.
C
      WRITE(ERRFIL,700) ERRNR,GNAM(FCTID+1)
  700 FORMAT(' GKS ERROR NUMBER',I5,' ISSUED FROM SUBROUTINE ',A6,':')
C
C  Determine the index into the error message array.
C
      DO 20 I=1,NUMERS
        IF (ERRNR .EQ. IERNMS(I)) THEN
          NDXER = I
          GO TO 50
        ENDIF
   20 CONTINUE
C
C  Error is unknown.
C
      NDXER = 79
   50 CONTINUE
C
C  Get the length of the error message.
C
      DO 30 J=90,1,-1
        IF (ERMSGS(NDXER)(J:J) .NE. ' ') THEN
          LENMSG = J
          GO TO 40
        ENDIF
   30 CONTINUE
      LENMSG = 1
   40 CONTINUE
C
C  Write out the error message.
C
      WRITE(IFMT,500) LENMSG
  500 FORMAT('(A',I3,')')
      WRITE(ERRFIL,IFMT) ERMSGS(NDXER)(1:LENMSG)
C
      RETURN
      END
