      COMMON /TRBUFR/ METBIT, MBUFER, MBFSAV, METREC, MRECLN,
     1		      MOPRST, MCONID
      INTEGER MNWRDS, RECLOC, RECSIZ, MBITST, MBUFOF,
     1	      MINSBD 
      PARAMETER (MNWRDS=360, RECLOC=0 , RECSIZ=16, 
     1		 MBITST=32 , MBUFOF=32, MINSBD=16)
      INTEGER METBIT, MBUFER(MNWRDS),  MBFSAV(MNWRDS), METREC, MRECLN, 
     1        MOPRST, MCONID
