      COMMON /TRCODE/ CELMVI, CELMCR, CELMCI,
     +                GPELPL, GPELPM, GPELTX, GPELPG, GPELCA, GPELGP,
     +                ATELLI, ATELLT, ATELLW, ATELLC, ATELMB, ATELMT,
     +                ATELMZ, ATELMC, ATELTI, ATELTF, ATELTP, ATELCE,
     +                ATELCS, ATELTC, ATELCH, ATELCO, ATELTH, ATELTA,
     +                ATELFI, ATELIS, ATELHI, ATELPI, ATELFC, ATELFR, 
     +                ATELPT, ATELPS, ATELCB, ATELAS
C
C  DEFINE THE TYPES OF THE COMMON DATA
C
      INTEGER CELMVI, CELMCR, CELMCI,
     +        GPELPL, GPELPM, GPELTX, GPELPG, GPELCA, GPELGP,
     +        ATELLI, ATELLT, ATELLW, ATELLC, ATELMB, ATELMT, ATELMZ,
     +        ATELMC, ATELTI, ATELTF, ATELTP, ATELCE, ATELCS, ATELTC,
     +        ATELCH, ATELCO, ATELTH, ATELTA, ATELFI, ATELIS, ATELHI,
     +        ATELPI, ATELFC, ATELFR, ATELPT, ATELPS, ATELCB, ATELAS
