      COMMON /TRDEFL/ POLIDF, LINTDF, LINWDF, TLNCDF, MARIDF, MARTDF,
     1		      MARSDF, TMRCDF, PMRSDF, HORIDF, VERTDF, PATHDF,
     2		      CHIGDF, XUDF, YUDF, XBDF, YBDF, TXTIDF, TTXCDF,
     3		      FINDDF, CEXPDF, CSPADF, FILIDF, INTSDF, PATIDF,
     4		      TFLCDF, HATIDF, FILRDF, TXTPDF
      REAL LINWDF, MARSDF, CEXPDF, CSPADF
      INTEGER POLIDF, LINTDF, TLNCDF, MARIDF,
     1	      MARTDF, TMRCDF, PMRSDF, HORIDF, VERTDF, PATHDF, CHIGDF,
     2	      XUDF, YUDF, XBDF, YBDF, TXTIDF, TTXCDF, FINDDF, FILIDF, 
     3	      INTSDF, PATIDF, TFLCDF, HATIDF, FILRDF(2), TXTPDF
