      COMMON /TRPARS/  MOPLEN, MCICPR, MFLCPR, MIXCPR, MWHCPR,
     1		       MOPDLN, MCIDPR, MFLDPR, MIXDPR, MWHDPR,
     2		       BYTSIZ, CONFLG, MENDPR, MENCPR
      INTEGER MOPCLL, MOPIDL, MSCLEN, MLGFLG, MCOLEN, MLOLEN
      PARAMETER (MOPCLL=4, MOPIDL=7, MCOLEN=1, MSCLEN=5, MLOLEN=15,
     1		 MLGFLG=31)
       INTEGER         MOPLEN, MCICPR, MFLCPR, MIXCPR, MWHCPR,
     1		       MOPDLN, MCIDPR, MFLDPR, MIXDPR, MWHDPR,
     2		       BYTSIZ, CONFLG, MENDPR, MENCPR
