.\"
.\"     $Id: ncarlogo2ps.m,v 1.1 2002-04-12 05:54:54 fred Exp $
.\"
.TH ncarlogo2ps 1NCARG "April 2002" UNIX "NCAR GRAPHICS"
.na
.nh
.SH NAME
ncarlogo2ps - adds NCAR logos to pre-existing PostScript files generated by NCAR Graphics.
.SH SYNOPSIS
usage: ncarlogo2ps [-s size] [-position x:y] [-angle ang]
.br
                   [-input input_file] [-output output_file]
.SH DESCRIPTION 
"ncarlogo2ps" takes as input a PostScript file created
from NCAR Graphics 3.2 or later, or created from a
"ctrans -d ps.color" command, and adds an NCAR logo
to each frame.
.sp
The options are:
.IP "-s size" 12
Specifies the height of the logo in inches.
The default is 0.517 inches.
.IP "-p position"
x:y specifies the X-Y position of the center
of the logo in inches.  Only the "-p" is
significant.  The default is 7.35:2.3
.IP "-angle ang"
Specifies the angle in degrees to rotate
the logo from the defualt upright position.
.IP "-input input_file"
Specifies the PostScript input file.  This
must have been generated by NCAR Graphics.
If no input option is specified, the input
defaults to standard in.
.IP "-output output_file"
Specifies the PostScript output file.  If
no output option is specified, the output
defaults to standard out.
.RE
.sp
The options may appear in any order and only the first
character is significant.
.SH EXAMPLE
ncarglogo2ps -s 0.75 -p 7.0:0.75 < input_file > ouptut_file
.sp
would place in the output file a logo 7 inches from the left
edge and 3/4" from the bottom with a height of 3/4".

.SH COPYRIGHT
Copyright (C) 2002
.br
University Corporation for Atmospheric Research
.br

This documentation is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This software is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this software; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA.

